### ISSUE TITLE
Add list of global CSS variables

### ISSUE THREAD

**Issue by camwiegert** [ionic-team/ionic-docs#101]
We need to add a list of all global variables (e.g. `--ion-statusbar-padding`) to [this page](https://github.com/ionic-team/ionic-docs/blob/master/src/content/theming/css-variables.md).

**Comment by brandyscarney** [comment]
I am thinking we should just manually document this. Thoughts?

**Comment by camwiegert** [comment]
@brandyscarney Agreed. I think that'll be simplest. Probably just add a table at the bottom of the page and link to it from the "Global Variables" section.

**Comment by brandyscarney** [comment]
Closed by https://github.com/ionic-team/ionic-docs/commit/bb35500ad4a7bb97c2e47206f4b7f1229ea3313e

We can iterate on this if desired.
