### ISSUE TITLE
v4 Doc: example of round button missing attribute shape

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-docs#103]
**I'm submitting a ...**  (check one with "x")
[ X] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/api/button

**Current behavior:**
Example of rounded buttons doesn't match doc and current way to display rounded buttons with v4, respectively:

    
    <ion-button round>Round Button</ion-button>
     ...
     <ion-button round fill="outline">Outline + Round</ion-button>

Doc itself is correct see

> shape
> Attribute:  shape Type: string
> The button shape. Possible values are: "round"

**Expected behavior:**

    
    <ion-button shape="round">Round Button</ion-button>
     ...
     <ion-button shape="round" fill="outline">Outline + Round</ion-button>

**Comment by brandyscarney** [comment]
Note that this has been fixed in latest just needs to be updated on the site: https://github.com/ionic-team/ionic/blob/master/core/src/components/button/usage/javascript.md
