### ISSUE TITLE
Color generator: broken UI in Safari

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#1037]
**Describe the bug**

<img width="1141" alt="Screen Shot 2019-10-21 at 11 02 56 AM" src="https://user-images.githubusercontent.com/6577830/67217243-672abc80-f3f2-11e9-8469-d0573cb8fb5b.png">

**To Reproduce**
1. Go to https://ionicframework.com/docs/theming/color-generator in Safari

**Browser and OS (please complete the following information):**
 - OS: [e.g. iOS] macOS
 - Browser [e.g. chrome, safari] Safari 
 - Version [e.g. 22] Version 12.1.1 (14607.2.6.1.1)

**Additional context**

**Comment by brandyscarney** [comment]
This works locally so no idea why it doesn't when hosted, any ideas @perrygovier ?

**Comment by peterpeterparker** [comment]
It looks like the css is not applied. No styles are applied to `color-gen-select-colors`, `.controls`, `. controls__item`, for example, as in Chrome of Firefox.

Is for some reason the related CSS not loaded in Safari?

**Comment by dotNetkow** [comment]
Fixed 2/12/2020.
