### ISSUE TITLE
The HTML code  examples are in one line

### ISSUE THREAD

**Issue by bleuscyther** [ionic-team/ionic-docs#1062]
**Describe the bug**
The HTML examples on the guide section are displayed in one line unlike the other sections 

**To Reproduce**
1. Go to 'https://beta.ionicframework.com/docs/layout/structure'
2. Check HTML examples

**Screenshots**
How it appears in the guide section:
![image](https://user-images.githubusercontent.com/2999487/68031393-f3aa6a00-fc91-11e9-9621-ec1bc45343cc.png)

How it appears on Github:
![image](https://user-images.githubusercontent.com/2999487/68031542-42580400-fc92-11e9-921f-e064e1590fa7.png)

Other examples working on [another page](https://beta.ionicframework.com/docs/api/badge): 
![image](https://user-images.githubusercontent.com/2999487/68031614-661b4a00-fc92-11e9-96da-66ed16778f3c.png)

**Browser:**
tested on Chrome and Firefox

**Comment by dotNetkow** [comment]
Thanks for the issue! This is only visible on the old beta version of the Ionic 4 docs, which are no longer active. Using your example, here's the actual [live "Structure" doc page](https://ionicframework.com/docs/layout/structure). Apologies for the confusion - I'll open an issue to implement a redirect from the beta to main docs.
