### ISSUE TITLE
refresher is not displaying correct using "ionic serve --lab"

### ISSUE THREAD

**Issue by iShinJini** [ionic-team/ionic-docs#1068]
![image](https://user-images.githubusercontent.com/37577105/68193908-fe952f80-ffee-11e9-9bb7-a46ce11c4555.png)

Sorry if this issue is duplicate.
I'm using ionic 4.
As shown above, the image, when I pull down to refresh, it displays black rectangular instead of refresher spinner icon. it happens only when using "ionic serve --lab".
It works fine without using "--lab".
Is there anything i miss out?

**Comment by dotNetkow** [comment]
Ionic Lab has been retired. Please use [ionic serve](https://ionicframework.com/docs/cli/commands/serve) along with the DevTools to view your Ionic app in different devices/viewports.
