### ISSUE TITLE
(ion-progress-bar): missing angular example

### ISSUE THREAD

**Issue by indraraj26** [ionic-team/ionic-docs#1079]
**Describe the bug**
No example for below component
https://ionicframework.com/docs/api/progress-bar

**To Reproduce**

**Expected behavior**

**Screenshots**

**Browser and OS (please complete the following information):**

**Additional context**

**Comment by brandyscarney** [comment]
Thanks for the issue! This was added by https://github.com/ionic-team/ionic/commit/da6263a0442db2a0e660976988cbb5b9a4b9cb7f and will be live on the site soon.
