### ISSUE TITLE
Ioinc 4 . Does this release support mobile web address hiding?

### ISSUE THREAD

**Issue by jbae1024** [ionic-team/ionic-docs#108]
https://github.com/ionic-team/ionic/issues/6168

Is there a way to solve this issue in this version?

Thank you

**Comment by bashoogzaad** [comment]
Also interested in this! I will be checking if I can find a solution myself. Will report back if worked.

**Comment by oliverrenner** [comment]
same here, this issue is quite important!

**Comment by aleksander351** [comment]
I would say, not hiding the navbar of the browser is a small UX sin. 🌮

**Comment by perrygovier** [comment]
This was marked as wont fix on the original framework issue

**Comment by efluxrepo** [comment]
Has it started to work in the latest version or still the issue still with framework?

**Comment by peterrobertz** [comment]
its still a very ugly issue

**Comment by Elwazeery** [comment]
Ionic 6
Still not fixed
