### ISSUE TITLE
Ion-range no option to customize snap or range-tick classs

### ISSUE THREAD

**Issue by ahaneef29** [ionic-team/ionic-docs#1098]
**URL**
The URL at which the content is missing or inaccurate
https://ionicframework.com/docs/api/range

**What is missing or inaccurate about the content on this page?**
I'm trying to achieve below design using ion-range, i cant able to modify range-tick class or snap.
is any other way to achieve with any other component. ?

![range](https://user-images.githubusercontent.com/10325179/69025857-1f438900-09e2-11ea-8d67-bddececab9dd.jpg)

**Comment by dotNetkow** [comment]
Outside the scope of the docs repo here... please submit design/implementation questions on the [Ionic Forum](https://forum.ionicframework.com/) or [Community Slack](http://ionicworldwide.herokuapp.com/).
