### ISSUE TITLE
Recombobulate the Nav

### ISSUE THREAD

**Issue by perrygovier** [ionic-team/ionic-docs#11]
- [x] use this format to add more sub-tasks

**Comment by bensperry** [comment]
Todo's:

- [ ] Speed up "Framework" and "Ecosystem" dropdown times
- [ ] Separate out "Native APIs" and "API Reference" items below the other ones
- [ ] Add arrow navigation
- [ ] Remove version dropdown from main docs. Only show in API pages
- [ ] Add very subtle animation to side menu items accordion

**Comment by bensperry** [comment]
*API Reference* mockup:

![image](https://user-images.githubusercontent.com/519526/38623725-00cf8cba-3d6c-11e8-96e1-9b2c5d5fed68.png)

**Comment by bensperry** [comment]
**Docs home** mockup:

![image](https://user-images.githubusercontent.com/519526/38623848-4b324fe0-3d6c-11e8-828d-8e05292c64ac.png)
