### ISSUE TITLE
docs api web for view components, fails device IOS/MD with Chrome

### ISSUE THREAD

**Issue by bitos2002** [ionic-team/ionic-docs#1108]
Hello,
I have issues with the following URL, for testing and preview the ionic 4 components
https://ionicframework.com/docs/api
Nevertheless, the old ionic web page works fine:
https://ionicframework.com/docs/v3/components/#buttons
De emulator device load the components, and just loaded, disapeer.
The problem are either IOS and MD device.
Any one have probles using this web?

OS: OSX 10.13.6
Chrome: Versión 78.0.3904.108 (Build oficial) (64 bits)

![image](https://user-images.githubusercontent.com/6966296/69664449-b1096100-1088-11ea-9fc8-e1b670e6f20b.png)
![image](https://user-images.githubusercontent.com/6966296/69667743-dbf6b380-108e-11ea-86bc-e3261f705b03.png)

**Comment by dotNetkow** [comment]
Reviewed and tested - should be OK now given time has passed and many iterations of the API pages have gone into effect.
