### ISSUE TITLE
Ionic 4 Beta - Fab demo problems

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-docs#111]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/api/fab

**Current behavior:**

Logging comments
Color squares
No indication in HTML of how color is set for the demo buttons
Nothing behind the javascript selector
Not closing a fab when another is open

![capture380](https://user-images.githubusercontent.com/140737/44295900-81ee2800-a267-11e8-9245-20740f698524.png)

**Expected behavior:**
Working and well explained

**Steps to reproduce:**
Just do it!

**Other information:**

**Comment by camwiegert** [comment]
The fab demo has been refined in the new docs. Thanks!
