### ISSUE TITLE
Feature Request - Submit an edit button similar to the Capacitor website so that we can easily find the file to edit and push a PR

### ISSUE THREAD

**Issue by antoinecfmws** [ionic-team/ionic-docs#1118]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
Currently to find the .md file that we are looking for from the ionicframwork.com/docs website, it's not trivial. For example, I am currently looking to edit https://ionicframework.com/docs/api/item/#detail-arrows , I am not familiar with the folder structure and even glancing over quickly at the intro md, I realize that the .md files are under src/pages. Looking at src/pages is not trivial either.

Can we please add a button similar to the Capacitor website, "Submit an edit" and it will take you right away to the .md file . Example: https://capacitor.ionicframework.com/docs/android/custom-code/

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by dotNetkow** [comment]
Thanks for submitting this. Currently, we do have "Contribute" buttons on the Framework Guide pages, but not the API components. A bit trickier because their data is pulled in from the ionic framework repo (but still doable).

**Comment by dotNetkow** [comment]
Closing... We do have edit buttons available elsewhere in the main Guide(s), and in this case it’s the Ionic Framework API page, which has to be edited outside the docs - on the "ionic" repo itself. See details on [Contributing.md](https://github.com/ionic-team/ionic-docs/blob/master/CONTRIBUTING.md).
