### ISSUE TITLE
Incorrect file import path on file transfer page

### ISSUE THREAD

**Issue by lucascrandle** [ionic-team/ionic-docs#1120]
**URL**
https://ionicframework.com/docs/native/file-transfer

**What is missing or inaccurate about the content on this page?**
The import for file is 
`import { File } from '@ionic-native/file';` 
but I think it should be 
`import { File } from '@ionic-native/file/ngx';`

The doc references this.file.dataDirectory which doesn't exist @ionic-native/file but does in @ionic-native/file/ngx

**Comment by dotNetkow** [comment]
Good catch, fixing in [this PR](https://github.com/ionic-team/ionic-native/pull/3454).
