### ISSUE TITLE
Incorrect code in InAppBrowser

### ISSUE THREAD

**Issue by chilupa** [ionic-team/ionic-docs#1134]
**URL**
The URL at which the content is missing or inaccurate
https://ionicframework.com/docs/native/in-app-browser#usage

**What is missing or inaccurate about the content on this page?**
Flower brace was missing.

The code below 
```js
   browser.insertCSS({ code: "body{color: red;" });
```
should be corrected to 
```js
   browser.insertCSS({ code: "body{color: red;}"});
```

**Comment by dotNetkow** [comment]
Great catch - fixing in an upcoming Ionic Native PR. Thank you!
