### ISSUE TITLE
ion-input docs missing title attribute [v4]

### ISSUE THREAD

**Issue by lightbeard** [ionic-team/ionic-docs#115]
**I'm submitting a ...**  (check one with "x")
[x] bug report

**URL:**
https://beta.ionicframework.com/docs/api/input

**Current behavior:**
The pattern section of ion-input states:

> Use the title attribute to describe the pattern to help the user.

**Expected behavior:**
However, there is no `title` attribute documented for ion-input.

**Comment by camwiegert** [comment]
This is referring to the [global HTML title attribute](https://developer.mozilla.org/en-US/docs/Web/HTML/Global_attributes/title).
