### ISSUE TITLE
How to scrollToBottom() with ionic for react

### ISSUE THREAD

**Issue by ve-amitsharma** [ionic-team/ionic-docs#1150]
I'm working on a Ionic-react project, in which I need to use scrollToBottom() for IonContent. when I'm trying to do 
getContent() {
        return document.querySelector('ion-content');
    }
    scrollToBottom = () => {
        this.getContent().scrollToBottom(500);
    }

It's showing me error, "Object is possibly 'null'. " 
How can I achieve this. Thanks in advance for any help.

**Comment by mlynch** [comment]
Hi, this is a support request, please post those the Ionic forum: http://forum.ionicframework.com/

To give you some things to check: you need to tell typescript that you're okay with the object being possibly null (by using !) or find a different way to express what you need with the type system
