### ISSUE TITLE
Incorrect import path on Mobile Accessibility plugin

### ISSUE THREAD

**Issue by bipoza** [ionic-team/ionic-docs#1152]
**URL**
[https://ionicframework.com/docs/native/mobile-accessibility](https://ionicframework.com/docs/native/mobile-accessibility)

**What is missing or inaccurate about the content on this page?**
The import for file is
`import { MobileAccessibility } from '@ionic-native/mobile-ccessibility/ngx';`
but I think it should be
`import { MobileAccessibility } from '@ionic-native/mobile-accessibility/ngx';
`

The error is caused by missing a letter. It is not a serious error, but could be arranged to improve the documentation.

Thanks.

**Comment by dotNetkow** [comment]
Thanks for reporting! Fixed in recent Ionic Native PR.
