### ISSUE TITLE
Missing documentation for Platform and Platform.backButton

### ISSUE THREAD

**Issue by rveerd** [ionic-team/ionic-docs#116]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**URL:**
https://beta.ionicframework.com/docs/api

**Current behavior:**
The page mentions `Platform` but this is not a link. Documentation for `Platform` does not exist. Backward incompatible changes esp. hardware back button are not documented.

**Expected behavior:**
A working link to the documentation for `Platform`. Documentation for `Platform`. Documentation of backward incompatible changes.

**Steps to reproduce:**
n/a

**Other information:**
Especially functionality for the hardware back button as this was changed from Ionic 3. Document `backButton` Observable. A minimal example of how to use it to go to the previous page in a typical Ionic app would be great.

Add the change from `registerBackButtonAction` to `backButton` in the migration guide.

**Comment by bryplano** [comment]
There does appear to be an inconsistency there. The "old" documentation does include a page about that: https://ionicframework.com/docs/api/platform/Platform/#platforms

We'll review this with the team.

**Comment by camwiegert** [comment]
The Platform docs are now located [here](https://ionicframework.com/docs/utilities/platform).

**Comment by Takkuz** [comment]
Yes, but it still miss any documentation about `.backButton` properties.
