### ISSUE TITLE
ion-item button missing button directive

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-docs#1189]
**Describe the bug**
I **can't find the file** to edit myself ... maybe you guys should think about putting a direct link at the bottom of each docs pages to be able to fork quickly and edit, I think you would have much more contributions ......

On ion-item's doc (https://ionicframework.com/docs/api/item), the example showing how to make a clickable item is missing the `button` directive, so the style is not applied (cursor, ripple effect).

**To Fix**
Currently :
```
<!-- Item as a Button -->
<ion-item (click)="buttonClick()">
  <ion-label>
    Button Item
  </ion-label>
</ion-item>
```

Should be :

```
<ion-item button (click)="buttonClick()">
  <ion-label>
    Button Item
  </ion-label>
</ion-item>
```

**Comment by brandyscarney** [comment]
Thanks for the issue! This was resolved by the following commit and will be available on the site soon: https://github.com/ionic-team/ionic/commit/6d6aba6d40d7bd72a0c16a3edb0538e632120678

We have some instructions on contributing to the API documentation here: https://github.com/ionic-team/ionic/blob/master/.github/CONTRIBUTING.md#modifying-documentation
