### ISSUE TITLE
Double await everywhere in the docs

### ISSUE THREAD

**Issue by Yohandah** [ionic-team/ionic-docs#1191]
**Describe the bug**
I **can't find the file** to edit myself ... maybe you guys should think about putting a direct link at the bottom of each docs pages to be able to fork quickly and edit, I think you would have much more contributions ......

On many components's doc (for example modal https://ionicframework.com/docs/api/modal) there is a double unnecessary await;

**To Fix**
Currently :
```
async presentModal() {
    const modal = await this.modalController.create({
      component: ModalPage
    });
    return await modal.present();
}
```

But double await is unnecessary :

```
async presentModal() {
    const modal = await this.modalController.create({
      component: ModalPage
    });
    return modal.present();
}
```

**Comment by rtpHarry** [comment]
Are you sure about this one? When I looked into it before I thought that it was required.

Just refreshed my knowledge with [this post](https://jakearchibald.com/2017/await-vs-return-vs-return-await/).

It does say outside of a try catch block `return await` is redundant, however if the sample code could end up in a try catch block then I suppose this is one less gotcha and it doesnt seem to harm it.

[Looking at the code](https://github.com/ionic-team/ionic/blob/master/core/src/components/modal/modal.tsx#L132) it seems that `present()` could actually throw an error so it probably should be wrapped up in a try catch.

**Comment by Yohandah** [comment]
@rtpHarry Well what put me on the lead is my IDE telling me (with tslint) that it's not necessary. Since the provided code is not in a try / catch I think the doc should give a clean code.

Maybe a note can be added next to the snippet to emphasize that tho .. idk

![double await](https://user-images.githubusercontent.com/15921402/73360335-fa517900-42a2-11ea-8c2e-63970fc7d477.png)

**Comment by kensodemann** [comment]
In the code above, your better option, IMO, is to remove the `return`:

```ts
async showEditModal(): Promise<void> {
  const modal: HTMLIonModalElement = await this._modalController.create({
    component: EditHomeModalComponent
  });

  await modal.present();
}
```

Then when `showEditModal()` has fulfilled its promise you can be sure the modal has been presented and it is obvious from the code that the presentation is being awaited.

**Comment by Yohandah** [comment]
Oh yeah you're right it was useless to return the promise since I was ignoring it anyway. Makes more sense this way. It just felt weird cause I'm new to Ionic. 

Thank you!
