### ISSUE TITLE
Markdown parser: Framework/Platform "tabs" at the top of the page if necessary

### ISSUE THREAD

**Issue by perrygovier** [ionic-team/ionic-docs#1206]
On pages that use `<angular-only>` and `<react-only>` components, or if they have sibling framework specific pages like `/docs/navigation/react` and `/docs/navigation/angular` we should automatically add an extra framework selection component that looks like the tabs interface used in the component api docs. 

It should be injected in to the top of the page, beneath the title header.

**Comment by perrygovier** [comment]
Aren't we rushing this decision a bit? 😜

**Comment by brandyscarney** [comment]
We don't have those components anymore 😆
