### ISSUE TITLE
Docs for `Input Component` needs to be updated

### ISSUE THREAD

**Issue by navicstein** [ionic-team/ionic-docs#1207]
**https://ionicframework.com/docs/api/input**
The URL at which the content is missing or inaccurate contains some outdated stuffs like `ionChange` became `onIonChange` etc.. this is misleading for some developers, and became a problem

**Comment by brandyscarney** [comment]
Thanks for the issue! `ionChange` is the correct event name for input. Are you using it in a Stencil app?

**Comment by amandaejohnston** [comment]
Due to the age of this issue and the lack of detail, I'm going to close this out, but please open a new issue if you are still having trouble. Thank you!
