### ISSUE TITLE
`ionic cap add ios` causes error

### ISSUE THREAD

**Issue by plocket** [ionic-team/ionic-docs#1210]
**URL**

https://ionicframework.com/docs/react/your-first-app/6-deploying-mobile

**What is missing or inaccurate about the content on this page?**

I'm not sure the instructions for adding Capacitor are complete. The intro says, "Since we added Capacitor to our project when it was first created..." I followed the tutorial. My project was created without a hitch. The code is running fine in my browser and builds just fine, but when I do `ionic cap add ios`, I get an error:
```
[error] cocoapods is not installed.
```

Is there some other thing that needs to be done to deal with cocoapods?

**Comment by plocket** [comment]
It doesn't happen with `ionic cap add android`.

**Comment by dotNetkow** [comment]
hey sorry about that! We'll update the guide soon. in the meantime, see here for [Capacitor dependencies](https://capacitor.ionicframework.com/docs/getting-started/dependencies/).

for iOS:
Additionally, you'll need to install CocoaPods (**sudo gem install cocoapods**), and install the Xcode Command Line tools (**either from Xcode, or running xcode-select --install**).

Once you have CocoaPods installed, update your local repo by running **pod repo update**. You should run this command periodically to ensure you have the latest versions of CocoaPods dependencies.

**Comment by plocket** [comment]
Don't have time to try this out right now, so I'm closing this. Thanks for the response and pointers.

**Comment by plocket** [comment]
Sorry, you made this an assignment. I shouldn't close stuff on your issues anyway. My bad.

**Comment by virgolee2209** [comment]
Hi there, 
I just have the same issue when add ios to my project.
I also install cocoapods 1.9.1 using terminal.
Here is the message when I add ios with verbose option:
```
onic:lib Terminal info: { ci: false, shell: '/bin/bash', tty: true, windows: false } +0ms
  ionic:lib CLI global options: { _: [ 'capacitor', 'add', 'ios' ], help: null, h: null, verbose: true, quiet: null, interactive: true, color: true, confirm: null, json: null, project: null, '--': [] } +4ms
  ionic:lib:project Project type from config: @ionic/react (react) +0ms
  ionic:lib:project Project details: { configPath: '/Users/hale/Documents/DevOpsProjects/EclipseOnlineIonic/ionic.config.json', errors: [], context: 'app', type: 'react' } +1ms
  ionic Context: { binPath: '/usr/local/lib/node_modules/@ionic/cli/bin/ionic', libPath: '/usr/local/lib/node_modules/@ionic/cli', execPath: '/Users/hale/Documents/DevOpsProjects/EclipseOnlineIonic', version: '6.9.2' } +0ms
> capacitor add ios
  ionic:lib:telemetry Sending telemetry for command: 'ionic capacitor add' [ 'ios', '--verbose', '--interactive', '--color' ] +0ms
[error] cocoapods is not installed. For information: https://guides.cocoapods.org/using/getting-started.html#installation
[ERROR] An error occurred while running subprocess capacitor.
        
        capacitor add ios exited with exit code 1.
        
        Re-running this command with the --verbose flag may provide more information.
  ionic:utils-process onBeforeExit handler: 'process.exit' received +0ms
  ionic:utils-process onBeforeExit handler: running 1 functions +0ms
  ionic:utils-process processExit: exiting (exit code: 1) +31ms
```

Any suggestion?

**Comment by virgolee2209** [comment]
never mind, I fixed it by running "brew install cocoapods". The gem command to install cocoapods says it installs successfully but it didnt. After running the brew command, everything is running as expected.

**Comment by naresh33** [comment]
fixed it by running "brew install cocoapods"

**Comment by jcesarmobile** [comment]
closing since the CocoaPods requirement is documented

**Comment by codemaster138** [comment]
> closing since the CocoaPods requirement is documented

About that: Yes, it's documented, but it's not mentioned at all in the the "developing for ios" page [here](https://ionicframework.com/docs/developing/ios#project-setup). Shouldn't it be mentioned there?
