### ISSUE TITLE
ion-backdrop CSS Custom Properties is Missing

### ISSUE THREAD

**Issue by albernaz** [ionic-team/ionic-docs#1212]
**URL**
The URL at which the content is missing or inaccurate
https://ionicframework.com/docs/api/backdrop

**What is missing or inaccurate about the content on this page?**
CSS Custom Properties
--ion-backdrop-color
--ion-backdrop-opacity

**Comment by brandyscarney** [comment]
Thanks for the issue! Global variables related to the theme (changing colors) of an application can be found in this section: https://ionicframework.com/docs/theming/themes#application-colors
