### ISSUE TITLE
FirebaseX - FirebaseXOriginal error

### ISSUE THREAD

**Issue by alexthunder3** [ionic-team/ionic-docs#1215]
**URL**
https://ionicframework.com/docs/native/firebase-x

**What is missing or inaccurate about the content on this page?**
In the Usage section it is stated to import FirebaseX from '@ionic-native/firebase-x'. This didn't work out in my project. There is a FirebaseX there, but it's a constant and it won't work when defined as a type in the constructor. A usable class is FirebaseXOriginal, which PHPStorm doesn't complain about, until I try to build, which ends up with an error. I poked a bit and I did find the proper FirebaseX class inside the ngx folder.
So the correct import would be
```
import {FirebaseX} from "@ionic-native/firebase-x/ngx";
```
This did build correctly.
Also, it is not mentioned that the same import has to be added to the .module.ts file, and FirebaseX specified in the @NgModule providers array.

FYI, i'm just starting with Angular/Typescript/Ionic. The more specific info would have helped me get started faster. I did figure it out because I've been looking at a tutorial earlier for the Ionic v3 version which mentioned the providers.

Thanks and best regards,
Alex.

**Comment by dotNetkow** [comment]
Code sample updated in recent Ionic Native PR.

The complete plugin usage info lives in the [Cordova plugin repo itself](https://github.com/dpa99c/cordova-plugin-firebasex#ionic-4).
