### ISSUE TITLE
Storage documentation missing

### ISSUE THREAD

**Issue by JoeDawson** [ionic-team/ionic-docs#122]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**URL:**
https://ionicframework.com/docs/storage/

**Current behavior:**
404'ing

**Expected behavior:**
Display the documentation for Storage

**Steps to reproduce:**
Visiting https://ionicframework.com/docs/storage/ returns a 404 (checked with a colleague too, same issue) - also not accessible from the sidebar of docs.

**Other information:**
n/a

**Comment by JoeDawson** [comment]
Referencing here for the time being: https://github.com/ionic-team/ionic-docs/blob/master/src/content/building/storage.md

**Comment by camwiegert** [comment]
@JoeDawson Thanks for opening this. This repo is for the [v4 docs](https://beta.ionicframework.com/docs/). You can find the [v4 storage documentation](https://beta.ionicframework.com/docs/building/storage) here. That is the live version of the markdown content you linked.

That said, the link you posted shouldn't be 404'ing either. I'll look into that. Thanks!

**Comment by JoeDawson** [comment]
Thanks for confirming @camwiegert - my bad for posting here but glad it has been seen by someone now.
