### ISSUE TITLE
Studio quickstart 404

### ISSUE THREAD

**Issue by malerba118** [ionic-team/ionic-docs#1222]
**Describe the bug**
Visiting studio quickstart page under docs returns a 404

**To Reproduce**
1. Go to https://ionicframework.com/docs/studio
2. Scroll down to quickstart card
3. Click on quickstart card

**Expected behavior**
Expect studio quickstart page to exist or quickstart card to be removed as well

**Screenshots**
![ionic-studio-quickstart-404](https://user-images.githubusercontent.com/5760059/74297010-2a6d3300-4d0b-11ea-8eb2-1c5490030458.gif)

**Browser and OS (please complete the following information):**
 - OS: macOS 10.13.2
 - Browser: Chrome
 - Version: 79.0.3945.130

**Additional context**
Might have to do with this commit
https://github.com/ionic-team/ionic-docs/commit/574739fc705293d738437e323dcb38942e0264a7#diff-7ebec450c981224fb5fd1551b4a101c5

**Comment by dotNetkow** [comment]
Quickstart guide (and now, the button) has been removed.
