### ISSUE TITLE
CSS attributes still mentioned the docs

### ISSUE THREAD

**Issue by shaneparsons** [ionic-team/ionic-docs#1230]
**URL**
https://ionicframework.com/docs/api/row#row-attributes

**What is missing or inaccurate about the content on this page?**
As you can see there is still a section dedicated to attributes, which no longer work.

This is likely widespread throughout the docs and not just limited to the linked page.

**Comment by brandyscarney** [comment]
Thanks for the issue! The main place where these are documented is in the layout section: https://ionicframework.com/docs/layout/css-utilities. These have all been updated to reflect the classes. I was unable to find places other than the grid API documentation where this was not yet updated, but I've created a pull request to fix that here: https://github.com/ionic-team/ionic/pull/20492

If you see any more places where it is not updated, please let us know. Thanks!
