### ISSUE TITLE
Ion-Anchor page shows no content

### ISSUE THREAD

**Issue by jdgarvey** [ionic-team/ionic-docs#1236]
**URL**
https://ionicframework.com/docs/api/anchor

**What is missing or inaccurate about the content on this page?**
The page shows a 404 message (see screenshot). It looks like `ion-anchor` is [deprecated](https://github.com/ionic-team/ionic/pull/18620), so I'm not sure if the link needs to be removed from navigation, or if the page needs some "deprecated" content. Happy to help with a PR either way.

![image](https://user-images.githubusercontent.com/1544557/74860323-b253ce00-5305-11ea-980d-94e8cd744fb4.png)

**Comment by dotNetkow** [comment]
yep! should be removed.  Fixed with #1275 . thanks!
