### ISSUE TITLE
bug: search shows v4 and v5 results, but does not specify which

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic-docs#1237]
**Describe the bug**
Searching for a component that exists in v4 and v5 results in 2 search results, and I have no idea which version of the framework it is for.

**To Reproduce**
1. Go Ionic docs.
2. Search for `ion-toggle`.
3. You should notice that two results pop up for `ion-toggle`, but there is no indication which version it is for.

In this instance, the first result goes to v4, and the second result goes to v5. This could potentially lead v5 users to see outdated docs.

**Expected behavior**
I would expect that the search would either a) specify the framework version, b) only show results from the latest framework version, or c) only show results from the framework version based upon where the user is in the docs (I.e. if I am in the v4 docs, only show v4 results, not v5 results).

I'm not sure which one is the _best_ solution but I am leaning towards option b.

**Screenshots**
![image](https://user-images.githubusercontent.com/2721089/74941060-69ad1b00-53c0-11ea-9671-0b329cbbd121.png)

**Comment by perrygovier** [comment]
ah, that was indexed quickly

thanks. I think we should just turn off v4 search results

**Comment by perrygovier** [comment]
I updated the search index in Swiftype. Should take about 10 mins to take effect.
