### ISSUE TITLE
Alert Controller content missing

### ISSUE THREAD

**Issue by appaulmac** [ionic-team/ionic-docs#1239]
**Describe the bug**
The page for the Alert Controller documentation is missing at [https://ionicframework.com/docs/api/alert-controller](url)

**Comment by perrygovier** [comment]
Controllers don't exist in the same way they did in v4. It's right for them to no longer be listed with other components, but they need to be documented _somewhere_

**Comment by amandaejohnston** [comment]
Controller usage is now being included in the component pages: https://ionicframework.com/docs/api/alert#controller Closing this out, but please feel free to open a new issue if you are still having trouble. Thank you!
