### ISSUE TITLE
Can't link to headers with same name on the same page

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#125]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**URL:**
https://beta.ionicframework.com/docs/theming/css-variables

**Current behavior:**
Add a subheading with the same name as an existing heading, see that you can only link to one.

For example, I have the following locally:

```
## Setting Values

### Global Variables

yada yada yada

## Ionic Variables

### Global Variables

yada yada yada
```

If I try to link to the second global variables by clicking the icon, it appends `#global-variables` to the url, which upon refresh will go to the first one. 

**Expected behavior:**
Clicking the link would direct link to the second heading.

**Comment by janbrasna** [comment]
The current markdown engine does handle unique anchor ids automatically, imho resolved since last years Docusaurus update.

**Comment by brandyscarney** [comment]
Closing as resolved
