### ISSUE TITLE
Dead links on the side menu to navigate the docs

### ISSUE THREAD

**Issue by manu2504** [ionic-team/ionic-docs#1256]
**Describe the bug**
When trying to access the Navigation items on the sidemenu, we get a "Not Found" message, except for https://ionicframework.com/docs/api/nav. The nav-pop, nav-push, and nav-set-root items are all dead links.

**To reproduce**
1. Go to https://ionicframework.com/docs/api/ 
2. On the sidemenu, in Navigation, click on 'ion-nav-pop'
3. See 404 error.

**Expected behavior**
The links should be updated to reflect the docs contents, or there should be enabled. The [docs ](https://ionicframework.com/docs/api/) describes that only nav and nav-link are valid items, but the sidemenu is not synced with it?

**Screenshots**
(No button to add an image in this code editor.)

**Browser and OS**
 - OS: Windows 10
 - Browser: Firefox
 - Version: 73

**Comment by dotNetkow** [comment]
thanks for pointing this out - fixed with #1275.
