### ISSUE TITLE
Ion Refresh documentation example has invalid icon

### ISSUE THREAD

**Issue by below43** [ionic-team/ionic-docs#1263]
**URL**
https://ionicframework.com/docs/api/refresher

**What is missing or inaccurate about the content on this page?**
Custom refresher content example has "arrow-dropdown" icon. This is now "chevron-down-circle-outline" in Ionicons 5.

Documentation says:
`
<ion-content>
  <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content
      pullingIcon="arrow-dropdown"...`

Documentation should say:
`
<ion-content>
  <ion-refresher slot="fixed" (ionRefresh)="doRefresh($event)">
    <ion-refresher-content
      pullingIcon="chevron-down-circle-outline"...`

**Comment by brandyscarney** [comment]
Thanks for the issue! This will be fixed soon.
