### ISSUE TITLE
import { Animation } should be from '@ionic/core' not from '@ionic/angular'

### ISSUE THREAD

**Issue by djabif** [ionic-team/ionic-docs#1277]
**URL**
The URL at which the content is missing or inaccurate
https://ionicframework.com/docs/utilities/animations#installation

**What is missing or inaccurate about the content on this page?**
I was trying to add an animation to my ionic 5 angular app following [this guide](https://ionicframework.com/docs/utilities/animations#installation).
It says to` import { Animation, AnimationController } from '@ionic/angular'; `but after building the app I get `error TS2305: Module '"../../../node_modules/@ionic/angular/ionic-angular"' has no exported member 'Animation'.`

It looks like `Animation` has to be imported from `'@ionic/core';` and not from` '@ionic/angular'`

**Comment by Sheikh45** [comment]
I'm doing from docs also facing same problem, importing it from @ionic/core doesn't help me out.

**Comment by jcesarmobile** [comment]
This was a bug in ionic/angular not re exporting the types, it was fixed shortly after the issue was created
https://github.com/ionic-team/ionic-framework/pull/20766
