### ISSUE TITLE
Broken links on ion-select page

### ISSUE THREAD

**Issue by shaneparsons** [ionic-team/ionic-docs#1278]
**URL**
https://ionicframework.com/docs/api/select

**What is missing or inaccurate about the content on this page?**
The following links on this page are broken:
- https://ionicframework.com/docs/api/alert-controller
- https://ionicframework.com/docs/api/action-sheet-controller
- https://ionicframework.com/docs/api/popover-controller

**Comment by shaneparsons** [comment]
It seems like `*-controller` links are broken on other pages as well.

**Comment by liamdebeasi** [comment]
Thanks! This has been resolved via https://github.com/ionic-team/ionic/pull/21167.
