### ISSUE TITLE
Docs are broken in Safari 10.0

### ISSUE THREAD

**Issue by ulesta** [ionic-team/ionic-docs#128]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/

**Current behavior:**
Broken in Safari version 10.0 on Mac OS; cannot navigate site as layout has issues + scroll does not work. When URL: https://beta.ionicframework.com/docs/ is entered, the page load with the regular layout and then breaks after page has fully loaded.

**Expected behavior:**
Layout should appear as normal and user should be able to scroll on pages

**Steps to reproduce:**
Visit https://beta.ionicframework.com/docs/ on Safari version 10.0 on Mac OS

**Other information:**
Mac Version: OS X El Capitan (10.11.6)

![image](https://user-images.githubusercontent.com/3767490/45648820-9bb5a180-ba97-11e8-8ccc-866b7ef3d0a7.png)

**Comment by mhartington** [comment]
Hi! Is this still an issue? At some point ,the docs were based on css-grid but are now flexbox which is supported in your version of safari.

**Comment by ulesta** [comment]
Hey Mike! Looks better, but still unusable. 

![beta-ionic](https://user-images.githubusercontent.com/3767490/49246874-e763c000-f3e3-11e8-95b4-8cf2964d8310.gif)

No rush, I can still use the doc site using Chrome 😉

**Comment by camwiegert** [comment]
Should be addressed by the new layout. Thanks!
