### ISSUE TITLE
How to pass REACT_APP_ prefixed Env Vars at build time?

### ISSUE THREAD

**Issue by vance** [ionic-team/ionic-docs#1283]
**URL**
A [standard way](
https://create-react-app.dev/docs/adding-custom-environment-variables/) to pass build-time configs to react is by using react environment variables prefixed with `REACT_APP_` however the docs do not illustrate how to properly pass them into the inner builder. 

There's a workaround by using the package `env-cmd` with
`npx env-cmd  -f .env.development ionic build` in the package scripts.

**Comment by dwieeb** [comment]
@vance It's a bug. See https://github.com/ionic-team/ionic-cli/issues/4333. A release is on its way.

**Comment by dwieeb** [comment]
@vance Please try with Ionic CLI 6.2.1. Thanks!

**Comment by vance** [comment]
Awesomes. thanks!
