### ISSUE TITLE
Update storage doc with capacitor

### ISSUE THREAD

**Issue by nicearma** [ionic-team/ionic-docs#1307]
**Describe the bug**
At this moment the storage doc are making reference to cordova plugin only, but is i try install it with ionic cli, i get one message about using capacitor instead, 

**To reproduce**
Create one capacitor projet with angular cli.
Fallow the instruction here: https://ionicframework.com/docs/building/storage

**Expected behavior**

Have the cordova and capacitor way, like https://ionicframework.com/docs/building/webview

**Comment by jcesarmobile** [comment]
the link doesn't show cordova nor capacitor information at the moment, so the issue is invalid

anyway, the only difference is how you install the plugins, in cordova you use `cordova plugin add plugin-id` and in capacitor just install it from npm with `npm install plugin-id`
