### ISSUE TITLE
Ionic V4 Beta - Native APIs docs unreachable (404 error)

### ISSUE THREAD

**Issue by LucaTerzaghi** [ionic-team/ionic-docs#131]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/native
https://beta.ionicframework.com/docs/native/app-preferences
Any other native API url

**Current behavior:**
Today all Ionic v4 Docs > Native APIs appear to be unreachable.
Please try navigating to:
https://beta.ionicframework.com/docs/native/app-preferences
or to any other Native API page.
All pages will throw a "Unable to fetch Unable to fetch native/app-preferences:" error.
Console shows a 404 for each https://beta.ionicframework.com/docs/content/native/ _APIname_ .md urls.

**Expected behavior:**
I would expect to be able to see the related API documentation.

**Steps to reproduce:**
1. Go to https://beta.ionicframework.com/docs/native
2. Select any native API from the left menu
3. The page content will display a "Unable to fetch native/ ... " error message

**Other information:**
None

**Comment by Tochukwuibe** [comment]
experiencing the same issue

**Comment by johannesnormannjensen** [comment]
I'm experiencing the same as well

**Comment by stephannagel** [comment]
Mike from the Ionic team confirmed existence of the error. He suggests we use the V3 documentation for the Native API's for now. No ETA on solving the issue.

**Comment by perrygovier** [comment]
This has been fixed now

**Comment by sangupta007** [comment]
@perrygovier I am experiencing this issue. Tested on chrome and edge and also on Android.

**Google Chrome (Win10)** 
Version 70.0.3538.110 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/16303528/50029776-e8b6fe80-0019-11e9-9b81-72ac3fbab52f.png)
