### ISSUE TITLE
Height of elements and layouts almost impossible to debug

### ISSUE THREAD

**Issue by Medtrack** [ionic-team/ionic-docs#133]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x ] feature request

The documentation lacks information on how to set up proportional heights and width for elements with a shadow dom. It is really hard to debug how to change height of elements, almost impossible.

**Steps to reproduce:**
Create an angular project
Add a header, a footer and the content with ion-header, ion-footer, ion-toolbar and ion-content.
Try to define proportional heights for header, footer and content.

This is not a question on ionicframework, but on the docs, the docs should explain things like width, font-size, height, etc...

**Comment by perrygovier** [comment]
With the move to shadow-dom, the only things that should be changed are covered by CSS variables.
