### ISSUE TITLE
Typo/error in the ion-item-option Docs

### ISSUE THREAD

**Issue by omar2205** [ionic-team/ionic-docs#1339]
**URL** https://ionicframework.com/docs/api/item-options

**What is missing or inaccurate about the content on this page?**
The option buttons for an **_ion-item-sliding_**. These buttons can be placed either on the start or end side.

Change "ion-item-sliding" to "ion-item-option"

**Comment by amandaejohnston** [comment]
The page has since been updated with clearer wording; closing this out. Thank you!
