### ISSUE TITLE
Grammar issue

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-docs#134]
On page: https://beta.ionicframework.com/docs/theming/advanced/

There is this sentence:
"After exploring many applications and themes, we found that most designs are never one background color."

I am not sure what is being said.

**Comment by Athuli7** [comment]
That the author and his colleagues looked at many applications and themes and came to the conclusion that most designs incorporate multiple backgrounds. It's not worded perfectly, but is it really a pressing issue? Also, its best to make these things a PR. Not just this one line, all mistakes you find.
