### ISSUE TITLE
Docs for Ionic React show non-React GIFs

### ISSUE THREAD

**Issue by jlkiri** [ionic-team/ionic-docs#1340]
**Describe the bug**
Docs for Ionic React show non-React GIFs.

**To reproduce**
1. Go to https://ionicframework.com/docs/react/your-first-app#photo-gallery-
2. Look at GIF

**Expected behavior**
GIF with Ionic React code is used.

**Browser and OS (please complete the following information)**
Irrelevant

**Comment by dotNetkow** [comment]
Thanks for reporting. The GIF is for illustrative purposes - more about showing how Live Reload works than the actual code used.
