### ISSUE TITLE
How to use ion-nav in React?

### ISSUE THREAD

**Issue by insoutt** [ionic-team/ionic-docs#1345]
**URL**
https://ionicframework.com/docs/api/nav

**What is missing or inaccurate about the content on this page?**
I didn't found how to implement `ion-nav` in **React** Documentation, how can I do?

**Comment by Kachilero** [comment]
+1

**Comment by wangcode** [comment]
what difference between ion-nav and pages?

**Comment by yunter** [comment]
> +1

+1

**Comment by phal0r** [comment]
There are several use cases, where one needs IonNav to provide navigation inside a modal or other subcomponents. Even the official docs mention this as common use case.

Currently we need to hack together some pieces with IonSlides to circumveint this, but this is far from being optimal. Having IonNav available in ionic react is definitely important from our side. Hope to see this integrated soon.

**Comment by MatthewSlater** [comment]
Hi guys, really struggling with implementation of ion nav with react too. Have any documentation changes been made on this that I'm missing?

Have looked at https://ionicframework.com/docs/api/nav

**Comment by moerabaya** [comment]
+1

**Comment by kevinclarkadstech** [comment]
This is a real dealbreaker for not being able to use React over Stencil.

**Comment by markatworksphere** [comment]
Here's a solution, but it uses some JS under the hood to make it work.
https://stackblitz.com/edit/react-ts-bcnnzq?file=pages%2FHome.tsx

+1 since it seems like there should be a much easier way.

**Comment by markatworksphere** [comment]
Also related issue: https://github.com/ionic-team/ionic-framework/issues/24002

**Comment by amandaejohnston** [comment]
Hi all; the live examples that Sean alluded to above are now live: https://ionicframework.com/docs/api/nav They include code snippets for all supported frameworks. I'm going to close this out. Thank you!

**Comment by babycourageous** [comment]
Thanks for the update @amandaejohnston and thanks to whoever got the docs updated for React!!
