### ISSUE TITLE
Incomplete ion-tabs documentation

### ISSUE THREAD

**Issue by cedricbellet** [ionic-team/ionic-docs#1360]
https://ionicframework.com/docs/api/tabs

From experimenting with basic examples and playing with the ionic-conference-app code, I found the following issues with ion-tabs:

1. an IonRouterOutlet is required
2. the IonRouterOutlet cannot contain a route to "/"
3. the views rendered by the tabs **must** be wrapped in an IonPage

Otherwise:

1. the IonTabs will throw an error
2. on tab change, nothing happens
3. on tab change, the rendered elements are not removed

**Comment by cedricbellet** [comment]
In addition, page transitions with ionTabs do not work properly if the IonApp is wrapped in React.StrictMode

**Comment by wingbui** [comment]
I used the example codes of ion-tab in Angular and get Error: 'ion-tab is not a known element'

**Comment by ceceliacreates** [comment]
I found a comment leading to the example [here,](https://github.com/ionic-team/ionic-react-conference-app/blob/master/src/pages/MainTabs.tsx#L17) which I was able to use in my app.

**Comment by amandaejohnston** [comment]
Thank you for the issue. The tabs docs were recently updated with a live demo that includes example usage code in all major supported frameworks, as well as more details about requirements for using the component. As such, I'm going to go ahead and close this out.
