### ISSUE TITLE
Difficult to find React documentation

### ISSUE THREAD

**Issue by gnesher** [ionic-team/ionic-docs#1366]
**URL**
N/A

**What is missing or inaccurate about the content on this page?**
Searching for React components using the site search functionality yields nothing.
For example, IonToolbar has no results but ion-toolbar does, developers who do not come from Ionic Angular will struggle to find information

**Comment by amandaejohnston** [comment]
Thank you for the issue. It looks like this has since been resolved with the latest version of the docs search functionality:

![toolbar search](https://i.gyazo.com/9b102f1960d22e02f363e1ade88f2599.png)

I'll go ahead and close this out.
