### ISSUE TITLE
React Photo Gallery tutorial app gives an error

### ISSUE THREAD

**Issue by wwhyte** [ionic-team/ionic-docs#1367]
**URL**
https://ionicframework.com/docs/react/your-first-app/4-loading-photos

**What is missing or inaccurate about the content on this page?**

The code provided for the call to set() to save photos is

```
set(PHOTO_STORAGE, JSON.stringify(newPhotos.map(p => {
  // Don't save the base64 representation of the photo data, 
  // since it's already saved on the Filesystem
  const photoCopy = { ...p };
  delete photoCopy.base64;
  return photoCopy;
})));
```

When I add this code, my app running in the browser changes to the following error:

> /Users/wwhyte/Dropbox/wwhyte-dev/ionic/photo-gallery/src/hooks/usePhotoGallery.ts
> TypeScript error in /Users/wwhyte/Dropbox/wwhyte-dev/ionic/photo-gallery/src/hooks/usePhotoGallery.ts(66,24):
> Property 'base64' does not exist on type '{ filepath: string; webviewPath?: string | undefined; base64?: string | undefined; } | { filepath: string; webviewPath: string | undefined; }'.
>   Property 'base64' does not exist on type '{ filepath: string; webviewPath: string | undefined; }'.  TS2339
> 
>     64 |       // since it's already saved on the Filesystem
>     65 |       const photoCopy = { ...p };
>   > 66 |       delete photoCopy.base64;
>        |                        ^
>     67 |       return photoCopy;
>     68 |     })));
>     69 |   };

This seems to be an error thrown by TypeScript and I assume it comes in part from the code defining Photo:

```
export interface Photo {
  filepath: string;
  webviewPath?: string;
  base64?: string;
}
```

Unfortunately I'm not familiar with TypeScript (or with React, in case this is a React issue) and don't know how to take this further.  It seems like the [name]?: [type] syntax means that the property with the given name may or may not be present, but it surprises me that this causes an error given that it *may* be present.

How can I address this and carry on with the tutorial?

I'm running on a Mac, using the most recent Ionic CLI, using Visual Studio Code as my editor, previewing in Chrome. I've checked other issues around the tutorial -- #1169 and #1179 seem similar but aren't close enough to this for me to be able to use them to resolve this one.

**Comment by dotNetkow** [comment]
hi there, I'll double check the guide tomorrow - but [check the code here](https://github.com/ionic-team/photo-gallery-capacitor-react/blob/master/src/hooks/usePhotoGallery.ts#L60). the return type needs to be Promise<Photo>.  hope that helps.

**Comment by wwhyte** [comment]
I had a look at the code and, apart from a check for whether it's a hybrid app, it seems to be the same as the code I'm running... I don't know how to set the return type in TypeScript code unfortunately, so I'll have to wait for you to check the guide. Thanks for your help.

**Comment by dotNetkow** [comment]
OK I figured it out. The issue actually stems from the 3rd page, https://ionicframework.com/docs/react/your-first-app/3-saving-photos, not the 4th. When we define the "savePicture" function there, it needs a return type of `Promise<Photo>`. I just added that - docs should reflect that soon.

Here's the complete example showing what I mean:

```
const savePicture = async (photo: CameraPhoto, fileName: string): Promise<Photo> => {
// snip
}
```
