### ISSUE TITLE
Clipboard API/component is missing in ionic 4 beta documents

### ISSUE THREAD

**Issue by agnaveen** [ionic-team/ionic-docs#137]
Hi team,

I could not find clipboard docs/details in ionic 4 beta, is this intentional, if so can you please help us with the alternative?

Else could you please share the doc link here??

Thanks,
Naveen.

**Comment by camwiegert** [comment]
@agnaveen I assume you are looking for [this](https://beta.ionicframework.com/docs/native/clipboard)!
