### ISSUE TITLE
ionic storage not included by default?

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#1381]
The docs at https://ionicframework.com/docs/angular/storage say:

> Next, install the package (comes by default for Ionic apps > Ionic V1):

I am working on a basic Ionic 5 app and it's not in my packages.json, so I just installed it.

Is it not included by default any more?

**Comment by dotNetkow** [comment]
Good catch, thanks for pointing out. No, not anymore. With Capacitor now, there's other options such as its Storage API. Must be an oversight.
