### ISSUE TITLE
docs: improve documentation surrounding using ionicons with React

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#1384]
**URL**
Either here: https://ionicons.com/

Or as a menu item in the main documentation 

**What is missing or inaccurate about the content on this page?**
We need to add more documentation surrounding using Ionicons with React to reduce confusion

https://github.com/ionic-team/ionic/issues/20353
https://github.com/ionic-team/ionic/issues/18847
& more

**Comment by amandaesmith3** [comment]
Resolved via https://github.com/ionic-team/ionic-docs/pull/2073 and https://github.com/ionic-team/ionic-docs/pull/2074.
