### ISSUE TITLE
how to use ion-nav-link without any framework?

### ISSUE THREAD

**Issue by anlexN** [ionic-team/ionic-docs#1385]
**URL**
The URL at which the content is missing or inaccurate
https://ionicframework.com/docs/api/nav-link
**What is missing or inaccurate about the content on this page?**
no pure javascript demo

**Comment by amandaejohnston** [comment]
A live demo of `ion-nav` and `ion-nav-link` has since been added to the docs here: https://ionicframework.com/docs/api/nav It features all supported frameworks, including pure JS. I'll go ahead and close this out. Thank you!
