### ISSUE TITLE
BREAKING.md is missing

### ISSUE THREAD

**Issue by lawchihon** [ionic-team/ionic-docs#1388]
**URL**
The URL at which the content is missing or inaccurate
https://ionicframework.com/docs/reference/BREAKING.md

**What is missing or inaccurate about the content on this page?**
Im following https://ionicframework.com/docs/reference/release-notes and try to update from 4.11 to 5.0. But the doc about breaking changes are gone.

**Comment by brandyscarney** [comment]
Thanks for the issue! The release notes are pulled from GitHub here: https://github.com/ionic-team/ionic/releases/tag/v5.0.0

The link to the breaking changes was a relative link there which is what was breaking it on our site. I've updated the link to point to the entire path so it will be fixed on our docs site at the next deployment. Here's the correct link: https://github.com/ionic-team/ionic/blob/master/BREAKING.md
