### ISSUE TITLE
Ion-Action-Sheet buttons properties not documented

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-docs#140]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X ] feature request

**URL:**
https://beta.ionicframework.com/docs/api/action-sheet/

**Current behavior:**
While the code sample shows some of the items in the buttons array, those additional properties are described in the documentation. For example, what are all the allowable roles?

**Expected behavior:**
Each property in the buttons array would be documented.

**Steps to reproduce:**
-

**Other information:**
-

**Comment by camwiegert** [comment]
Addressing all of these interface documentation issues in #229, thanks!
