### ISSUE TITLE
[v4] modal events not correct

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic-docs#141]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/api/modal#events

**Current behavior:**
The events listed for modals are not correct as on beta 12.

![image](https://user-images.githubusercontent.com/2852839/46583442-9bd20d00-ca57-11e8-8e82-8f2954f91485.png)

**Expected behavior:**
Update to show the correct events exposed on a modal. 

![image](https://user-images.githubusercontent.com/2852839/46583444-a2608480-ca57-11e8-909b-297c8f50c3e4.png)

**Comment by camwiegert** [comment]
@dylanvdmerwe That table is listing the event names, which are correct. Am I correct in assuming you're looking for the [method names](https://beta.ionicframework.com/docs/api/modal#methods)?
