### ISSUE TITLE
The documentation is outdated and incomplete

### ISSUE THREAD

**Issue by devportolio** [ionic-team/ionic-docs#1417]
This is the url.
https://ionicframework.com/docs/native/printer

When I try to implement what's on the page, it's showing an error. Printer option is outdated. Hopefully, you'll have time to update it.

Thanks,
Joseph

**Comment by dotNetkow** [comment]
Thanks for reporting. Updated this page as part of an Ionic Native PR. For any other usage details, see the [Cordova plugin page](https://github.com/katzer/cordova-plugin-printer).
