### ISSUE TITLE
wrong info on npm

### ISSUE THREAD

**Issue by peterennis** [ionic-team/ionic-docs#1421]
**URL**
The URL at which the content is missing or inaccurate

https://www.npmjs.com/package/@ionic/react
![Capture874](https://user-images.githubusercontent.com/140737/81989719-9f922200-95f2-11ea-891c-46a68c756b28.PNG)

**What is missing or inaccurate about the content on this page?**

Compare with https://ionicframework.com/getting-started/
![Capture875](https://user-images.githubusercontent.com/140737/81989298-dc114e00-95f1-11ea-82d5-a4c9d405c67b.PNG)

**Comment by jcesarmobile** [comment]
https://github.com/ionic-team/ionic-framework/pull/23610

**Comment by jcesarmobile** [comment]
The linked PR is merged, should be ok once next release is published
