### ISSUE TITLE
Wrong javascript code for ion-modal creation

### ISSUE THREAD

**Issue by JEricaM** [ionic-team/ionic-docs#1428]
**URL**
https://ionicframework.com/docs/api/modal

**What is missing or inaccurate about the content on this page?**
The code in usage section it's inaccurate because it's necessary to use controllers to create modals and not create them manually.

The correct code should be:

```
import { modalController } from '@ionic/core';
@Component({
  tag: 'app-home',
  styleUrl: 'app-home.css',
})
export class AppHome {
  async openModal() {
    const modal = await modalController.create({
      component: 'app-modal',
    });
    modal.onWillDismiss().then((x) => {
      console.log(x);
    });

    await modal.present();
  }
```

Reference: solved problem with ionic modal 
https://forum.ionicframework.com/t/on-select-is-hidden-behind-ion-modal/189703/7

**Comment by amandaejohnston** [comment]
Thank you for the issue. This has since been fixed with the new live demo of the controller modal: https://ionicframework.com/docs/api/modal#controller-modals I'm going to close this out.
