### ISSUE TITLE
[v4] Expand card component docs

### ISSUE THREAD

**Issue by dylanvdmerwe** [ionic-team/ionic-docs#143]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[X] feature request

**URL:**

**Current behavior:**
In the [card API page](https://beta.ionicframework.com/docs/api/card/) for v4, the card examples need to be expanded as they were in the v3 docs. 

Missing examples:

- [ ] [Card images](https://ionicframework.com/docs/components/#card-image)
- [ ] [Background images](https://ionicframework.com/docs/components/#card-background)
- [ ] [Advanced social cards](https://ionicframework.com/docs/components/#advanced-cards)
- [ ] [Advanced map cards](https://ionicframework.com/docs/components/#card-advanced-map)

**Expected behavior:**
Many more examples on how to use the card component are necessary.
v3: https://ionicframework.com/docs/components/#cards

**Comment by brandyscarney** [comment]
Thanks! I'm going to close this as we have mockups for cards that we'll be adding as part of this issue: https://github.com/ionic-team/ionic-docs/issues/477

**Comment by cambierjulien** [comment]
Hi,
This issue is closed, but where are the examples? Can I use the v3 code in the v4 or are they completely incompatible?
(I have no cod to test it yet, I'm currently exploring different frameworks to see which one would best fit our project.
Thanks!

**Comment by dylanvdmerwe** [comment]
The v3 code is quite similar, but there are in fact differences. Ionic team is working on creating more examples, however the [docs ](https://ionicframework.com/docs/api/card)are quite substantial, the code is solid and you can build and customise almost everything you will need.

**Comment by blahblehblah** [comment]
Would really appreciate having more examples on the cards page of v4 as in v3.
