### ISSUE TITLE
IonicSafeString not working

### ISSUE THREAD

**Issue by mneitzke** [ionic-team/ionic-docs#1443]
**URL**
https://ionicframework.com/docs/techniques/security

**What is missing or inaccurate about the content on this page?**
results in 

error TS2305: Module '"../../../../node_modules/@ionic/angular/ionic-angular"' has no exported member 'IonicSafeString'.
3 import {IonicSafeString} from '@ionic/angular';

**Comment by mhartington** [comment]
Tested this out. Seems to be working fine in my app.

Please open a new forum post for further discussion.

https://forum.ionicframework.com
