### ISSUE TITLE
feat: sheet-style modal on iOS

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic-docs#1449]
# Feature Request

**Ionic version:**

[x] **5.x**

**Describe the Feature Request**

We should create a way for users to present a sheet-style modal such as the one found in the iOS mail app:

![image](https://user-images.githubusercontent.com/2721089/76534153-7a94fd80-644f-11ea-86e1-9d8eafe6f12e.png)

**Comment by brandyscarney** [comment]
Transferred to ionic-docs

**Comment by brandyscarney** [comment]
I believe this is resolved now via the new playground documentation here: https://ionicframework.com/docs/api/modal#sheet-modal

Please reopen if not!
