### ISSUE TITLE
Layers Colors Select does not visually update when interacted with

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic-docs#1450]
**Describe the bug**
The select that opens in the "Layered Colors" section of the docs (https://ionicframework.com/docs/theming/colors) does not update when interacted with.

The select opens fine, and I can scroll. However, clicking any of the options does not cause them to appear to be checked.

Steps to reproduce:

1. Go to https://ionicframework.com/docs/theming/colors
2. Go to the "Layered Colors" section.
3. Click the dropdown to open a select.
4. Attempt to click on any of the options in the select. You should not be able to.

If you click "Success", then click "OK", the selected option does actually update. For some reason this is not being reflected as you click the option itself.

Tested in Version 83.0.4103.61 on macOS 10.15.5

**Comment by brandyscarney** [comment]
I'm not able to reproduce this, although the CSS for the dropdown itself looks like it got lost in the migration. Can you still reproduce?

**Comment by liamdebeasi** [comment]
I believe the select used to be an `ion-select` which may be why this bug was happening (some data not being collected when the selection is confirmed). I can't reproduce anymore.
