### ISSUE TITLE
Wrong Title for the Code

### ISSUE THREAD

**Issue by Sampath-Lokuge** [ionic-team/ionic-docs#1460]
Hi,

Native plugins have the wrong title. i.e. It says Using React? But it shows Angular code.

e.g. https://ionicframework.com/docs/native/secure-storage#usage

**Comment by dotNetkow** [comment]
Thanks! It's a bug, rendering the React header twice instead of once

**Comment by dotNetkow** [comment]
Let's see if the linked PR fixes it...

**Comment by Sampath-Lokuge** [comment]
Ok sure. We'll see that.
