### ISSUE TITLE
[v4] Missing css include in "Using Ionic from a CDN"

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-docs#147]
**I'm submitting a ...**  (check one with "x")
[X ] feature request

**URL:**
https://beta.ionicframework.com/docs/installation/cdn

**Current behavior:**
In the chapter "Using Ionic from a CDN", the import of the css I think is missing, right now only `<script src="https://unpkg.com/@ionic/core@latest/dist/ionic.js"></script>` is specified

**Expected behavior:**
As on npmjs (https://www.npmjs.com/package/@ionic/core) I would have expect both js and css 

    <link href="https://unpkg.com/@ionic/core@latest/css/ionic.bundle.css" rel="stylesheet">
    <script src="https://unpkg.com/@ionic/core@latest/dist/ionic.js"></script> 

**In the same time**

In the same time and in the same doc page, maybe `<script src="https://unpkg.com/ionicons@4.0.0/dist/ionicons.js"></script>` could be updated in order to point out to latest instead of 4.0.0 too

**Comment by SeanBannister** [comment]
Possible duplicate https://github.com/ionic-team/ionic-docs/issues/54
