### ISSUE TITLE
Building docs locally on windows breaks

### ISSUE THREAD

**Issue by frederikprijck** [ionic-team/ionic-docs#1473]
**Describe the bug**
Running npm start on my windows machine results in "Not Found" for all pages

**To reproduce**
1. npm i
2. npm start

**Expected behavior**
The docs run fine

**Screenshots**
![image](https://user-images.githubusercontent.com/2146903/84432507-2f94ad00-ac2d-11ea-9c29-235761d6880c.png)

Important note, I noticed an incorrectly file generation in the `www` folder.

So my project lives in `c:\Development\frederikprijck\ionic-docs`, and this is what's inside `www\docs\pages`:

![image](https://user-images.githubusercontent.com/2146903/84432597-54892000-ac2d-11ea-89fc-d90fd4267bb4.png)

Notice how this is almost identical to my file path? It just doesn't have the `C:\\Dev` part.

I think all relevant files are in there:

![image](https://user-images.githubusercontent.com/2146903/84432802-9e720600-ac2d-11ea-98d7-a98ddc5e96d2.png)

**Browser and OS (please complete the following information)**
 - OS: Windows 10 Pro
 - Browser: n/a

**Comment by frederikprijck** [comment]
Looks like a duplicate of https://github.com/ionic-team/ionic-docs/issues/761

**Comment by dotNetkow** [comment]
Hi @frederikprijck - we just merged a fix. I tested it on my windows 10 PC - would you mind pulling the latest from master and try

**Comment by frederikprijck** [comment]
Hey @dotNetkow , yep works fine. There is no weird folder being generated in the www folder and the docs work fine now!

Thanks for the fix!

**Comment by dotNetkow** [comment]
excellent, we appreciate the quick follow-up!
