### ISSUE TITLE
Error on loading the google analytics native docs

### ISSUE THREAD

**Issue by olrtg** [ionic-team/ionic-docs#1495]
**Describe the bug**

**To reproduce**
1. Go to 'https://ionicframework.com/docs/native/google-analytics'
2. See error "Something went wrong"

**Expected behavior**
To load the page correctly as on Firefox or Safari.

**Screenshots**
![Ionic Docs - Google Analytics](https://i.ibb.co/JkzwZMh/Screen-Shot-2020-06-22-at-11-45-10.png)

**Browser and OS (please complete the following information)**
 - OS: macOS Catalina
 - Browser: chrome
 - Version: 83.0.4103.106 (Official Build) (64-bit)

**Comment by dotNetkow** [comment]
Fixed
