### ISSUE TITLE
An IonRouterOutlet can be a descendant of another IonRouterOutlet

### ISSUE THREAD

**Issue by danaugrs** [ionic-team/ionic-docs#1521]
The documentation at https://ionicframework.com/docs/react/navigation states: "An IonRouterOutlet should also not be a descendant from another IonRouterOutlet."

But that's wrong - it's absolutely imperative to have `IonRouterOutlets` as descendants of `IonRouterOutlets`. Maybe the doc writer meant "immediate descendants" but that case is covered by the previous paragraph/sentence: "An IonRouterOutlet should only contain Routes or Redirects. Any other component should be rendered either as a result of a Route or outside of the IonRouterOutlet."

Therefore I propose we remove that sentence from the docs altogether.

Here's a screenshot of the docs in question:

![image](https://user-images.githubusercontent.com/5261448/86302740-01790c00-bbe0-11ea-8a43-f181df6f9280.png)

**Comment by mhartington** [comment]
Can you explain a bit more on what you mean? Im having a difficult time understanding what you are trying to explain.

**Comment by danaugrs** [comment]
Sure. Sometimes **it is** necessary to have an `IonRouterOutlet` as a descendant from another `IonRouterOutlet` when building a React application. For example when you have an `IonTabs` component in a page (which is not the root `App.tsx`). In that case you are going to have an `IonRouterOutlet` in the `App.tsx` component and, inside one of the routes, you are going to have the page with tabs which itself has an `IonRouterOutlet` inside it. This second IonRouterOutlet is a descendant of the first, and that's a perfectly valid use case.

**Comment by amandaejohnston** [comment]
Thank you for the issue. It looks like the sentence in question was removed since this issue was posted, so I'm going to ahead and close this out.
