### ISSUE TITLE
Animations/Gestures Documentation Shown as Part of the Security Documentation

### ISSUE THREAD

**Issue by QubeKay** [ionic-team/ionic-docs#1528]
**Describe the bug**
When you open the documentation on Animations and then navigate away to the documentation on Gestures first and that on Security second, you find parts of the Animation documentation interspersed in the documentation on Gestures and Security. Reloading the Gestures/Security page displays the correct content. 

**To reproduce**
1. Go to [Ionic Docs](https://ionicframework.com/docs)
2. On the left sidebar, scroll down to **Utilities**
3. Click on **Animations**
4. On the sidebar again, click on **Gestures** 
5. On the sidebar again, click on **Security** 
6. Scroll through the content 

**Expected behavior**
When navigating away from the Animations page to the Gestures page, I expect to see only the documentation on Gestures. 

**Screenshots**
<img width="1440" alt="Screenshot 2020-07-10 at 07 13 04" src="https://user-images.githubusercontent.com/43026159/87115779-e0b65380-c27c-11ea-964d-7615004df4f7.png">

**Browser and OS (please complete the following information)**
 - OS: macOS Catalina
 - Browser: Chrome || Safari
 - Version: 83.0.4103.116 || 13.1.1 (15609.2.9.1.2)

**Additional context**
Navigating straight to the Security documentation from Animations without first opening Gestures documentation does not cause this bug.

**Comment by tricki** [comment]
I can confirm this. Had it happen a couple times when researching gestures and animations and the mentioned steps reliably reproduce the bug.

I'm also seeing different console errors when navigating:
- p-8e2f739c.js:1 TypeError: Cannot read property 'insertBefore' of null
- p-8e2f739c.js:1 TypeError: Cannot read property 'nodeType' of null
- p-89ad75c1.entry.js:1 Uncaught TypeError: Cannot read property 'getBoundingClientRect' of null

**Comment by tricki** [comment]
The errors seem to be connected to slot relocation:

Navigating from Animations to Gestures:

**TypeError: Cannot read property 'insertBefore' of null**
Source: [`vdom-render.ts:299`](https://github.com/ionic-team/stencil/blob/e3f270037dc39c9026d28803ed35c2c1c4117c31/src/runtime/vdom/vdom-render.ts#L299)
- `oldStartVnode.$tag$ === 'docs-codepen'`
- `oldStartVnode.$attrs$ === {"user":"ionic","slug":"bGbMojP"}`
- `oldStartVnode.$elm$ !== null && document.body.contains(oldStartVnode) === false`

Navigating from Gestures to Security:

**TypeError: Cannot read property 'nodeType' of null** (thrown multiple times)
Source: [`update-element.ts:11`](https://github.com/ionic-team/stencil/blob/63595bc540db9aa85295f5a8dc8738beb2a37611/src/runtime/vdom/update-element.ts#L11)
- `newVnode.$elm$ === null`
- `JSON.stringify(newVnode) === {"$flags$":0,"$tag$":"code","$text$":null,"$elm$":null,"$children$":[{"$flags$":0,"$tag$":null,"$text$":"threshold","$elm$":null,"$children$":null,"$attrs$":null,"$key$":null,"$name$":null}],"$attrs$":null,"$key$":null,"$name$":null}`

**Comment by milantenk** [comment]
I faced this issue, now every route displays the same content. Some examples:

![image](https://user-images.githubusercontent.com/4102195/88030058-11c73b80-cb3b-11ea-9e11-82e8d8c3d147.png)
--------------------------
![image](https://user-images.githubusercontent.com/4102195/88030103-1b50a380-cb3b-11ea-95a3-9fb0a434d3f1.png)
--------------------------
![image](https://user-images.githubusercontent.com/4102195/88030125-24da0b80-cb3b-11ea-85b5-57ee80b1cd36.png)
--------------------------

On the console there is following error:
![image](https://user-images.githubusercontent.com/4102195/88030187-3a4f3580-cb3b-11ea-9726-3ad7675a9f0c.png)

Pressing `ctrl+f5` fixes it.

**Comment by jcesarmobile** [comment]
I can't reproduce anymore, so it's probably fixed

**Comment by amandaejohnston** [comment]
Thank you for the issue. I believe this is the same root problem as this: https://github.com/ionic-team/ionic-docs/issues/1370 I'm also no longer able to reproduce, so I believe this issue was fixed in the later versions of the docs. As such, I'm going to close this out.
