### ISSUE TITLE
Duplicate attribute in ion-loading creation doc

### ISSUE THREAD

**Issue by fred-mity** [ionic-team/ionic-docs#1540]
**URL**
https://ionicframework.com/docs/api/loading

**What is missing or inaccurate about the content on this page?**
Not much but in usage, under presentLoadingWithOptions method, cssClass defined twice in create option.

**Comment by liamdebeasi** [comment]
Thanks for the issue. I am going to close this as it appears to be resolved: https://ionicframework.com/docs/api/loading
