### ISSUE TITLE
Cant run first ionic angular capaciitor app

### ISSUE THREAD

**Issue by shruti318** [ionic-team/ionic-docs#1541]
**Describe the bug**
Angular related bug kindly include steps for node ,ionic ,anglar etc installation stepwise .
ng has unexpectedly closed (exit code 1)
the ionic cli will exit. please check any output above for errordetails
under project version ng some module missing 

**To reproduce**
1. ionic start 
2. angular -y
3. capacitor -y
4. serve -- error

**Expected behavior**
should run just defult black template tried

**Screenshots**

**Browser and OS (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**
using latest version of node ,ionic ,angular

**Comment by dotNetkow** [comment]
can you describe exactly what's happening/the error message? thanks

**Comment by shruti318** [comment]
Thanks @dotNetkow  there was some angular dependency error ,I installed them using npm i and error resolved .
Thanks
