### ISSUE TITLE
[v4] In addition to the existing Angular and JavaScript usage options, have a Stencil option

### ISSUE THREAD

**Issue by balupton** [ionic-team/ionic-docs#155]
**I'm submitting a ...**
[x] feature request

**URL:**
https://beta.ionicframework.com/docs/api/action-sheet/#usage

**Current behavior:**
Currently there is only Angular and JavaScript usage instructions.

**Expected behavior:**
 It would be nice if there were Stencil instructions for those building Stencil apps with Ionic.

**Comment by perrygovier** [comment]
Thanks! I dug around for a bit at what that'd look like and I think there's enough overlap between the JS content and any Stencil specific content that they don't necessitate a Stencil-specific option
