### ISSUE TITLE
REACT_APP_ENV is undefined in mobile build

### ISSUE THREAD

**Issue by jemantilla** [ionic-team/ionic-docs#1557]
**Describe the bug**
Browser works well but when i create a mobile build it is undefined.

My ionic info:
```
Ionic:

   Ionic CLI       : 6.10.1 (/Users/neil/.nvm/versions/node/v10.16.3/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/react 5.0.7

Capacitor:

   Capacitor CLI   : 2.2.1
   @capacitor/core : 2.3.0

Utility:

   cordova-res : not installed
   native-run  : not installed

System:

   NodeJS : v10.16.3 (/Users/neil/.nvm/versions/node/v10.16.3/bin/node)
   npm    : 6.13.6
   OS     : macOS Mojave
```

**To reproduce**
1. Build mobile using `cross-env REACT_APP_APPENV=development react-scripts build && ionic capacitor copy ios && ionic capacitor open ios`
2. Try to print env variable `REACT_APP_APPENV` using `console.log(process.env)`
3. Result: `{"NODE_ENV":"production","PUBLIC_URL":""}`

**Comment by jcesarmobile** [comment]
I don't see how this is a bug on ionic docs.
