### ISSUE TITLE
Angular Photo Gallery Guide: Argument of type 'void' is not assignable to parameter of type 'Photo'.

### ISSUE THREAD

**Issue by hugil** [ionic-team/ionic-docs#1565]
Pardon if this is a non-issue, I'm learning Angular using your framework and this issue appears after meticulously following the guide.

**URL**
https://ionicframework.com/docs/angular/your-first-app/3-saving-photos

**What is missing or inaccurate about the content on this page?**
```js
[ng]     ERROR in src/app/services/photo.service.ts:24:27 - error TS2345: Argument of type 'void' is not assignable to parameter of type 'Photo'.
[ng]
[ng]     24       this.photos.unshift(savedImageFile);
[ng]                                  ~~~~~~~~~~~~~~
```

**Comment by hugil** [comment]
Nevermind, missed to return the photo object in the savePicture function

```js
  private async savePicture(cameraPhoto: CameraPhoto) {
    const base64Data = await this.readAsBase64(cameraPhoto);

    const fileName = new Date().getTime() + '.jpeg';
    const savedFile = await Filesystem.writeFile({
      path: fileName,
      data: base64Data,
      directory: FilesystemDirectory.Data
    });

      // Use webPath to display the new image instead of base64 since it's
  // already loaded into memory
  return {
    filepath: fileName,
    webviewPath: cameraPhoto.webPath
  };
  }
```

**Comment by AlejoBohorquez** [comment]
private async savePicture(cameraPhoto: Photo) { 
     // Convert photo to base64 format, required by Filesystem API to save
    const base64Data = await this.readAsBase64(cameraPhoto);

    // Write the file to the data directory
    const fileName = new Date().getTime() + '.jpeg';
    const savedFile = await Filesystem.writeFile({
      path: fileName,
      data: base64Data,
      directory: Directory.Data
    });
    return await this.getPhotoFile(cameraPhoto,fileName);
  
  }

https://www.youtube.com/watch?v=VaLaJgus9p8

  private async getPhotoFile(cameraPhoto: Photo, fileName: string): Promise<Fotos>{
    return{
      filePath: fileName,
      webviewPath: cameraPhoto.webPath
    }

  }
