### ISSUE TITLE
infinite scroll: react and vue examples

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-docs#1583]
**Is your feature request related to a problem? Please describe.**
In the [infinite scroll](https://ionicframework.com/docs/api/infinite-scroll) documentation page there is no React and Vue example of usage.

**Describe the solution you'd like**
Would be cool to have examples for such frameworks too.

**Side note**
I opened this issue following two comments on a blog post I wrote on [dev](https://dev.to/daviddalbusco/infinite-scroll-with-ionic-react-3a3i).

**Comment by jeffcjohnson** [comment]
Not only are there no examples of use, it says:

> The Infinite Scroll component is not supported in React.

Also:

> The Virtual Scroll component is not supported in React.

**Comment by amandaejohnston** [comment]
Thank you for the issue. Usage examples for all supported frameworks have since been added: https://ionicframework.com/docs/api/infinite-scroll Closing this out.
