### ISSUE TITLE
Dark mode / theme for the docs.

### ISSUE THREAD

**Issue by infacto** [ionic-team/ionic-docs#1615]
The [Ionic docs](https://ionicframework.com/docs) are currently only in light theme. I like this theme. But my eyes hurt. The Ionic apps itself have a dark mode, which is awesome. But we should also implement a dark mode for the docs site.
I don't know what this website was created with. Are there theme variables? I hope so. Otherwise it is a bit more complex. If this site is also made with Ionic we could follow [this instructions](https://ionicframework.com/docs/theming/dark-mode).
We should implement a pretty nice dark mode. No alternatives like "invert" colors. And handle special components (like ads) of the website with hard coded colors. And the code blocks, app preview device frame. Etc. Maybe not trivial. 🤔

**Comment by saostad** [comment]
This is my request too, I am reading Ionic docs a lot recently but with the light background, it's hard. it's even not compatible with the dark reader browser extension.

**Comment by lexxyungcarter** [comment]
We are almost approaching 1 full year with no dark mode for the docs.

**Comment by jcesarmobile** [comment]
The docs have dark mode now by clicking the moon icon
