### ISSUE TITLE
docs(tabs): update usage section to latest

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#163]
The usage section for tabs is outdated / not up to date with beta 14: https://github.com/ionic-team/ionic/tree/master/core/src/components/tabs/usage

Need to review the readme too and probably the component docs

**Comment by peterpeterparker** [comment]
also the doc https://beta.ionicframework.com/docs/api/tab-bar display `<ion-tab-bar slot="bottom"/>` where actually it should be `<ion-tab-bar placement="bottom"/>` (not a slot, cf.: https://github.com/ionic-team/ionic/blob/018fb9876f10eeae37e45fd1e2b9a6315db69067/core/src/components/tab-bar/tab-bar.tsx)

**Comment by brandyscarney** [comment]
@peterpeterparker Placement is removed in master: https://github.com/ionic-team/ionic/blob/master/core/src/components/tab-bar/tab-bar.tsx

It should be slot. 🙂

**Comment by peterpeterparker** [comment]
@brandyscarney funny I just noticed it too 5 minutes ago 😆 turns out one of my many Ionic projects was not yet actualized. Sorry for my wrong comment, you are right of course
