### ISSUE TITLE
Slides references Swiper docs 6.x instead of 5.x

### ISSUE THREAD

**Issue by mbunge** [ionic-team/ionic-docs#1633]
**URL**
https://ionicframework.com/docs/api/slides

**What is missing or inaccurate about the content on this page?**
Docs references swiper 6.x instead of 5.x docs. Please replace http://idangero.us/swiper/api/ with https://github.com/nolimits4web/swiper/blob/Swiper5/API.md as long as ionic slides uses Swiper 5.4.1.

**Comment by amandaejohnston** [comment]
Thank you for the issue. The `ion-slides` component has since been deprecated and is set to be removed in an upcoming major release of Ionic, so developers should use the latest version of Swiper in its stead. I'm going to go ahead and close this out.
