### ISSUE TITLE
Ionic API - Index missing

### ISSUE THREAD

**Issue by bkarv** [ionic-team/ionic-docs#165]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/api

**Current behavior:**
The api index for api documentation is missing, now only states overview. 

**Expected behavior:**
Should have index of the API documentation. Although you can get access via components there is a bucket load APIs that are not in the components section missing. 

**Steps to reproduce:**
See photo:
<img width="222" alt="screen shot 2018-11-03 at 11 50 32 am" src="https://user-images.githubusercontent.com/10624315/47946371-085d0080-df5f-11e8-98d9-1405e65c269e.png">

**Comment by kplhub** [comment]
kpl [11:34 AM]
To bring back the api index list I created a pull request to update docs-api-map.ts: https://github.com/ionic-team/ionic-docs/pull/166

**Comment by badpenguin** [comment]
is there any workaround to display the doc? is it possibile to install and browse it locally?

**Comment by xiao1014** [comment]
> there

not work for me....

**Comment by jeugregg** [comment]
I copy paste the name of folder found here : 
https://github.com/ionic-team/ionic/tree/master/core/src/components

I add it at the end for  "https://beta.ionicframework.com/docs/api/"

For example for **button** :  https://github.com/ionic-team/ionic/tree/master/core/src/components/button

Doc is here : https://beta.ionicframework.com/docs/api/button

**Comment by perrygovier** [comment]
Fixed in 
https://github.com/ionic-team/ionic-docs/commit/9ba623dbeb9b1623105593e095b4d20d6f4e2765
