### ISSUE TITLE
[New @ionic/vue Beta] IonicModule

### ISSUE THREAD

**Issue by DieOver** [ionic-team/ionic-docs#1652]
**URL**
URL: Dont have.

**What is missing or inaccurate about the content on this page?**
I miss the IonicModule for "new @ionic/vue beta" on we can do things like that:
IonicModule.forRoot({
    mode: 'ios',
}),

And so much more.. please, make this possible.. thx!

**Comment by dotNetkow** [comment]
Hi there - in Ionic Vue, the equivalent would be:

```
window.Ionic = {
  config: {
    mode: 'ios'
  }
}
```

**Comment by liamdebeasi** [comment]
Hey there, 

We also have a complete guide on using the config in Ionic Vue: https://ionicframework.com/docs/vue/config. In addition to what @dotNetkow provided, you can also do:

```javascript
createApp(App)
  .use(IonicVue, {
    rippleEffect: false,
    mode: 'md'
  })
```
