### ISSUE TITLE
Color creator doesn't allow numeric characters in custom property name

### ISSUE THREAD

**Issue by onderceylan** [ionic-team/ionic-docs#1666]
First of all, thanks for this very useful color generator, it definitely saves time!

**Describe the bug**
I'd like to use numeric characters for my custom colors but the [color creator](https://ionicframework.com/docs/theming/colors#new-color-creator) doesn't allow them. As stated in the specs, [dashed idents](https://drafts.csswg.org/css-values-4/#typedef-dashed-ident) should allow alphanumeric characters so, whitelisting numeric characters would make the color generator more aligned with the standard.

**To reproduce**
1. Go to 'https://ionicframework.com/docs/theming/colors#new-color-creator'
2. Click on 'Color name input' where 'New' value is written by default
3. Replace `New` with `var-1`
4. See error and variable name that stripped out number `1`

**Expected behavior**
`var-1` should be a valid input for the CSS custom variable name, and color generator should be able to generate CSS code with alphanumerical custom property name.

**Screenshots**
![image](https://user-images.githubusercontent.com/2641384/93866559-1db0b480-fcc8-11ea-96a8-75bc1cfc6ad1.png)

**Browser and OS (please complete the following information)**
 - OS: [Windows]
 - Browser: [chrome]
 - Version: [85]

**Comment by brandyscarney** [comment]
Thanks for the issue! This seems to be working now for me, can you let me know if you're still running into it?

![Screen Shot 2022-10-11 at 2 51 44 PM](https://user-images.githubusercontent.com/6577830/195175133-b302c956-e61a-48e0-8d12-79be8b06ea9d.png)
