### ISSUE TITLE
Documentation Examples are Broken

### ISSUE THREAD

**Issue by balupton** [ionic-team/ionic-docs#168]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**
All the ionic v4 examples are boken for me on all browsers, for days. For example:

https://beta.ionicframework.com/docs/api/action-sheet/

**Current behavior:**
<img width="1444" alt="screen shot 2018-11-06 at 12 55 41 pm" src="https://user-images.githubusercontent.com/61148/48095221-43657980-e268-11e8-829a-ca63c91090d2.png">
<img width="1521" alt="screen shot 2018-11-06 at 12 54 56 pm" src="https://user-images.githubusercontent.com/61148/48095222-43657980-e268-11e8-823d-9c2abfe3adb9.png">

**Expected behavior:**
For it to work

**Steps to reproduce:**
Navigate to any of the examples on Safari Version 12.0.1 (14606.2.104.1.1), Chrome Version 70.0.3538.77 (Official Build) (64-bit), Firefox 63.0.1 (64-bit)

**Other information:**
https://ionic-worldwide.slack.com/archives/C08DV9NTY/p1541469290348700

**Comment by camwiegert** [comment]
@balupton Thanks for opening this! This has been addressed [here](https://github.com/ionic-team/ionic-docs/commit/35e0ad2d07059a668d27281cd9fb221e66f2f604).

**Comment by balupton** [comment]
Is it possible to add tests to make sure the docs are working before (and after) they are deployed so broken docs can be caught quicker, as broken docs makes adoption of the framework quite difficult
