### ISSUE TITLE
Build your first app: saving/reloading absolute photo URI breaks on iOS

### ISSUE THREAD

**Issue by DjulLau** [ionic-team/ionic-docs#1685]
**URL**
https://ionicframework.com/docs/angular/your-first-app/3-saving-photos

**What is missing or inaccurate about the content on this page?**
Saving absolute is wrong as it changes on each load in dev mode on iOS (https://github.com/ionic-team/capacitor/issues/1375#issuecomment-478018260)
Instead the filename should be stored and the URI should be rebuilt on load

**Comment by dotNetkow** [comment]
I just retested the app on iOS 14 with a development build and it appears to work correctly.

Can you tell me what you tested on? thanks.

**Comment by DjulLau** [comment]
Hi. I've tested on iOS 12.2. The GUID number after **/Application/** changes every launch on my setup.

**Comment by jcesarmobile** [comment]
closing as current code uses the file name
