### ISSUE TITLE
React usage for Geolocation plugin

### ISSUE THREAD

**Issue by chilupa** [ionic-team/ionic-docs#1691]
**URL**
https://ionicframework.com/docs/native/geolocation#usage

**What is missing or inaccurate about the content on this page?**
There isn't `React` related code specific to the `Geolocation` plugin mentioned in the docs. Thought it would help someone who are in search of it like me instead of redirecting them to another page.
I've implemented the below in my Ionic - React app.
```
import { Geolocation } from '@ionic-native/geolocation';

...

Geolocation.getCurrentPosition().then((resp) => {
  // resp.coords.latitude
  // resp.coords.longitude
}).catch((error) => {
  console.log('Error getting location', error);
});

let watch = Geolocation.watchPosition();
watch.subscribe((data) => {
  // data.coords.latitude
  // data.coords.longitude
  // data can be a set of coordinates or an error
});
```

**Comment by jcesarmobile** [comment]
that page no longer exists and redirects to capacitor geolocation plugin usage, which is framework agnostic
