### ISSUE TITLE
Update native community plugins link

### ISSUE THREAD

**Issue by chilupa** [ionic-team/ionic-docs#1692]
**URL**
https://github.com/ionic-team/ionic-docs/blob/master/CONTRIBUTING.md#updating-ionic-native-community-plugins

**What is missing or inaccurate about the content on this page?**
Looks like the link for the `community plugins` is broken there. Should be updated to https://ionicframework.com/docs/native/community

**Comment by dotNetkow** [comment]
good catch. fixed! thanks.
