### ISSUE TITLE
Quite a bunch things wrong here..

### ISSUE THREAD

**Issue by lordgreg** [ionic-team/ionic-docs#17]
Can you please update the readme.md in a way so that I can build api-docs without any issues. There's no `api-scripts-build` command, So, what's the procedure to really have all docs including API running with `npm run start`? 

Using windows 10.
```
$ node --version
v9.6.1

$ npm --version
6.0.1
```

Currently, this is the issue after doing `npm run api-docs` and `npm run start`:
![image](https://user-images.githubusercontent.com/480546/40278464-a7699938-5c31-11e8-8c9d-161e4b9342bb.png)

**Comment by perrygovier** [comment]
Closing for the same reasons as #18
