### ISSUE TITLE
Beta documentation redirecting to external site

### ISSUE THREAD

**Issue by volkanx** [ionic-team/ionic-docs#170]
**I'm submitting a ...**  (check one with "x")
[X] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/

**Current behavior:**
I'm trying to run the doc site locally to have offline access to documentation for Ionic 4 Beta. But the beta link in the localhost takes me to the actual site (https://beta.ionicframework.com/)

**Expected behavior:**
The URLs should be relative and beta documentation should work under localhost

**Steps to reproduce:**
Run the site locally and click on "Ionic 4 is coming" link on top left

**Other information:**

**Comment by mhartington** [comment]
Which link are you talking about? I will note that the new docs will have a service worker enabled once we hit final, so docs will be available offline.
