### ISSUE TITLE
Times New Roman is used until the fonts are loaded.

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-docs#1710]
**Describe the bug**
Times New Roman is used until the fonts are loaded. This does not look very good.

**To reproduce**
1. Go to '[ionicframework.com/docs](https://ionicframework.com/docs)'
2. See error

**Expected behavior**
Fonts should be loaded or times new roman should not be visible.

**Screenshots**
![Unbenannt](https://user-images.githubusercontent.com/36629890/95651625-00fbe580-0aec-11eb-9bb4-889480e559d6.PNG)

**Browser and OS (please complete the following information)**
 - OS: Windows 10 / MacOS Big Sur
 - Browser: Chrome / Safari / Safari Technology Preview
 - Version: latest

**Comment by amandaejohnston** [comment]
Thank you for the issue. It looks like the problem has been resolved in the time since this was posted, so I'm going to close this out, but please open a new issue if you're still seeing this with the latest version of the docs.
