### ISSUE TITLE
segmentChanged event  load data bug  more times

### ISSUE THREAD

**Issue by xlanghejianfeng** [ionic-team/ionic-docs#1711]
**Describe the bug**

**To reproduce**

**Expected behavior**

**Screenshots**

**Browser and OS (please complete the following information)**
 - Browser: [e.g. chrome, safari]
 - Version: [e.g. 22]

**Additional context**

**Comment by amandaejohnston** [comment]
Closing this out due to a lack of description, but if you're still having trouble, please open a new issue and ensure the template is filled out. Thank you.
