### ISSUE TITLE
Typo: Vue Example ion-menu mentController

### ISSUE THREAD

**Issue by scottix** [ionic-team/ionic-docs#1720]
**URL**

https://ionicframework.com/docs/api/menu

**What is missing or inaccurate about the content on this page?**

There is a typo for the Vue Example

it imports "mentController" it should be "menuController"

**Comment by bygiro** [comment]
12 days and this issue is still open?!

**Comment by liamdebeasi** [comment]
This was fixed back in October 2020, we just forgot to close the issue: https://github.com/ionic-team/ionic-framework/pull/22392
