### ISSUE TITLE
ion-menu doc enhancement ionic vue

### ISSUE THREAD

**Issue by dlodeprojuicer** [ionic-team/ionic-docs#1728]
**URL**
https://ionicframework.com/docs/api/menu

**What is missing or inaccurate about the content on this page?**
It will be helpful to add [this](https://stackoverflow.com/a/58953688/616221) to the documentation. It's easy to miss if the IDs structure is not setup the same as the example.

Also, the typo mentioned [here](https://github.com/ionic-team/ionic-docs/issues/1720)

**Comment by liamdebeasi** [comment]
This was fixed in https://github.com/ionic-team/ionic-framework/pull/22624.
