### ISSUE TITLE
404 Link on /docs/deployment/desktop-app

### ISSUE THREAD

**Issue by michaelalhilly** [ionic-team/ionic-docs#1743]
**URL**
The URL at which the content is missing or inaccurate

https://ionicframework.com/docs/deployment/desktop-app

**What is missing or inaccurate about the content on this page?**

The "Electron guide" link at the top of the page directs to 404 on Electron's site.

https://electronjs.org/docs/tutorial/first-app

**Comment by dotNetkow** [comment]
It redirects to https://www.electronjs.org/docs/tutorial/quick-start for me. Can you recheck?

**Comment by michaelalhilly** [comment]
Yes I see the same. Thanks.
