### ISSUE TITLE
v4 Doc: tabs "preview" has no effect

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-docs#176]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/api/tabs

**Current behavior:**
When I click on "preview" in the examples of the router integration of the tabs doc it has no effect

**Expected behavior:**
I guess I should be able to see a preview or the buttons "preview" should just not exist

**Comment by brandyscarney** [comment]
I'm going to close this since the site has been refactored and this no longer exists, but thank you for the issue!

**Comment by peterpeterparker** [comment]
Sure thx 👍
