### ISSUE TITLE
Please update current docs with cdk-virtual-scroll info

### ISSUE THREAD

**Issue by barrcodes** [ionic-team/ionic-docs#1760]
**URL**
https://ionicframework.com/docs/api/virtual-scroll

**What is missing or inaccurate about the content on this page?**
According to [this md file](https://github.com/ionic-team/ionic-docs/blob/ef471ef4acf5fbd9ac160161ef4f8b2b231a1f4e/src/pages/angular/virtual-scroll.md), angular users should be using the cdk-virtual-scroll. However, when I navigate to `ion-virtual-scroll` with Angular selected as my framework, I am not warned in any way that I am using the wrong component.

**Comment by dotNetkow** [comment]
Thanks for pointing out - this is a WIP as part of Ionic Framework v6 planning.

**Comment by amandaejohnston** [comment]
Thank you for the issue. The docs have since been updated with info on how to use the `@angular/cdk` package within an Ionic app: https://ionicframework.com/docs/angular/virtual-scroll I'm going to close this out.
