### ISSUE TITLE
Data Storage documentation is incorrect.

### ISSUE THREAD

**Issue by enmanuel97** [ionic-team/ionic-docs#1771]
The are a mistake in data storage usage section. You have to change the installation command.

`ionic cordova plugin add cordova-sqlite-storage` this doesn't work anymore, the correct way is `npm i cordova-sqlite-storage`

**Comment by amandaejohnston** [comment]
Thank you for the issue. The installation instructions have since been updated to include both commands: https://github.com/ionic-team/ionic-storage#installation-1 I'm going to close this out.
