### ISSUE TITLE
bug: ion-slides loop removes bindings such as onClick and routerLink when looping

### ISSUE THREAD

**Issue by kas84** [ionic-team/ionic-docs#1777]
# Bug Report

**Ionic version:**

[ ] **4.x**
[x] **5.x**

**Current behavior:**

- Click event does not work properly inside a ionic-slide (you have to click several times to make it work.
- Reactive data is not reactive on duplicate slides

**Expected behavior:**

- Click event should  work as expected
**Steps to reproduce:**

Here I provide a sample application that demonstrates this. On the first tab, I have a slider that has 7 buttons that could be clicked.

The one that is active has an 'active' class that makes the letter bold. By clicking any button, you should make the clicked button active.

**Related code:**

https://github.com/kas84/ion-slides-vue-sample

**Other information:**

**Ionic info:**

```
Ionic:

   Ionic CLI       : 6.12.0 (/Users/pablo/.nvm/versions/node/v14.7.0/lib/node_modules/@ionic/cli)
   Ionic Framework : @ionic/vue 5.4.1

Capacitor:

   Capacitor CLI   : 2.4.2
   @capacitor/core : 2.4.2

Utility:

   cordova-res : 0.15.1
   native-run  : not installed

System:

   NodeJS : v14.7.0 (/Users/pablo/.nvm/versions/node/v14.7.0/bin/node)
   npm    : 6.14.8
   OS     : macOS Catalina
```

**Comment by amandaejohnston** [comment]
Thank you for the issue. In the time since this was posted, `ion-slides` has since been deprecated and is set to be removed in a future major release of Ionic. Migration instructions can be found in the component docs page: https://ionicframework.com/docs/api/slides I'm going to close this out.
