### ISSUE TITLE
IonRouterOutlet is compulsory for IonTabs to work

### ISSUE THREAD

**Issue by skshahidur** [ionic-team/ionic-docs#1778]
https://github.com/ionic-team/ionic-docs/blob/1b5809b33bb4985d09bd35a96ad018867144cad3/src/demos/api/tabs/index.html#L20

The `IonTabs` doesn't work without providing a `IonRouterOutlet`. However, the code sample doesn't mention this. Please add a `IonRouterOutlet` snippet on the code.

e.g. 

```
<IonRouterOutlet>
          <Route path="/tabs/:tab(home)" component={Home} exact />
          <Redirect from="/tabs" to="/tabs/home" />
</IonRouterOutlet>
```

Ionic:

   Ionic CLI       : 6.11.10
   Ionic Framework : "@ionic/react": "^5.0.7"

System:

   NodeJS : v14.15.0
   npm    : 6.14.8
   OS     : macOS Catalina

**Comment by amandaejohnston** [comment]
Thank you for the issue. This has recently been added: https://ionicframework.com/docs/api/tabs Closing this out.
