### ISSUE TITLE
ionBackButton event vs. 'backButton' event - wrong name in hardware-back-button docs

### ISSUE THREAD

**Issue by inspire22** [ionic-team/ionic-docs#1783]
**Describe the bug**
The docs mention to listen for "ionBackButton", but the correct event seems to be "backbutton"

Here's the (incorrect) docs https://ionicframework.com/docs/developing/hardware-back-button

Here's a forum post discussing this.
https://forum.ionicframework.com/t/how-cancel-android-back-button-event/191163/11

**To reproduce**

Per the thread, this event mentioned in the docs is never called:
```

document.addEventListener('ionBackButton', (ev) => {
  ev.detail.register(10, () => {
    console.log('Handler was called!');
  });
});

```

But this event is:

I think both work, but I'm currently using Plugins.App.addListener("backButton", () => { stuff } )
```
document.addEventListener('backbutton', (ev) => {
    console.log('Handler was called!');
   // do something like dismissing an active modal
   this.$ionic.modalController.dismiss();
});

```
The docs here do mention the right event:
https://capacitorjs.com/docs/apis/app#method-addListener-3

Thanks for a great project!

**Comment by liamdebeasi** [comment]
You can use both `ionBackButton` and `backbutton`. Both Capacitor and Cordova fire `backbutton` events, but in the event that the two APIs diverge in the future, developers won't have to worry about it if they are using `ionBackButton`. Additionally, just learning `ionBackButton` lets developers use hardware back button functionality without concerning themselves with the underlying Capacitor/Cordova functionality. As a result, we recommend using `ionBackButton`.

**Comment by inspire22** [comment]
ionBackButton was definitely not being called as of @ionic/core version 5.1.1  or @capacitor/android 2.1.2 - I tried to update to the latest but am using the vue beta and it was forcing an update to Vue 3 which I wasn't able to get working.

**Comment by liamdebeasi** [comment]
The `ionBackButton` event was added in Ionic Framework v4.0. Several bugs were fixed and the event itself was publicly documented in Ionic Framework v5.1. 

The issue here is likely that you are using the old Ionic Vue beta for Vue 2 which lacks several important features. I recommend using a new Ionic Vue starter app to test out this functionality with Vue 3. Additionally, in Ionic Vue for Vue 3 you can use a composition API hook to easily access the hardware back button:

```js
import { useBackButton } from '@ionic/vue';

...

export default {
  setup() {
    useBackButton(10, () => {
      console.log('Handler was called!');
    });
  }
}
```
