### ISSUE TITLE
API design: properties table in tab-bar docs looks wrong

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#179]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/api/tab-bar/#properties

<img width="720" alt="screen shot 2018-11-20 at 12 08 11 pm" src="https://user-images.githubusercontent.com/6577830/48790357-28115a00-ecbd-11e8-9673-7801b583cbe4.png">

**Comment by brandyscarney** [comment]
There are other API references where this is happening too, see button: https://beta.ionicframework.com/docs/api/button

I think the solution here is to add a specified width for description and wrap the left column.

**Comment by camwiegert** [comment]
The properties list is `display: grid`, so we could get really specific and say:

```css
grid-template-columns: minmax(min-content, 40%) 1fr;
```

...so that the left hand side will take up 40% of the width at most, and otherwise collapse as needed.
