### ISSUE TITLE
ionic generate command on Scaffolding docs should say it is only supported in Angular

### ISSUE THREAD

**Issue by Jam3si** [ionic-team/ionic-docs#1799]
**URL**
https://ionicframework.com/docs/api/infinite-scroll

**What is missing or inaccurate about the content on this page?**
The Vue code is inaccurate, as I'm not familiar with TS and this was the first time trying Ionic & TS I've found that there are three errors in this example:

1)
items.value.push(i);
**Error:**
TS2345: Argument of type 'number' is not assignable to parameter of type 'never'.
**Solution:**
const items: any = ref([]);

2)
ev.target.complete();
**Error:**
TS2339: Property 'complete' does not exist on type 'EventTarget'.
**Solution:**
ev.detail.complete();

3)
ev.target.disabled = true;
**Error:**
TS2339: Property 'disabled' does not exist on type 'EventTarget'.
**Solution:**
ev.detail.disabled = true;

But then, there is an error after first load of data: 
Uncaught TypeError: ev.detail is null

There is also an misleading information in Scaffolding page (selected Vue):

https://ionicframework.com/docs/developing/scaffolding#generating-new-features
`$ ionic generate
[ERROR] Cannot perform generate for Vue projects.
        
        Since you're using the Vue project type, this command won't work. The Ionic CLI doesn't know how to generate
        framework components for Vue projects.
` 

Why is there the information about generating the pages if it is not supported?

**Bonus:**
The example is not same as shown on the right demo section, this is really confusing. How can there be some sample and different code? As I've seen there is a lot of complaints from users on Issue page about this. But for me as the "first time visitor" of Ionic framework docs, this was disaster level experience.

**Comment by amandaejohnston** [comment]
Thank you for the issue. In the time since this was posted, we've updated many of our component docs with live demos that include code snippets for all supported frameworks and run the code samples shown in real time. You can see the `ion-infinite-scroll` demos here: https://ionicframework.com/docs/api/infinite-scroll

However, it looks like the Scaffolding page is still misleading. We should update it to specify that the `ionic generate` command is only supported for Ionic Angular.

**Comment by amandaejohnston** [comment]
Resolved via https://github.com/ionic-team/ionic-docs/pull/2718, thanks again.
