### ISSUE TITLE
Missing references to vue for cli

### ISSUE THREAD

**Issue by 1beb** [ionic-team/ionic-docs#1826]
**URL**
https://ionicframework.com/docs/cli/commands/start

**What is missing or inaccurate about the content on this page?**

Missing examples and references to vue. The following section: 

![image](https://user-images.githubusercontent.com/421859/106780355-e6f38f00-6615-11eb-93cf-e8cdd0bdb12f.png)

Should also list "vue"

**Comment by mhartington** [comment]
Closing as this has been resolved.
