### ISSUE TITLE
Next steps in getting started page are the same.

### ISSUE THREAD

**Issue by marwanatef2** [ionic-team/ionic-docs#1832]
Go to [Getting started page](https://ionicframework.com/getting-started) and scroll down to Next steps.

**What is missing or inaccurate about the content on this page?**
All the paragraphs for the 3 different link are the same; misleading description.

![image](https://user-images.githubusercontent.com/30902406/107220041-8cde3980-6a1a-11eb-939f-2f3506fcadbd.png)

**Comment by amandaejohnston** [comment]
Thank you for the issue. In the time since this was posted, the page in question has been updated to not include the pictured section, so I'm going to close this out.
