### ISSUE TITLE
docs: add showWhen / hideWhen replacement

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#185]
We should include some documentation on the replacement for `showWhen`/ `hideWhen` (`ion-show-when` / `ion-hide-when`). I added it to the breaking changes here: https://github.com/ionic-team/ionic/blob/master/angular/BREAKING.md#show-when--hide-when

We could either add it somewhere to the Layout section (https://beta.ionicframework.com/docs/layout/css-utilities) or we can provide a set of utilities for this in Ionic, like we have for the text alignment, float, etc.

I'm not sure which direction we want to go here.

**Comment by brandyscarney** [comment]
Related to https://github.com/ionic-team/ionic/issues/10904

**Comment by perrygovier** [comment]
Fixed in #403
