### ISSUE TITLE
Bug: No previews available

### ISSUE THREAD

**Issue by BerkeAras** [ionic-team/ionic-docs#1859]
**Describe the bug**
Previews of components are not available (03.03.2021 / 11:06 GMT).
This issue has been tested on multiple devices and networks:
- MacOS Big Sur (Mac Mini M1 2020; 500 Mbit/s)
- Windows Server 2012 R2 Standard (two different network-connections; 1 Gbit/s)

**To reproduce**
1. Go to a component (e. g. https://ionicframework.com/docs/api/item)
2. See error (errors are in console too)

**Expected behavior**
CDN should be available/reachable.

**Screenshots**
<img width="1170" alt="Bildschirmfoto 2021-03-03 um 12 08 05" src="https://user-images.githubusercontent.com/36629890/109796980-22837800-7c19-11eb-8200-2b27d1572f1b.png">

**Browser and OS**
 - 1 OS: MacOS Big Sur 11.2.1
 - 1 Browser: Chrome 88.0.4324.192 (ARM64)
 - 2 OS: Windows Server 2012 R2 Standard
 - 2 Browser: Chrome 88.0.4324.190 (64-Bit)

**Comment by brandyscarney** [comment]
Thanks for the issue! We have recently been migrating all of our preview examples to [component playgrounds](https://ionic.io/blog/announcing-component-playgrounds-for-ionic-docs). As a result, I am not able to reproduce this, but let me know if you are still seeing it!

**Comment by BerkeAras** [comment]
@brandyscarney This issue is literally 1.5 Years old 😂
Fixed...
