### ISSUE TITLE
Duplicate 'React' sections for Usage of the Camera plugin

### ISSUE THREAD

**Issue by lukethacoder** [ionic-team/ionic-docs#1861]
**Describe the bug**
Duplicate 'React' sections for Usage of the Camera plugin. One is missing the hyperlink.

**To reproduce**
1. Go to "https://ionicframework.com/docs/native/camera#installation"
3. Scroll down to 'Usage'
4. See duplicate "React - See here."

**Expected behavior**
Only need one working hyperlink

**Screenshots**
![image](https://user-images.githubusercontent.com/13529535/109887372-adc24380-7cd5-11eb-8fd9-0ea5c9630ec5.png)

**Browser and OS (please complete the following information)**
 - OS: Windows 10 Home 19042
 - Browser: Edge Chromium
 - Version: 88.0.705.81

**Comment by jcesarmobile** [comment]
looks like it's fixed now
