### ISSUE TITLE
All CodePen Pens are duplicated on gestures.md

### ISSUE THREAD

**Issue by saschwarz** [ionic-team/ionic-docs#1874]
**Describe the bug**

All CodePen Pens are duplicated on gestures.md

**To reproduce**
1. Go to https://ionicframework.com/docs/utilities/gestures
2. Scroll down and see there is a single CodePen for each example.
3. Cmd or Ctrl-R to soft refresh
4. Page is refreshed and two CodePens are displayed for each example.

**Expected behavior**
Each CodePen should only appear once

**Screenshots**

![image](https://user-images.githubusercontent.com/184171/112226420-2729c380-8bfc-11eb-980b-4039178fa1c0.png)

**Browser and OS (please complete the following information)**
 - OS: MacOS
 - Browser: Chrome
 - Version: Google Chrome is up to date
Version 89.0.4389.90 (Official Build) (x86_64)

**Comment by brandyscarney** [comment]
Thank you for the issue! I am no longer able to reproduce this so I am going to close this but let me know if you're still seeing it!
