### ISSUE TITLE
Shadow DOM &::part() not working for any component only in IOS

### ISSUE THREAD

**Issue by muzamilabbas** [ionic-team/ionic-docs#1875]
**Describe the bug**
I have tested shadow root ::part() in android and it is working fine. But it is not working in IOS devices. Even in brow

Below style is written in general.scss file to remove indicator from ion-segment-button and caret icon from ion-select

ion-segment.secondary ion-segment-button::part(indicator) {
    display: none;
}
ion-select::part(icon) {
    display: none;
}

Below style is written in component file -> To remove tick mark from radio button

.radio-group[_ngcontent-yeu-c184] ion-radio[_ngcontent-yeu-c184]::part(container){
    display: none;
}
Both above styles and other styles working in windows machine and android devices but not working in IOS.

Here is the Ionic version I am using

ionic --version => 6.12.3

**To reproduce**
1. Include 'ion-select, ion-radio, ion-segment' in the code
2. Write a style to access its parts respectively '::part(icon), ::part(container), ::part(indicator)'
3. Test it in android and IOS
4. You can see issue in IOS. 

**Expected behavior**
The ::part() should work in android and IOS devices to modify the style of shadow part elements.

**Screenshots**
https://ibb.co/Y2PwM0w

**Browser and OS (please complete the following information)**
 - OS: IOS
 - Browser: Safari
 - Version: Latest

**Additional context**

**Comment by liamdebeasi** [comment]
CSS Shadow Parts are only supported on iOS 13.4+. Please verify that the device you are testing on supports shadow parts: https://ionicframework.com/docs/theming/css-shadow-parts#browser-support
