### ISSUE TITLE
useIonModal hook isn't available in @ionic/react

### ISSUE THREAD

**Issue by abhinavchawla13** [ionic-team/ionic-docs#1897]
**URL**
https://ionicframework.com/docs/api/modal

**What is missing or inaccurate about the content on this page?**
The first react example uses `useIonModal` which isn't available in `@ionic/react`

![image](https://user-images.githubusercontent.com/10625526/115125130-32220a80-9f94-11eb-9c95-2996f57373ab.png)

I also checked the codebase and couldn't find any references.

**Comment by sean-perkins** [comment]
Thanks for this issue. If you experience this problem with the latest version of Ionic, please create an issue here: https://github.com/ionic-team/ionic-framework/issues.

Thanks!
