### ISSUE TITLE
Add a visual example for each variation of a component

### ISSUE THREAD

**Issue by avalanche1** [ionic-team/ionic-docs#1919]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to try and test what each property and variation of a component does and how it looks - by running it in my own project, isntead of seeing it directly in the docs.

**Describe the solution you'd like**
I would like the Usage section of each component have a rendered visual representation alongside code.
Just like 99% of component frameworks for React do (AntDesign, Semantic-UI, Mantine)

**Comment by brandyscarney** [comment]
Thanks for the issue! We have recently been migrating all of our api documentation to [component playgrounds](https://ionic.io/blog/announcing-component-playgrounds-for-ionic-docs). This allows you to see the component with different properties applied, copy the code into your app, or open it in StackBlitz to mess around with it (in different frameworks too!). [Button](https://ionicframework.com/docs/api/button) is a good example of this. We have migrated about 80% of the API documentation to use playgrounds and are actively working on the rest. I am going to close this as I believe this is what you're asking for, but let me know if I'm misunderstanding. 🙂

**Comment by avalanche1** [comment]
@brandyscarney awesome!
