### ISSUE TITLE
[ion-picker] - props are poorly documented

### ISSUE THREAD

**Issue by avalanche1** [ionic-team/ionic-docs#1922]
**URL**
https://ionicframework.com/docs/api/picker

**What is missing or inaccurate about the content on this page?**
Some props, like `buttons ` & `columns` have respective types of `PickerButton ` & `PickerColumn `.
These types are not documented anywhere.

I get really frustrated because I have to dig into ionic type def files to kinda deduct which types have which props and they do what. Pls fix.
Also would be awesome if you could do the same for all the other components that have similar issues. Thanks.

**Comment by sean-perkins** [comment]
The `ion-picker` docs have been updated with component playgrounds. These examples now show usages with the expected types. 

We also highlight these interfaces on the docs pages.

Thanks!

**Comment by avalanche1** [comment]
Thanks!
But these props still need to be deduced as to what they are for
<img width="380" alt="image" src="https://user-images.githubusercontent.com/10534563/178464893-fdd44d8f-fa79-4749-87c8-9d7a6ad3b9e6.png">
