### ISSUE TITLE
useCamera call no longer in code [react/your-first-app/2-taking-photos]

### ISSUE THREAD

**Issue by amirmazmi** [ionic-team/ionic-docs#1924]
**URL** - The URL at which the content is missing or inaccurate
https://ionicframework.com/docs/react/your-first-app/2-taking-photos
<br>
**What is missing or inaccurate about the content on this page?**  

The following line is no longer accurate as `useCamera()` was removed as of #1923 
```Back at the top of the function (right after the call to useCamera, we will define a state variable to store the array of each photo captured with the Camera.```

**Comment by jcesarmobile** [comment]
looks like it's fixed now, thanks!
