### ISSUE TITLE
broken instructions on [react/your-first-app] 

### ISSUE THREAD

**Issue by erik-smit** [ionic-team/ionic-docs#1926]
**URL**
https://ionicframework.com/docs/react/your-first-app/3-saving-photos

**What is missing or inaccurate about the content on this page?**
 - `async (photo: CameraPhoto, fileName: string)`. There is no `CameraPhoto`. Maybe `Photo`?
 - `Promise<Photo>` complains "Type '{ filepath: string; webviewPath: string | undefined; }' is not assignable to type 'Photo'.". Maybe `Promise<UserPhoto>`?

**URL**
https://ionicframework.com/docs/react/your-first-app/4-loading-photos

**What is missing or inaccurate about the content on this page?**
- #1923 renamed `const photos` to `const photosInStorage`, but didn't update the `setPhotos(photos)`, so it doesn't update `photos` with the loaded list.

**Comment by smontanaro** [comment]
In addition, in 3-saving-photos there is no mention at the very start of how to "get access to the writeFile method from the FileSystem class"... This is important for those of us who are not already conversant in many of the technologies which underly Ionic.

**Comment by jcesarmobile** [comment]
thanks for the issue, it's fixed now
