### ISSUE TITLE
React Lifecycle - Describe the dependencies argument

### ISSUE THREAD

**Issue by avalanche1** [ionic-team/ionic-docs#1949]
**URL**
https://ionicframework.com/docs/react/lifecycle

**What is missing or inaccurate about the content on this page?**
The second argument to  the lifecycle hooks -the dependencies- is not described.
I had to spend a day trying to solve the issue I was having - https://forum.ionicframework.com/t/obsolete-state-in-useionviewwillenter/210861.
Plz add it to the docs + describe how and when it should be used.

**Comment by liamdebeasi** [comment]
Thanks! This was fixed in https://github.com/ionic-team/ionic-docs/pull/3078
