### ISSUE TITLE
APK build instructions do not support Capacitor

### ISSUE THREAD

**Issue by avalanche1** [ionic-team/ionic-docs#1957]
**URL**
https://ionicframework.com/docs/deployment/play-store

**What is missing or inaccurate about the content on this page?**
When I run `ionic cordova build android --prod --release` I get 
`[ERROR] Ionic doesn't support using Cordova with @ionic/react projects.`
This sd be mentioned in the docs; and alternative provided.

**Comment by amandaejohnston** [comment]
Thank you for the issue. We've since updated this page with Capacitor-specific instructions as well, which is supported in Ionic React, so I'll go ahead and close this out.
