### ISSUE TITLE
Missing / Broken View Source Links in Ionic Documentation

### ISSUE THREAD

**Issue by nvispute** [ionic-team/ionic-docs#1967]
**Describe the bug**
The links provided under the sample view in the Ionic component page to view source on Github are broken

**To reproduce**
1. Go to Ion-list component on the ionic docs/API 
2. Click View source under the mobile view on the right side 
3. It points to "Page Not Found"  [Link](https://github.com/ionic-team/ionic-docs/tree/main/src/demos/api/list/index.html)

**Expected behavior**
It should show the source code of the example shown in the mobile view in the Ionic docs/API page

**Comment by janbrasna** [comment]
Seems source links to main ionic-framework repo components list now work as expected. Is the issue fixed for you?

**Comment by jcesarmobile** [comment]
seems to be working fine now
