### ISSUE TITLE
"View Source" for component in document, but broken link

### ISSUE THREAD

**Issue by hiroghap1** [ionic-team/ionic-docs#1975]
<img width="1172" alt="スクリーンショット 2021-06-22 13 54 16" src="https://user-images.githubusercontent.com/29915679/122865794-ead44380-d361-11eb-8871-406c509758a2.png">

**URL**
https://ionicframework.com/docs/api/slides

**What is missing or inaccurate about the content on this page?**
Even if you press the "View Source" will go to the 404 page.

**Comment by AzizStark** [comment]
Every view source link is broken.

**Comment by nvispute** [comment]
@hiroghap1 I created a big issue for this same like 8 days back haven't heard from the team yet, but I am writing this comment just to say you described it better..

**Comment by jcesarmobile** [comment]
Seems to be working fine now
