### ISSUE TITLE
Update cordova-resources

### ISSUE THREAD

**Issue by karanalpe** [ionic-team/ionic-docs#2010]
**URL**
https://ionicframework.com/docs/cli/commands/cordova-resources

Service https://res.ionic.io/api/v1/upload is shutdown. I think is now reccomended use https://github.com/ionic-team/cordova-res

Look this: https://forum.ionicframework.com/t/upload-resources-fail-with-410/209741

**Comment by jcesarmobile** [comment]
Ionic CLI uses cordova-res internally, that's transparent for users, they just need to have the CLI up to date (or at least the version that added this like 2 years ago)

**Comment by karanalpe** [comment]
@jcesarmobile for older projects this is not "transparent". The documentation should indicate this or there should be a specific page for each version.

For example:

https://fontawesome.com/v4.7/icons/
https://fontawesome.com/v5.15/icons?d=gallery&p=2
...

**Comment by jcesarmobile** [comment]
the CLI is a global dependency, can be updated at any time, doesn't matter if the project is old or not and it's compatible with old projects.
