### ISSUE TITLE
V6 Beta swiper upgrade guide

### ISSUE THREAD

**Issue by conde2** [ionic-team/ionic-docs#2023]
**Describe the bug**
I'm trying to update to ionic v6 and remove the ion slides, but following the documentation it says to use the 
```html
<swiper-slide>
```
https://beta.ionicframework.com/docs/angular/slides

But there is not swiper-slide for angular, is it meant to be
```html
       <ng-template swiperSlide>Slide 3</ng-template>
```
Reference  https://swiperjs.com/angular

**Comment by rdlabo** [comment]
And this: 

```
// slides.component.scss
@import '~swiper/swiper';
@import '~@ionic/angular/css/ionic-swiper';
```

these CSS should be import to global.scss. not import to Individual components css.

**Comment by liamdebeasi** [comment]
Thanks! This is fixed now on the docs site: https://beta.ionicframework.com/docs/angular/slides
