### ISSUE TITLE
Contribute button leads to 404 page on github

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#2044]
**Describe the bug**![image](https://user-images.githubusercontent.com/1038062/129171944-4c958356-039f-41b2-bfdc-3a2e6848b7f2.png)The contribute button leads to a 404 page on github

**To reproduce**
1. Go to any page, for example https://ionicframework.com/docs/developing/android
2. Scroll to the bottom
3. Click the Contribute button
4. See error 404 with the link that its pointing to

**Screenshots**

![image](https://user-images.githubusercontent.com/1038062/129171944-4c958356-039f-41b2-bfdc-3a2e6848b7f2.png)

![image](https://user-images.githubusercontent.com/1038062/129171981-27aa9c1f-404d-49b6-8b88-53019931b887.png)

**Comment by jcesarmobile** [comment]
thanks for the issue
the contribute button is gone, now there is an "Edit this page" and seems to work fine
