### ISSUE TITLE
Currently no documentation for a Vue Picker Component

### ISSUE THREAD

**Issue by sdras** [ionic-team/ionic-docs#2053]
👋 Hi all!

Thank you for this wonderful tool. I've been loving working with it.

**URL**
[https://ionicframework.com/docs/api/picker](https://ionicframework.com/docs/api/picker)

**What is missing or inaccurate about the content on this page?**
I noticed there's currently no example for how to create a Picker component with Vue, and one exists for React, I thought I might add an example. I pared it down to be as simple as humanly possible so that folks can grok it easily.

PR incoming!

**Comment by brandyscarney** [comment]
Thanks for the issue! We have recently been migrating our documentation over to inline [component playgrounds](https://ionic.io/blog/announcing-component-playgrounds-for-ionic-docs). As a result, there are now code examples of [picker](https://ionicframework.com/docs/api/picker) usage in Vue. The code can be copied to your app or opened up in StackBlitz. Please open a new issue if you think something is still missing from the Picker documentation, thanks. 🙂
