### ISSUE TITLE
ion-datetime open() method missing?

### ISSUE THREAD

**Issue by andreasseiler** [ionic-team/ionic-docs#2056]
**URL**
The URL at which the content is missing or inaccurate

https://ionicframework.com/docs/api/datetime#methods

**What is missing or inaccurate about the content on this page?**

I try to open the ion-datetime component via the documented open() method. But when I reference the component via vue 3 $refs.<name>.open() -> I get the error that open is no function. Also when I have a look at the component, there is no open method. Are the docs wrong or am I missing something?

Thanks,
Andi

**Comment by liamdebeasi** [comment]
Thanks for the issue. You need to access the underlying component via `$el`:

```js
ionDatetimeRef.value.$el.open()
```

See https://ionicframework.com/docs/vue/troubleshooting#method-on-component-is-not-a-function for more information.
