### ISSUE TITLE
auto-grow not working on ion-textarea

### ISSUE THREAD

**Issue by DeanCMS** [ionic-team/ionic-docs#2071]
**Describe the bug**
The auto-grow attribute is not working like it should when using on ion-textarea

**Screenshots**
![image](https://user-images.githubusercontent.com/89902557/133422629-d69173c8-5edc-44d0-8066-d216f5135052.png)

**Comment by sean-perkins** [comment]
Thanks for this issue. This problem will be resolved with this PR: https://github.com/ionic-team/ionic-framework/pull/24205 and will be available in 6.2.0.
