### ISSUE TITLE
Problem class CameraPhoto (Deprecated)

### ISSUE THREAD

**Issue by ramses512** [ionic-team/ionic-docs#2080]
**Describe the bug**
CameraPhoto is deprecated, instead now use Photo. Should be changed in doc.
**To reproduce**
1. Go to 'https://ionicframework.com/docs/angular/your-first-app/3-saving-photos'
2. Search  'CameraPhoto'.
3. See error

**Expected behavior**
Should use Photo

**Browser and OS (please complete the following information)**
N/A

**Additional context**
N/A

**Comment by jcesarmobile** [comment]
thanks for the issue, it's changed now
