### ISSUE TITLE
Missing import

### ISSUE THREAD

**Issue by ramses512** [ionic-team/ionic-docs#2081]
**URL**
https://ionicframework.com/docs/angular/your-first-app/5-adding-mobile

**What is missing or inaccurate about the content on this page?**
1. Search 'Capacitor.convertFileSrc(savedFile.uri),'
2. Need add 'import { Capacitor } from '@capacitor/core';' in the example. Needs to work example.

**Comment by jcesarmobile** [comment]
Thanks for the issue.
Not sure if that was the case when the issue was reported, but now there is a link [to this page](https://ionicframework.com/docs/core-concepts/webview#file-protocol), and the link has the `import { Capacitor } from '@capacitor/core';`.
