### ISSUE TITLE
Apk signer with minimum signature scheme v2

### ISSUE THREAD

**Issue by Evanzsnr** [ionic-team/ionic-docs#2097]
**URL**
[The URL at which the content is missing or inaccurate](https://ionicframework.com/docs/deployment/play-store)

**What is missing or inaccurate about the content on this page?**
I recently uploaded an update of my ionic app and google play console rejected my update with this error, when I look at the docs, I think there needs to be some kind of update to include a way to go around this kind of issue because as of now, I don't know what to do next.  Thanks.
```
You uploaded an APK with an invalid signature (learn more about signing). 
Error from apksigner: ERROR: MIN_SIG_SCHEME_FOR_TARGET_SDK_NOT_MET: Target SDK version 30 requires a minimum of signature
scheme v2; the APK is not signed with this or a later signature scheme
```

**Comment by liamdebeasi** [comment]
Hey there,

Apologies for the delay in replying to this. We use this repo to track bugs or feature requests for our documentation site. If you still need help with an issue I recommend posting on the [Ionic Forum](http://forum.ionicframework.com) or our [Discord](https://discord.com/invite/UPYYRhtyzp.
