### ISSUE TITLE
ion-range with dualKnob in docs is not moving properly

### ISSUE THREAD

**Issue by comfortme** [ionic-team/ionic-docs#210]
# Bug Report

**Describe the Bug**
lower knob on ion-range is not moving properly (lagging)

**Steps to Reproduce**
1. Go to 'https://beta.ionicframework.com/docs/api/range/'
2. try to move lower knob on dualknob example.
3. See error

**Expected Behavior**
should move normally like higher knob

**Comment by brandyscarney** [comment]
Thanks for the issue! Which browser are you using?

**Comment by brandyscarney** [comment]
What version of Chrome and is it on Windows/Mac? Could you share a gif of what you see? I am not able to reproduce.

**Comment by comfortme** [comment]
this is what I'm seeing on windows 7 chrome 70.0.3538.110 (64 bit) while I drag the knob
![2](https://user-images.githubusercontent.com/18467824/49314781-88459e80-f4fc-11e8-9edf-c1ba5a146a8b.jpg)
![1](https://user-images.githubusercontent.com/18467824/49314782-88459e80-f4fc-11e8-8a3a-a85bd1949ad2.jpg)

**Comment by brandyscarney** [comment]
@comfortme Thanks! We will try to reproduce.

**Comment by comfortme** [comment]
@brandyscarney  thank you. I can also reproduce on windows 10 as well.
knob is dragging, falling behind and disappearing

**Comment by camwiegert** [comment]
ionic-team/ionic@74ce34fa68b926777a4166c5eb815866433ae91e
