### ISSUE TITLE
Language Dropdown Menu Seems Purposeless

### ISSUE THREAD

**Issue by bigboy-pdb-spam** [ionic-team/ionic-docs#2110]
**URL**
[Framework - Guide](https://ionicframework.com/docs)

**What is missing or inaccurate about the content on this page?**
The select menu has options for: React, Angular, JavaScript, and Vue.

Selecting a different entry (language) doesn't change the documentation sections that are shown in the menu or (appear to change) their contents.

**Comment by jcesarmobile** [comment]
closing since the dropdown is no longer present.
