### ISSUE TITLE
IonModal data/role cannot be passed to dismiss function when using useIonModal hook

### ISSUE THREAD

**Issue by smiley-uriux** [ionic-team/ionic-docs#2124]
**URL**
https://ionicframework.com/docs/api/modal

**What is missing or inaccurate about the content on this page?**
I expected the dismiss method returned from useIonModal react hook would follow signature called out in docs, however it doesn't seem to support passing data/role. 

I would expect the docs to call this out or, ideally, provide support for data/role passing through the dismiss method. As it stands, performing an action that unmounts the modal's container as part of a dismiss triggers a "Can't perform a React state update on an unmounted component" warning. Consequently I'm forced to use a setTimeout since I can't easily leverage the onDidDismiss callback without introducing extra state management.

**Comment by sean-perkins** [comment]
This was resolved in: https://github.com/ionic-team/ionic-framework/pull/25209 and available in Ionic 6.1.4 and later.
