### ISSUE TITLE
v5 sidebar demo shows v6 component

### ISSUE THREAD

**Issue by MeijerM1** [ionic-team/ionic-docs#2126]
**URL**
[The URL at which the content is missing or inaccurate](https://ionicframework.com/docs/api/datetime)

**What is missing or inaccurate about the content on this page?**
Navigate to the page and select framework version v5 in the top right.

The component on the right side of the page shows the new calendar datetime component introduced in framework version 6.

**Comment by amandaejohnston** [comment]
Confirming that this is still an issue, and applies to all components -- it's just most obvious with `ion-datetime`.
