### ISSUE TITLE
Please we need new step on how to upload a bundle to play store its now  different  no longer apk

### ISSUE THREAD

**Issue by waynelidza** [ionic-team/ionic-docs#2127]
**URL**
The URL at which the content is missing or inaccurate

**What is missing or inaccurate about the content on this page?**

**Comment by sean-perkins** [comment]
Hello @waynelidza thanks for reporting this issue.

Have you read our blog covering this topic: https://ionicframework.com/blog/google-play-android-app-bundle-requirement-for-new-apps?

I believe the outdated page you are referring to is this: https://ionicframework.com/docs/deployment/play-store.
