### ISSUE TITLE
Ion-menu-toggle missing usage documentation / example

### ISSUE THREAD

**Issue by Agular** [ionic-team/ionic-docs#2136]
The URL at which the content is missing or inaccurate
https://ionicframework.com/docs/api/menu-toggle

**What is missing or inaccurate about the content on this page?**
It does not show how the component should be used. I assumed it would work like ion-menu-button but it didn't even render. I found out by googling that you have to put a component inside e.g. ion-button to make it work

**Comment by sean-perkins** [comment]
@Agular thanks for reporting this issue!

I've opened a PR to introduce slot documentation on the `ion-menu-toggle` and also to add basic usage examples for each respective framework target.

While not always the easiest path, if you ever find yourself stuck with how to use a component in Ionic, each component should have a `/test/` folder in the repository that shows at least the basic usage of the component. 

Appreciate the feedback for the docs, helps make it easier for the next person!
