### ISSUE TITLE
Icons overlap with Previous and Next Topic 

### ISSUE THREAD

**Issue by talhafaroow33** [ionic-team/ionic-docs#2140]
pagination Icons are overlapping with Previous and Next  

![image](https://user-images.githubusercontent.com/69416703/146504968-18ab449e-5831-45dc-a5fd-a64ee0c34d95.png)

**Comment by sean-perkins** [comment]
This appears to be resolved with the latest docs. Please let me know if you see it with the live site. Thanks!
