### ISSUE TITLE
ion-tab-bar has slot but is documented in ion-tabs

### ISSUE THREAD

**Issue by dtarnawsky** [ionic-team/ionic-docs#2150]
**URL**
[tabs](https://ionicframework.com/docs/api/tabs)

**What is missing or inaccurate about the content on this page?**
ion-tabs is documented with slots as a property but ion-tab-bar is the place where the slot property is used (bottom, top).

**Comment by amandaejohnston** [comment]
Closing this out for the reasons described in the comments on the related PR: https://github.com/ionic-team/ionic-framework/pull/24498
