### ISSUE TITLE
In ion-modal - Sheet Modals add a note to have a breakpoint at 0 to exit when swiped away

### ISSUE THREAD

**Issue by omar2205** [ionic-team/ionic-docs#2155]
**Is your feature request related to a problem? Please describe.**
With Sheet Modals, if there is not 0 breakpoint (ex: [0, 0.5]), the modal won't be closed if swiped all the way down.

**Describe the solution you'd like**
Add a note to mention it.

**Comment by amandaejohnston** [comment]
Resolved via https://github.com/ionic-team/ionic-docs/pull/2732.
