### ISSUE TITLE
Ionic 5 animations modal outdated / broken example

### ISSUE THREAD

**Issue by Agular** [ionic-team/ionic-docs#2166]
https://ionicframework.com/docs/utilities/animations#modals
The URL at which the content is missing or inaccurate

**What is missing or inaccurate about the content on this page?**
1. The example code / fiddle is not working. To add modal elements for the wrapper and backdrop animations, the elements must be queried from the shadowRoot e.g. baseEl.**shadowRoot**.querySelector('.modal-wrapper'). the fiddle immediately works when adding this part.

**Comment by jcesarmobile** [comment]
it's working fine now
