### ISSUE TITLE
Glossary/reference link broken on Intro home

### ISSUE THREAD

**Issue by janbrasna** [ionic-team/ionic-docs#2176]
**Describe the bug**
Glossary link for web standards is rendered with invalid url /reference instead of /docs/referece on docs home "Introduction to Ionic".

**To reproduce**
1. Go to https://ionicframework.com/docs
3. Scroll down to https://ionicframework.com/docs#web-standards-based
2. Click on 'standardized web technologies'
4. See 404 error

**Expected behavior**
The path should be generated either as /docs/reference/glossary or relatively ./reference/glossary instead of the absolute /reference/glossary now being published.

**Additional context**
Since this change:
https://github.com/ionic-team/ionic-docs/commit/5e1a443d11514a50b113bc0e968e3f752c995b9a#diff-b4d68dc855d0f9476d3f2ee343853bd21bf82ea9960d0cf06661baa244439dd6L69
it's been broken, and I haven't been able to identify why all the links elsewhere work… incl. those with anchor hash, that all somehow pass the link generation correctly — just not this one.

**Comment by pfurbacher** [comment]
In addition to the above report, the following links are also broken (suggested corrections are in-line):

- href="/cli" (the value should be "/docs/cli")
- href="#ionic-appflow" (the value should read "#appflow" if this is meant to point to the AppFlow section on the same page; otherwise the value should refer to the main AppFlow page)

**Comment by janbrasna** [comment]
@pfurbacher Nice catch. The #hash is probably just a broken link (since #1840 in e2503f5): i'll propose a fix for that separately. Nonetheless the CLI link you mention is exactly the same case as the reported Glossary — for some reason in build compilation the links are not written out with the correct path.

**Comment by janbrasna** [comment]
Ha! I suspect the broken links just miss their correct .md suffix — that should fix them for output too.
