### ISSUE TITLE
Samples not visible on some screens

### ISSUE THREAD

**Issue by maratumba** [ionic-team/ionic-docs#2180]
**Describe the bug**
The samples are not visible on my -admittedly kinda old- Macbook Pro screen in a maximized Chrome window. In fact there aren't even any hints that there are samples. I actually realized that there are samples while searching the repo for suggestions to add samples.

**To reproduce**
1. Scale the viewport on Chrome to 1280x800
2. Visit any component documentation page
3. Notice that there is now way to know that there are samples

**Expected behavior**
Samples visible on the page or at least there is some sort of a hamburger button to reveal them.

**Screenshots**
![image](https://user-images.githubusercontent.com/2898911/150854211-fa1412bb-5d70-49d2-8f86-6242e665e482.png)

After scaling it to 90%:
![image](https://user-images.githubusercontent.com/2898911/150854692-639362f2-d158-4cfc-9484-562ce124c760.png)

**Browser and OS (please complete the following information)**
 - OS: MacOS Mojave (10.14.6)
 - Browser: Chrom
 - Version: 97.0.4692.99

**Comment by brandyscarney** [comment]
Thank you for the issue! We have been migrating our demos over to inline examples, so this shouldn't be a problem 
anymore. We have migrated about 80% of the demos and are actively working on the remaining ones, but you can see [Avatar](https://ionicframework.com/docs/api/avatar) has already been migrated to show the inline playgrounds. I am going to close this as that should fix your problem, but let me know if you're still seeing issues. 🙂
