### ISSUE TITLE
ion-datetime range selector

### ISSUE THREAD

**Issue by oneclickwebstudio** [ionic-team/ionic-docs#2194]
**Is your feature request related to a problem? Please describe.**
Ability to select starting and ending dates in one calendar picker

**Describe the solution you'd like**
No solution yet

**Describe alternatives you've considered**
[ion-calendar2](https://github.com/HsuanXyz/ion2-calendar)
[mobiscroll](https://demo.mobiscroll.com/angular/range/# )

**Additional context**
![image](https://user-images.githubusercontent.com/5783161/153705836-e15fc239-2f92-4333-96ae-fb9d6846dcc8.png)

**Comment by sean-perkins** [comment]
Closing as a duplicate of: https://github.com/ionic-team/ionic-framework/issues/23572.
