### ISSUE TITLE
Component preview not matching doc version

### ISSUE THREAD

**Issue by manu2504** [ionic-team/ionic-docs#2197]
**URL**
[ion-datetime v5](https://ionicframework.com/docs/v5/api/datetime)

**What is missing or inaccurate about the content on this page?**
The ios/android component preview on the right side displays the latest version 6 of the component, instead of the version being documented.

**Comment by sean-perkins** [comment]
@manu2504 thanks for reporting this issue!

Unfortunately how the embedded examples function, we are unable to easily point them at a specific version at this time. They will always display the latest examples as they exist in the `main` branch on the framework repository.

**Comment by amandaejohnston** [comment]
I'm going to merge this with this issue: https://github.com/ionic-team/ionic-docs/issues/2126 While that one specifically mentions `ion-datetime`, the root cause is the same with all components.
