### ISSUE TITLE
Background Upload Plugin Installation Instruction not up to date on Ionic Docs

### ISSUE THREAD

**Issue by zfir** [ionic-team/ionic-docs#2199]
**URL**

https://ionicframework.com/docs/native/background-upload

**What is missing or inaccurate about the content on this page?**

Installation instructions are missing for Background Upload Plugin

Please find the updated commands to install this plugin: https://github.com/danielsogl/awesome-cordova-plugins/pull/4028

Regards,
Zafir.

**Comment by jcesarmobile** [comment]
the docs now redirect to the official docs awesome-cordova-plugin docs, so you should report it to the maintainer of the awesome-cordova-plugins
https://danielsogl.gitbook.io/awesome-cordova-plugins/background-upload
