### ISSUE TITLE
Ionic API doc  'git submodule' not fetched

### ISSUE THREAD

**Issue by kael** [ionic-team/ionic-docs#22]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**

**Current behavior:**

**Expected behavior:**

API doc necessary for `http://localhost:3333/docs/api/*` pages are not fetched when being fetched from git submodules.

**Steps to reproduce:**

```bash
$ git submodule update --init
Cloning into '/home/kael/Project/dev/ionic-docs/sources/component-preview'...
ERROR: Repository not found.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
fatal: clone of 'git@github.com:ionic-team/component-preview.git' into submodule path '/home/kael/Project/dev/ionic-docs/sources/component-preview' failed
Failed to clone 'sources/component-preview'. Retry scheduled
...
```
**Other information:**

**Comment by pickfire** [comment]
@kael The repository https://github.com/ionic-team/component-preview is not present as of now.

**Comment by kael** [comment]
Thanks. The repo is now available.

I have the doc up and running, awesome.

After `npm run api-docs`, I had to `cp -rf src/content/* www/docs/content/` to have it fully working (I might have missed something).
