### ISSUE TITLE
Wrong code structure in ion-slides/swiper docs

### ISSUE THREAD

**Issue by manikandan-bambus** [ionic-team/ionic-docs#2201]
**URL**
The URL at which the content is missing or inaccurate
https://ionicframework.com/docs/angular/slides
**What is missing or inaccurate about t
![Screenshot from 2022-02-23 12-23-30](https://user-images.githubusercontent.com/83752624/155273726-bf1f1e33-7954-44d8-9716-52a57bef6226.png)
he content on this page?**
Check the code

**Comment by liamdebeasi** [comment]
Hey there,

Can you please describe what is wrong with the code in the screenshot you provided?

**Comment by liamdebeasi** [comment]
Thanks! Looks like it should say the following instead:

```js
this.slides = swiper;
```

**Comment by manikandan-bambus** [comment]
> Thanks! Looks like it should say the following instead:
> 
> ```js
> this.slides = swiper;
> ```

Yes replace it with the variable "swiper"

**Comment by sean-perkins** [comment]
Fixed in https://github.com/ionic-team/ionic-docs/pull/2246, thanks for reporting this!
