### ISSUE TITLE
Documentation menu label overflow

### ISSUE THREAD

**Issue by vvanpo** [ionic-team/ionic-docs#221]
https://github.com/ionic-team/ionic/issues/16669

[x] bug report

**URL:**
https://beta.ionicframework.com/docs/native/
https://beta.ionicframework.com/docs/native/action-sheet
https://beta.ionicframework.com/docs/native/abbyy-rtr

**Current behavior:**
A menu label under the "Native APIs" heading in the v4 beta documentation is overflowing atop the subsequent label. It's quite difficult to click the obscured menu item.

![text-overflow](https://user-images.githubusercontent.com/3506391/49772003-71dbd780-fca0-11e8-89ba-97cd3e88c3fe.PNG)

**Expected behavior:**
Either the label should wrap onto a new line, or the sidebar should expand to accommodate the longer label.

**Steps to reproduce:**
Visit any meny item in https://beta.ionicframework.com/docs/native/ and observe the text-overtop-text.

**Comment by camwiegert** [comment]
d92418f1bfb5dd7a25324016ee455bfc13494293
