### ISSUE TITLE
React overview not react/overview.md anymore?

### ISSUE THREAD

**Issue by janbrasna** [ionic-team/ionic-docs#2220]
**Describe the bug**
React overview page as seen in navigation is in react.md, however some content links to react/overview.md that's probably not maintained anymore (and not linked from menu).

**To reproduce**
1. See React links on Intro page in the first paragraph vs. in the next "Overview" paragraph.
2. Click the "React" link from "Overview" paragraph.
3. Then click on 'React › Overview' from context menu.
4. Compare the two targets.

**Expected behavior**
Only one "React overview" content.

**Additional context**
- Angular (overview) is in `angular/overview.md`
- Vue (overview) is in `vue/overview.md`
- React (overview) is in `react.md`…
…yet there's an actual `react/overview.md` linked here and there… and that page seems broken (w/ no frontmatter so no navigation etc.)

**Comment by janbrasna** [comment]
Thanks @brandyscarney! Yet there's the other half of the issue:

The "duplicate"/unused [docs/react/overview.md](https://github.com/ionic-team/ionic-docs/blob/5633ce928fa5bd3b17bee39ba87a2bda8ad7ff20/docs/react/overview.md) file is still present. Is there maybe a consensus on removing it; and/or redirecting it to `docs/react.md`?

**Comment by brandyscarney** [comment]
Ah! Let me tag in @jaredcbaum for this one. Do you want to remove or redirect this file?

**Comment by mapsandapps** [comment]
Thanks for reporting this issue! We'll be removing the extra "overview" page and any links to it.
