### ISSUE TITLE
cordova-plugin-speechrecognition is not working in Ionic5

### ISSUE THREAD

**Issue by sagarsumit** [ionic-team/ionic-docs#2225]
Hi Team,

I have upgraded my Ionic to version 5 and I want to [https://github.com/pbakondy/cordova-plugin-speechrecognition](https://github.com/pbakondy/cordova-plugin-speechrecognition) but after upgrading, the given plugin is giving me an error:
**Native: tried calling SpeechRecognition.isRecognitionAvailable, but Cordova is not available. Make sure to include cordova.js or run in a device/simulator**

`ERROR Error: Uncaught (in promise): cordova_not_available
    at resolvePromise (zone.js:1255:1)
    at resolvePromise (zone.js:1209:1)
    at zone.js:1321:1
    at ZoneDelegate.invokeTask (zone.js:434:1)
    at Object.onInvokeTask (core.mjs:25463:33)
    at ZoneDelegate.invokeTask (zone.js:433:1)
    at Zone.runTask (zone.js:205:1)
    at drainMicroTaskQueue (zone.js:620:1)`

And documentation link is [https://ionicframework.com/docs/native/speech-recognition#angular](https://ionicframework.com/docs/native/speech-recognition#angular)

**Comment by jcesarmobile** [comment]
are you using cordova or capacitor?
if running in capacitor, are you running on web? android? ios?
capacitor doesn't support cordova plugins when running as web, only when running natively on iOS or Android.

**Comment by jcesarmobile** [comment]
Closing since there was no response
