### ISSUE TITLE
Foreground service plugin

### ISSUE THREAD

**Issue by lisbuenas** [ionic-team/ionic-docs#2253]
The current documentation on website https://ionicframework.com/docs/v5/native/foreground-service doesn't show how to use with reactjs this plugin.

When tried to use, the plugin shows that missing angular/core lib 

Is there any code sample showing the right usage ?

**Comment by jcesarmobile** [comment]
the plugins listed don't belong to ionic, they are part of the [@awesome-cordova-plugins](https://github.com/danielsogl/awesome-cordova-plugins) project and it was initially created for supporting angular only, and the usage instructions are fetched from @awesome-cordova-plugins project and they have no react examples.
We provide this docs as an example, using any other plugin should be similar to that
https://ionicframework.com/docs/v5/native/community#react
