### ISSUE TITLE
docs: include interface options in API docs

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#229]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**URL:**
https://beta.ionicframework.com/docs/

Currently there is no documentation for interface options. For example, see Picker: https://beta.ionicframework.com/docs/api/picker

The Picker lists types for its options including PickerButton[] and PickerColumn[] but there is no documentation (that I can find) on what these interfaces are.

Here are the interfaces directly from the src code:

```
export interface PickerButton {
  text?: string;
  role?: string;
  cssClass?: string | string[];
  handler?: (value: any) => boolean | void;
}

export interface PickerColumn {
  name: string;
  align?: string;
  selectedIndex?: number;
  prevSelected?: number;
  prefix?: string;
  suffix?: string;
  options: PickerColumnOption[];
  cssClass?: string | string[];
  columnWidth?: string;
  prefixWidth?: string;
  suffixWidth?: string;
  optionsWidth?: string;
  refresh?: () => void;
}

export interface PickerColumnOption {
  text?: string;
  value?: any;
  disabled?: boolean;
  duration?: number;
  transform?: string;
  selected?: boolean;
}
```

**Comment by liamdebeasi** [comment]
This has been added: https://ionicframework.com/docs/api/picker#interfaces
