### ISSUE TITLE
Removed cssClass prop still shown in example

### ISSUE THREAD

**Issue by TylerAHolden** [ionic-team/ionic-docs#2290]
**URL**
Specifically for React components I noticed
[The URL at which the content is missing or inaccurate](https://ionicframework.com/docs/api/popover#inline-popover-with-state)
& other components where cssClass was a prop (Modal etc)

**What is missing or inaccurate about the content on this page?**
The examples show usage of the cssClass prop, however, it looks like that was removed in favor of just using `className`. 

https://github.com/ionic-team/ionic-framework/issues/24504 noted the issue but the docs still reflect the incorrect usage.

**Comment by brandyscarney** [comment]
Thanks for the issue! We recently updated our documentation and I no longer see `cssClass` being used there or in modal: https://ionicframework.com/docs/api/popover

Is this still an issue in other parts of the documentation?
