### ISSUE TITLE
Can't access ionic 4 native docs.

### ISSUE THREAD

**Issue by sangupta007** [ionic-team/ionic-docs#231]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**

https://beta.ionicframework.com/docs/native/camera/

**Current behavior:**

Url gives *Unable to fetch native/camera:*

**Expected behavior:**

Url should work fine

**Steps to reproduce:**
Open the given link in any browser

**Other information:**
Tested on:
Google Chrome (Win10)
Version 70.0.3538.110 (Official Build) (64-bit)

**Comment by alexeevvlad** [comment]
experiencing the same issue too

**Comment by nicobytes** [comment]
experiencing the same issue too

![screen shot 2018-12-16 at 10 19 08 am](https://user-images.githubusercontent.com/7611944/50054800-22702e00-011c-11e9-85b1-adc0f1000137.png)
![screen shot 2018-12-16 at 10 19 10 am](https://user-images.githubusercontent.com/7611944/50054801-22702e00-011c-11e9-912e-9244cb4b88db.png)

**Comment by JoshuaPerk** [comment]
+1

**Comment by camwiegert** [comment]
Thanks for the report, everyone. Fixed here: cd895e8f606f82d66e3a77b480e4c020f7cb7bac
