### ISSUE TITLE
Native Docs Unable To Fetch Information

### ISSUE THREAD

**Issue by ewwwgiddings** [ionic-team/ionic-docs#232]
# Bug Report

**Ionic version:**

[x] **4.x**

**Current behavior:**

https://beta.ionicframework.com/docs/native/in-app-browser says 'Unable to fetch...' when menu item is clicked.

**Expected behavior:**

To fetch the docs so I can see their use

**Steps to reproduce:**

Go to the link above and try to see the docs for the plugin

**Comment by camwiegert** [comment]
Fixed here: cd895e8f606f82d66e3a77b480e4c020f7cb7bac
