### ISSUE TITLE
browser support should include angular 14 note

### ISSUE THREAD

**Issue by jcesarmobile** [ionic-team/ionic-docs#2388]
There is an angular 13 note, but should include an angular 14 note too

**URL**
https://ionicframework.com/docs/reference/browser-support#a-note-on-angular-13-support

**What is missing or inaccurate about the content on this page?**
Missing an Angular 14 note where it says basically the same but using es2020 instead of es2015

**Comment by liamdebeasi** [comment]
Fixed, thanks Julio!
