### ISSUE TITLE
Unable to access Ionic Framework site

### ISSUE THREAD

**Issue by mayankdargan03** [ionic-team/ionic-docs#2400]
Hi Team,

I have been trying to access ionicframework.com from past one week and it seems the server is down. Could please rectify this on priority.
<img width="1440" alt="Screenshot 2022-06-21 at 12 36 23 PM" src="https://user-images.githubusercontent.com/89840915/174738155-6aabb19c-85c7-4d5e-9800-2e8b165f1e60.png">

**Comment by jaredcbaum** [comment]
Can you provide more information about your location, environment, and give an update if this is still a problem.

**Comment by mayankdargan03** [comment]
@jaredcbaum I was trying to access it from India, and it worked around 12:29 IST.
