### ISSUE TITLE
ion-textarea maxLength attribute

### ISSUE THREAD

**Issue by overbost** [ionic-team/ionic-docs#2439]
**URL**
https://ionicframework.com/docs/api/textarea#properties

**What is missing or inaccurate about the content on this page?**
Is reported maxlength attribute, but is maxLength instead.

**Comment by sean-perkins** [comment]
@overbost thanks for reporting this issue. The attribute is correctly named as `maxlength`, when using JSX bindings, the property is renamed to match React conventions (`maxLength`). 

When accessing the property list from the element, the property will come across as `maxlength`.
