### ISSUE TITLE
bug: studio faq page is outdated

### ISSUE THREAD

**Issue by alcalyn** [ionic-team/ionic-docs#2466]
**URL**
[The URL at which the content is missing or inaccurate](https://github.com/ionic-team/ionic-docs/blob/main/docs/studio/faq.md)

**What is missing or inaccurate about the content on this page?**
I landed on this explaining that ionic 4 is maintained, and no longer ionic 3.

I am very confused about all documentation I find on the web, still getting v1 results but not the equivalent for the v6.

I think this page should be either deleted as I found other migration guides, or updated.

**Comment by thetaPC** [comment]
Thanks for the issue! This has been resolved via ionic-team/ionic-docs#2900 and will be available soon.

**Comment by thetaPC** [comment]
The fix has been deployed to the [Framework docs](https://ionicframework.com/docs).
