### ISSUE TITLE
Inline Popovers

### ISSUE THREAD

**Issue by D-Mino** [ionic-team/ionic-docs#2473]
<img width="454" alt="Screen Shot 2022-08-01 at 4 14 26 PM" src="https://user-images.githubusercontent.com/23691343/182116336-5c4788b1-5900-4390-8db5-556569115137.png">

Loop 'div.popover-viewport' element after Popover is opened.

**Comment by sean-perkins** [comment]
@D-Mino we will need a lot more context to help with this issue. What docs example are you seeing this problem with?
