### ISSUE TITLE
ion-select[interface="popover"] is not work in component-preview.

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-docs#248]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

https://github.com/ionic-team/component-preview/blob/master/src/components/select/select.tsx#L45

is not working in docs. md and ios.

**URL:**
docs is here.
https://beta.ionicframework.com/docs/components/#select

**Current behavior:**
popover contents is not display.

**Expected behavior:**
display popover.

**Steps to reproduce:**

**Other information:**

**Comment by camwiegert** [comment]
This page no longer contains a demo.
