### ISSUE TITLE
@ionic/vue ion-popover `side` propery doesn't work as expected

### ISSUE THREAD

**Issue by adin00** [ionic-team/ionic-docs#2484]
**Describe the bug**
The popover will always open downwards, regardless of the selected side.

**To reproduce**
1. go to https://ionicframework.com/docs/api/popover#side-and-alignment-demo
2. select `Vue` demo
3. click to open in StackBlitz
4. click on first button (side=top, alignment=center) and compare it with the result from docs (link at 1st step)

**Expected behavior**
Popover with `side=top` should open upwards from the trigger.

**Browser and OS (please complete the following information)**
 - OS: All
 - Browser: Chrome

**Comment by brandyscarney** [comment]
Thank you for the issue! I am not able to reproduce this. Are you still seeing this issue?
