### ISSUE TITLE
Photo gallery tutorial - import to android studio camera doesn't work

### ISSUE THREAD

**Issue by ehyvn** [ionic-team/ionic-docs#2488]
I imported the ionic photo gallery app to android studio, gave the permissions for read & write external storage, and connected an Android 11 device. Now the camera doesn't open when I click the camera button and I have no idea why it's not working.

This is the android manifest file :

<?xml version="1.0" encoding="utf-8"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="io.ionic.starter">

    
    <uses-permission android:name="android.permission.INTERNET" />
    <uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE"/>
    <uses-permission
        android:name="android.permission.WRITE_EXTERNAL_STORAGE"
        android:maxSdkVersion="28" />

    <uses-permission android:name="android.permission.CAMERA" />
    <uses-permission android:name="android.permission.RECORD_AUDIO" />
    <uses-permission android:name="android.permission.MODIFY_AUDIO_SETTINGS" />

    <application
        android:allowBackup="true"
        android:icon="@mipmap/ic_launcher"
        android:label="@string/app_name"
        android:roundIcon="@mipmap/ic_launcher_round"
        android:supportsRtl="true"
        android:theme="@style/AppTheme">

        <activity
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|smallestScreenSize|screenLayout|uiMode"
            android:name="io.ionic.starter.MainActivity"
            android:label="@string/title_activity_main"
            android:theme="@style/AppTheme.NoActionBarLaunch"
            android:launchMode="singleTask"
            android:exported="true">

            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>

        </activity>

        <provider
            android:name="androidx.core.content.FileProvider"
            android:authorities="${applicationId}.Fileprovider"
            android:exported="false"
            android:grantUriPermissions="true">
            <meta-data
                android:name="android.support.FILE_PROVIDER_PATHS"
                android:resource="@xml/file_paths"></meta-data>
        </provider>
    </application>

</manifest>

Also, when I used it on web it successfully took pictures but lagged when taking it and kept saving the picture twice.

I'd appreciate any help. Thank you.

**Comment by jcesarmobile** [comment]
There are three photo gallery apps, one per framework, please, report the issue on the app you tried
https://github.com/ionic-team/tutorial-photo-gallery-vue
https://github.com/ionic-team/tutorial-photo-gallery-react
https://github.com/ionic-team/tutorial-photo-gallery-angular
