### ISSUE TITLE
I want to script https://ionicframework.com/docs

### ISSUE THREAD

**Issue by cyanora** [ionic-team/ionic-docs#2490]
Hello, i want to https://ionicframework.com/docs php script. But just docs website not app. Can you send me please?

**Comment by sean-perkins** [comment]
@cyanora I am unable to understand your request. Could you possibly rephrase or give another example that might help me understand?

**Comment by jcesarmobile** [comment]
Docs content is in this repository, you just have to clone it.
There is no php script, the docs site is not built using php.
