### ISSUE TITLE
Your First Ionic App: Outdated storage plugin instructions

### ISSUE THREAD

**Issue by Canuckaholic** [ionic-team/ionic-docs#2491]
**Describe the bug**

I'm going through the "create your first Ionic app" tutorial for React (https://ionicframework.com/docs/react/your-first-app), and the instructions say to install `@capacitor/storage`, but this plugin is no longer included in Capacitor 4.

It looks like `@capacitor/preferences` is now what should be used.

**Comment by kensodemann** [comment]
You are correct. Would you be willing to create a PR for the doc via the edit link at the bottom of the page?
