### ISSUE TITLE
Navigating to grid scrolls focus to the first input

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#25]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**

https://beta.ionicframework.com/docs/layout/grid

**Current behavior:**

Navigate to layout -> structure -> grid and see that it is scrolled halfway down the page to the input box in the example

**Expected behavior:**

I would expect the page to be at the top of the document upon navigation

**Comment by camwiegert** [comment]
@brandy This would happen if the input was `autofocus`'d, right? Is that the case?

**Comment by brandyscarney** [comment]
@camwiegert Nevermind this is indeed still happening here: https://github.com/ionic-team/ionic-docs/blame/master/src/content/layout/grid.md#L219

**Comment by camwiegert** [comment]
@brandyscarney Thanks. I'll check it out.

**Comment by camwiegert** [comment]
Closing as this is addressed in the next Ionic beta release: ionic-team/stencil@aac503bb5a1fa9b290ffe161eb5db918b91ecf90
