### ISSUE TITLE
Document the return types for controller’s create method, like loadingCtrl.create().

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/ionic-docs#251]

**Comment by camwiegert** [comment]
@adamdbradley Right now we have a complete function signature for methods, including the return type. For example, on loading-controller's create method:

```
create(opts?: LoadingOptions | undefined) => Promise<HTMLIonLoadingElement>
```

Does that suffice? Or do you think there is a more useful way to present that?

**Comment by perrygovier** [comment]
This is no longer applicable in v5
