### ISSUE TITLE
Ionic docs view not working

### ISSUE THREAD

**Issue by ImAbhishekTomar** [ionic-team/ionic-docs#2519]
I have tested on all browsers but the ionic docs view not working.

<img width="1499" alt="Screenshot 2022-09-01 at 1 43 43 AM" src="https://user-images.githubusercontent.com/6933841/187773570-e8bf5d52-d965-4c15-8f54-189c0bc722d1.png">

**Comment by liamdebeasi** [comment]
Thanks! This should be fixed now. You may need to do a hard refresh/clear your browser cache.
