### ISSUE TITLE
Platform Not Included in v4 API Docs

### ISSUE THREAD

**Issue by ewwwgiddings** [ionic-team/ionic-docs#253]
**I'm submitting a ...**  (check one with "x")
[ ] bug report
[x] feature request

**URL:**

https://beta.ionicframework.com/docs/api

**Current behavior:**

Does not included Platform even though it says this in the "Overview" section:
The Programmatic APIs are classes like MenuController, Config or Platform. These are services provided by Ionic that can be injected into your classes.

**Expected behavior:**

Expected to see the Config and Platform docs in the new API docs.

**Steps to reproduce:**

Go here and to v4: https://beta.ionicframework.com/docs/api and look for those two. 

**Other information:**

**Comment by liamdebeasi** [comment]
This has been resolved in a5bdd41. Thanks for the report!
