### ISSUE TITLE
Stacked Modal Backdrop not working

### ISSUE THREAD

**Issue by bastifix** [ionic-team/ionic-docs#2537]
[**URL**](https://ionicframework.com/docs/api/modal)

There is an explanation for stacked modals and this code for showing backdrops:
```
ion-modal.stack-modal {
  --box-shadow: 0 28px 48px rgba(0, 0, 0, 0.4);
  --backdrop-opacity: var(--ion-backdrop-opacity, 0.32);
}
```
But it's not working.
I added it to my `global.scss` and open the stacked modal with `cssClass: 'stack-modal',`

**Comment by liamdebeasi** [comment]
Thanks for the report. Do you have a code sample I can run to verify this behavior? I cannot reproduce the issue on my end.

**Comment by bastifix** [comment]
Hey, here: [https://stackblitz.com/edit/angular-ionic-6-david-lnzwrf?file=src%2Fapp%2Fapp.component.html](https://stackblitz.com/edit/angular-ionic-6-david-lnzwrf?file=src%2Fapp%2Fapp.component.html)

**Comment by bastifix** [comment]
Wow, I really tried many things... But not that simple one... Thanks!
