### ISSUE TITLE
Wrong documentation

### ISSUE THREAD

**Issue by Mani-VD** [ionic-team/ionic-docs#2564]
I tried this code as per documentation
ion-badge {
  --background: purple;
  --color: white;
}
But this one is working
ion-badge {
  background-color: purple;
  color: white;
}

**ionic info:**

   Ionic CLI                     : 6.19.0 (/usr/local/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 6.2.4
   @angular-devkit/build-angular : 14.2.0
   @angular-devkit/schematics    : 14.2.0
   @angular/cli                  : 14.2.0
   @ionic/angular-toolkit        : 7.0.0

Capacitor:

   Capacitor CLI      : 4.1.0
   @capacitor/android : 4.1.0
   @capacitor/core    : 4.1.0
   @capacitor/ios     : 4.1.0

Utility:

   cordova-res                          : not installed globally
   native-run (update available: 1.7.0) : 1.6.0

System:

   NodeJS : v16.15.0 (/usr/local/bin/node)
   npm    : 8.5.5
   OS     : Linux 5.15

**Comment by sean-perkins** [comment]
@Mani-VD can you provide an example Stackblitz of this not working?

Here is a generated Stackblitz from that example: https://stackblitz.com/edit/angular-weos47?file=src%2Fapp%2Fexample.component.css
