### ISSUE TITLE
Need docs on how to override the platform mode in Config in Angular

### ISSUE THREAD

**Issue by bensperry** [ionic-team/ionic-docs#257]

**Comment by rondog** [comment]
I was trying to figure this out and all the < Ionic 4 posts I found said something like

`
IonicModule.forRoot(MyApp, {
  mode: 'ios'
}),
`

I figured out with Ionic 4, it is simply

`
IonicModule.forRoot({
  mode: 'ios'
}),
`

for anyone who comes across this

**Comment by brandyscarney** [comment]
Closing to track this in #270
