### ISSUE TITLE
bug: Nowhere it's said to install @capacitor/cli

### ISSUE THREAD

**Issue by dcasbonne** [ionic-team/ionic-docs#2597]
### Describe the Bug

I'm new to Ionic and capacitor. Like really new !
I've used the wizard to generate my app, ionic serve to view it in browser. Then I want to view it in Android. I follow the doc which is really great but it's said "ionic capacitor build android" and it does nothing in my terminal (i'm on a Mac).
I was stuck for about 30-40min without any clue ....
Then I decided to install @capacitor/cli as seen on a forum and it unlocks everything !

### Expected Behavior

Just mention to install @capacitor/cli in the capacitor section of Android docs

### Steps to Reproduce

Follow the doc :)

**Comment by sean-perkins** [comment]
@dcasbonne can you provide a link to the docs page that is missing this information? Thanks!

**Comment by dcasbonne** [comment]
@sean-perkins yes for sure, I forgot the most important ^^
I'm talking about that page : https://ionicframework.com/docs/developing/android

**Comment by jcesarmobile** [comment]
This was a bug on @ionic/cli, was fixed and released 2 weeks ago, update to latest CLI
