### ISSUE TITLE
v4 Docs: Thumbnail images missing

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-docs#261]
**I'm submitting a ...**  (check one with "x")
[X ] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/api/thumbnail/

**Current behavior:**
Thumbnail images not found, displaying a broken image

**Expected behavior:**
Show the svg that is referenced.

**Steps to reproduce:**

**Other information:**

**Comment by RafaelKr** [comment]
Same problem as in your other issue, more info here: https://github.com/ionic-team/ionic-docs/issues/262#issuecomment-452333334
