### ISSUE TITLE
Input misalignment

### ISSUE THREAD

**Issue by isurendrasingh** [ionic-team/ionic-docs#263]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/components/#input

**Current behavior:**

There is a small bug in alignment of the second input.

![screenshot 3](https://user-images.githubusercontent.com/7621607/50740074-54eae380-120f-11e9-9dfe-5976808d40dc.png)

**Expected behavior:**

Remove the line width of second input.

**Steps to reproduce:**

Check the link

**Comment by rtpHarry** [comment]
I agree I've never been a fan of it but I don't think it's an accidental misalignment.

If you scroll down further on that page you will see all of the examples with lists have a full-width line as the last item, it caps off the list.

Either way, I think this would be a bug on the main repo, not the docs.

**Comment by camwiegert** [comment]
@isurendrasingh Yep, pretty much what @rtpHarry has said above. And I believe this was changed in a recent round of iOS design updates. Thank you!
