### ISSUE TITLE
content: Datetime doc mentions "done" and "cancel" methods

### ISSUE THREAD

**Issue by Gkleinereva** [ionic-team/ionic-docs#2637]
### URL

https://ionicframework.com/docs/api/datetime#showing-confirmation-buttons

### Issue Description

The link above mentions `done` and `cancel` methods triggered by the buttons, but there is no other mention of a `done` method in the documentation.   I played with the stackblitz a little bit, and couldn't get a public `cancel()` method on the component to be called, either.

Either this documentation isn't clear (what methods are Done and Cancel preconfigured to call), or it's inaccurate (I don't think they're actually preconfigured to do anything).

**Comment by sean-perkins** [comment]
@Gkleinereva appreciate you reporting this!

Yes, this documentation is incorrect. It should be referring to the `confirm()` public method that exists on `ion-datetime`. There is no `done()` method. 

The `cancel()` API is meant to dismiss the popover or modal that the `ion-datetime` is presented within. You can take advantage of this by passing `true` when calling `cancel`.

e.g.:
```ts
const datetime = document.querySelector('ion-datetime'); // a reference to your datetime element
datetime.cancel(true);
```

If you do not pass `true`, the overlay will not be dismissed, but `ionCancel` will be emitted.

**Comment by Gkleinereva** [comment]
@sean-perkins thanks for answering my question and addressing this  :)
