### ISSUE TITLE
content: List header wrong source code in example

### ISSUE THREAD

**Issue by Vectorfield4** [ionic-team/ionic-docs#2638]
### URL

https://ionicframework.com/docs/api/list-header#list-header-lines

### Issue Description

Wrong source code.

Example:
![image](https://user-images.githubusercontent.com/47894313/200907563-8ae2589c-f7f1-4da6-9673-17e99f18f386.png)
Source code:
![image](https://user-images.githubusercontent.com/47894313/200907615-4ad0fa38-99de-4ba4-9bf0-3638bc55c726.png)

**Comment by sean-perkins** [comment]
@Vectorfield4 thanks for reporting this!
