### ISSUE TITLE
bug: missing arrow from popover in web

### ISSUE THREAD

**Issue by shivamsharmanps** [ionic-team/ionic-docs#2639]
### Describe the Bug

I was using ionic 5 then moved to 6 since then I am getting issues related to the arrow missing in mobile and sometimes it doesn't point from where the action triggered

### Expected Behavior

It should show an arrow and proper points like a tooltip with an arrow and adjustable according to the screen.

### Steps to Reproduce

https://ionicframework.com/docs/api/popover#usage
https://ionicframework.com/docs/api/popover#usage

### Screenshots

![image](https://user-images.githubusercontent.com/50568306/201187718-e486917b-e555-401a-a004-92ae24f0cd34.png)

### Operating System

Windows

### Browser

Chrome, Edge

### Version

6.3.4

**Comment by sean-perkins** [comment]
Hello @shivamsharmanps can you provide more information for this issue?

When the arrow is missing on mobile, is this an Android device or iOS? The screenshot image appears to be corrupted/invalid markdown. 

A reproduction of your problem would be helpful.
