### ISSUE TITLE
content: Vertical Grid Alignment page missing

### ISSUE THREAD

**Issue by lazmeister** [ionic-team/ionic-docs#2648]
### URL

https://ionicframework.com/docs/layout/grid#vertical-alignment

### Issue Description

Noticed this page is missing from the docs

**Comment by sean-perkins** [comment]
@lazmeister can you please elaborate? 

The page that you provided exists.

**Comment by lazmeister** [comment]
Sorry I should note how I got there. Using the search bar and search vertical alignment and then clicking on the result gets you the error.
![image](https://user-images.githubusercontent.com/3281599/202276082-8f77de79-d904-45a4-8d1f-fe60e7edd5c3.png)

![image](https://user-images.githubusercontent.com/3281599/202276164-cdbe9581-e19d-4c46-a186-691b7d1a2baf.png)

**Comment by sean-perkins** [comment]
Thank you for the quick follow-up! Looks like a redirect is not working as expected (only when coming from search). I'll discuss with the team 👍

**Comment by sean-perkins** [comment]
This should be resolved now 👍 we updated our algolia search index and the correct page will be returned in the search result.
