### ISSUE TITLE
Error: connect ECONNREFUSED in e2e test

### ISSUE THREAD

**Issue by adiandroo** [ionic-team/ionic-docs#2660]
Hello, I'm having trouble on e2e test on GitHub CI run on production, it gives me this error

    Failed: ErrorEvent {
      "error": [Error: connect ECONNREFUSED 127.0.0.1:39813],
      "message": "connect ECONNREFUSED 127.0.0.1:39813",
      "target": WebSocket {
        "_binaryType": "nodebuffer",
        "_bufferedAmount": 0,
        "_closeCode": 1006,
        "_closeFrameReceived": false,
        "_closeFrameSent": false,
        "_closeMessage": "",
        "_closeTimer": null,
        "_events": Object {
          "error": [Function onError],
          "open": [Function onOpen],
        },
        "_eventsCount": 2,
        "_extensions": Object {},
        "_isServer": false,
        "_maxListeners": undefined,
        "_protocol": "",
        "_readyState": 3,
        "_receiver": null,
        "_redirects": 0,
        "_req": null,
        "_sender": null,
        "_socket": null,
        "_url": "ws://127.0.0.1:39813/devtools/browser/a29532b7-3b31-46c2-add5-438c0b7b9e3e",
        Symbol(kCapture): false,
      },
      "type": "error",
    }

      2 |
      3 | describe('comp paywall', () => {
    > 4 |   it('renders', async () => {
        |   ^
      5 |     const page = await newE2EPage();
      6 |     await page.setContent('<comp-paywall></comp-paywall>');
      7 |

      at Env.it (node_modules/jest-jasmine2/build/jasmineAsyncInstall.js:95:24)
      at Suite.<anonymous> (src/components/comp-paywall/comp-paywall.e2e.ts:4:3)
      at Object.<anonymous> (src/components/comp-paywall/comp-paywall.e2e.ts:3:1)

My version on stencil is v2.5.2
My dependencies version
  "devDependencies": {
    "@stencil/postcss": "^2.0.0",
    "@types/autoprefixer": "^10.2.0",
    "@types/jest": "^26.0.23",
    "@types/puppeteer": "^5.4.3",
    "autoprefixer": "^10.2.5",
    "axios": "^1.0.0",
    "base-64": "^1.0.0",
    "jest": "^26.6.3",
    "jest-cli": "^26.6.3",
    "postcss-nested": "^5.0.5",
    "puppeteer": "^5.5.0",
    "stencil-inline-svg": "^1.0.1",
    "stencil-tailwind-plugin": "^0.5.0",
    "tailwindcss": "^2.1.2",
    "typescript": "^4.4.4"
  }

**Comment by sean-perkins** [comment]
Hello @adiandroo, I would recommend opening a post on the Ionic Forums or within the Discord channel to receive support related assistance. 

Closing as this is not an issue with the Ionic Docs.

**Comment by adiandroo** [comment]
Is there any link to Ionic forums or discord channel?

**Comment by sean-perkins** [comment]
@adiandroo the Discord invite link is available here: https://discord.com/invite/UPYYRhtyzp and the Ionic Forums is available here: https://forum.ionicframework.com/. I would recommend the forums for issues that require additional code for others to help. You can link users to that forum post in the Discord 👍
