### ISSUE TITLE
content: Document plugin usage for VueJS

### ISSUE THREAD

**Issue by evenstensberg** [ionic-team/ionic-docs#2678]
### URL

https://ionicframework.com/docs/native/native-audio

### Issue Description

It would be nice if you'd document how to use plugins using Ionic + VueJS

**Comment by liamdebeasi** [comment]
Hey there,

The Ionic Native plugins are now maintained by the community under the "awesome-cordova-plugins" name. I recommend filing an issue on https://github.com/danielsogl/awesome-cordova-plugins. Please see https://ionic.io/blog/a-new-chapter-for-ionic-native for more information.
