### ISSUE TITLE
bug: ion-searchbar, debounce example for Vue3 doesn't work

### ISSUE THREAD

**Issue by ulf1** [ionic-team/ionic-docs#2680]
### Describe the Bug

Code: https://ionicframework.com/docs/api/searchbar#debounce

Error
```
Failed to compile.

./src/components/PollImageEdit.vue
Module Error (from ./node_modules/eslint-loader/index.js):

/Users/uh/projects/ddkaa/src/components/PollImageEdit.vue
  5:5  error  Custom elements in iteration require 'v-bind:key' directives  vue/valid-v-for

✖ 1 problem (1 error, 0 warnings)
```

### Expected Behavior

no error msg

### Steps to Reproduce

1. Copy code and run it

**Comment by ulf1** [comment]
there must be a `:key` in the for loop

instead of
`<ion-item v-for="result in results">`

write
`<ion-item v-for="result in results" :key="result">`

**Comment by amandaejohnston** [comment]
Thank you for the issue. I'm unable to replicate the error when opening the example in Stackblitz (which you can do by clicking the ⚡ button at the top right of the demo). Could you provide a minimal Github repo that reproduces the problem?
