### ISSUE TITLE
v4 docs: Config documentation

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#270]
## Config

Add the Config docs from the following PR to the Guide section of the docs: https://github.com/ionic-team/ionic/pull/16523

https://github.com/ionic-team/ionic/blob/8206d5c337ca5a3835a39a36ce5f4e1ae90be108/core/src/utils/config.ts

Global angular usage:

```
IonicModule.forRoot({ mode: 'ios' }),
```

v3 reference: https://ionicframework.com/docs/v3/api/config/Config/

Related: https://github.com/ionic-team/ionic-docs/issues/253

<img width="988" alt="screen shot 2019-01-30 at 4 15 13 pm" src="https://user-images.githubusercontent.com/6577830/52066495-abb1b780-2546-11e9-8f2a-400f439a0354.png">

**Comment by liamdebeasi** [comment]
This has been resolved in 4c6b0fd

**Comment by brandyscarney** [comment]
https://ionicframework.com/docs/utilities/config
