### ISSUE TITLE
bug: Official Ionic documentation website partially works, timeouts 

### ISSUE THREAD

**Issue by Asac2142** [ionic-team/ionic-docs#2765]
### Describe the Bug

I'm someone who is new to Ionic Framework, and I am learning how to use it in order to create awesome web and mobile apps,
for this, I'm constantly accessing the official docs in order to study, learn more about the different Ionic components, but the vast majority of time, the site doesn't load the showcase of any component, it gets loading forever.

I have reset my internet connection, I have verified that my internet connection is stable, I am accessed other websites such as YouTube watching 4K videos with no issues but Ionic Docs website sometimes doesn't display the showcase of components, I've also have tried accessing Ionic official docs in an incognito window, both Firefox and Chrome... same result, sometimes the site is not interactive anymore, it just freezes 

### Expected Behavior

The Ionic documentation website should be available almost instantly like any other website such as Angular Material or PrimeNG, those sites also provides with documentation and showcase of components, and the time response is really fast.

### Steps to Reproduce

Open either Firefox or Chrome, access https://ionicframework.com/docs/api/button

### Screenshots

![image](https://user-images.githubusercontent.com/12599968/217589962-40256ae4-70b5-46fb-b658-170e65ad1ea9.png)

![image](https://user-images.githubusercontent.com/12599968/217590279-04611684-1cd8-4ab7-8b09-fb14c4e4b37e.png)

![image](https://user-images.githubusercontent.com/12599968/217590816-af55825d-bffe-49da-8ef0-aad50ec3c0ae.png)

Time out 524:
![image](https://user-images.githubusercontent.com/12599968/217592655-ca465830-9a39-4307-83df-b2859d81e1dc.png)

My internet speed:
![image](https://user-images.githubusercontent.com/12599968/217592084-fc57f2a1-49ab-4fc6-97b9-8f49fc2a32e1.png)

### Operating System

Linux Mint 20.3 Cinnamon

### Browser

Firefox and Chrome

### Version

Firefox 109.0.1 Chrome 110

**Comment by amandaejohnston** [comment]
Thank you for the issue. 524 is a Cloudflare-specific error code; I do remember seeing some slowdown on the docs site yesterday, but it seems to have been resolved now. It's possible there was some temporary server trouble slowing down the Ionic distribution scripts used by the live demos. Can you confirm whether you're still seeing this behavior today?

**Comment by Asac2142** [comment]
@amandaejohnston 
Thank you Amanda for your reply.

FYI, the slow response from the official docs, I've been detecting it from a couple of days now. 
Today seems to be fully responsive.

**Comment by amandaejohnston** [comment]
Looks like the site is still running smoothly today. I'm going to close this since it seems to have been a temporary server issue, but let us know if you spot it again and we can take another look.
