### ISSUE TITLE
content: Most of the required plugins in documentation is missing from documentation.

### ISSUE THREAD

**Issue by manikandan-bambus** [ionic-team/ionic-docs#2775]
### URL

https://ionicframework.com/docs/native

### Issue Description

I am searching for a plugin that checks if another app is available or not (App Availability plugin). But I am unable to see the plugin documentation via documentation page. Why?

**Comment by amandaejohnston** [comment]
Thank you for the issue. The list of available plugins can be found in the left sidebar, under the Plugins header. Does that help resolve your issue? If not, can you give more information on what you're looking for?

**Comment by manikandan-bambus** [comment]
Most of the plugins that's available in version 5 are not  available for version 6 
![Screenshot from 2023-02-16 21-10-58](https://user-images.githubusercontent.com/83752624/219415216-5242b292-9e2b-4f81-a28f-0b0b54fc06f2.png)
![Screenshot from 2023-02-16 21-11-13](https://user-images.githubusercontent.com/83752624/219415226-9c8dbc87-7cbf-4f06-a3c8-b086d2cd03ee.png)
Check these screenshots

**Comment by kensodemann** [comment]
@manikandan-bambus: The v6 list is the Capacitor plugins that we maintain. The v5 list is wrong, really, as we do not maintain those plugins. We never have.

For a more complete list of plugins available from the community along with docs, I suggest one of the following:

https://github.com/riderx/awesome-capacitor
https://github.com/danielsogl/awesome-cordova-plugins

It is best to prefer Capacitor over Cordova, especially as time goes on.

Hopefully, that helps.

**Comment by amandaejohnston** [comment]
It looks like this is resolved per the above, so I'm going to go ahead and close this out, but please let us know if you have any other questions.
