### ISSUE TITLE
bug: SOPHEAKMONY 

### ISSUE THREAD

**Issue by Sopheakmo** [ionic-team/ionic-docs#2794]
### Describe the Bug

[SOPHEAKMONY](url)

1. (SOPHEAKMONY 

- [x] សូមស្វាគមន៍
- [x] ចូល/ចុះឈ្មោះ

> ក្រុមហ៊ុនសុភ័ក្រមុន្នីឌីជីថលឯកជសូមស្វាគមន៍### **

> មើលភាពយន្ដ
``យុវនពេញសិទ្ធរបស់ SOPHEAKMONY
SOPHEAKMONY

1. @plengall #1772 

- [ ] 

### Expected Behavior

Ggcvh

### Steps to Reproduce

Ggbh

### Screenshots

Ggbhyyhhgh

**Comment by xnousnow** [comment]
What do you mean?
