### ISSUE TITLE
feat: Allow users to set their preferred JS framework

### ISSUE THREAD

**Issue by xnousnow** [ionic-team/ionic-docs#2798]
### Describe Problem

The language of the code snippets is all using Angular. As a Vue developer, It's hard to change the language of the snippet every time.

### Describe Preferred Solution

Allow users to set their preferred language.

**Comment by amandaejohnston** [comment]
Thank you for the feature request. I talked with the team and we agree that this would be a good feature to add to the docs.

**Comment by Quraian** [comment]
I came here to post an issue regarding this exact scenario. The implementation doesn't even have to be complicated I suggest to just persist the last selected framework and view all examples in the selected framework until the user selects another.

**Comment by amandaejohnston** [comment]
This has since been implemented -- both the framework and mode selection will sync across all demos on the page, and the selection will persist as you navigate the docs. Thanks again!
