### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by gauravsharma1111** [ionic-team/ionic-docs#2834]
### Describe the Bug

in the ion select component , the selected field  will be shown  with the radio button in the start 
the inner circle of the radio button is not properly alligned

### Expected Behavior

the radio button  UI should be properly centered 

### Steps to Reproduce

The css should be right  and it should be responsive 

### Screenshots

![Screenshot (57)](https://user-images.githubusercontent.com/38078337/225612446-4932c82b-715a-484e-a95e-4cca4b4e4601.png)

**Comment by amandaejohnston** [comment]
Thank you for the issue. I'm unable to reproduce this behavior. Looking at the Single Selection demo [here](https://ionicframework.com/docs/api/select#single-selection) in Chrome, the radio UI is centered (screenshot below). What browser (including the version) are you testing on?

![centered radio](https://i.gyazo.com/868ab9177b645838728498fa3d46b942.png)
