### ISSUE TITLE
content: missing documentation for ion-datetime-button change the displayed value

### ISSUE THREAD

**Issue by eranf91** [ionic-team/ionic-docs#2850]
### URL

https://ionicframework.com/docs/api/datetime-button

### Issue Description

The component has a default value as now, but there is no documentation for how set bind the value to a different value.

**Comment by amandaejohnston** [comment]
Thank you for the issue. The `ion-datetime-button` component links to an `ion-datetime`, so modifying the `value` of the datetime will reflect in the buttons. Here's an example: https://stackblitz.com/edit/angular-xg9ed1?file=src%2Fapp%2Fexample.component.html Does that resolve your concern?
