### ISSUE TITLE
content: v7 is marked as beta

### ISSUE THREAD

**Issue by captn3m0** [ionic-team/ionic-docs#2867]
### URL

https://ionicframework.com/docs/reference/support#framework-maintenance-and-support-status

### Issue Description

In addition to marking v7 as the "Active" release, it would be nice if clear dates could be provided for v6 at the least.

![image](https://user-images.githubusercontent.com/584253/228853173-0d559fdc-d960-4c3c-a440-7b452cd80b3f.png)

**Comment by amandaejohnston** [comment]
Updated in https://github.com/ionic-team/ionic-docs/pull/2868, thank you!
