### ISSUE TITLE
Missing plugins documentation for v7

### ISSUE THREAD

**Issue by co-dax** [ionic-team/ionic-docs#2878]
### URL

https://ionicframework.com/docs/native

### Issue Description

There is only documentation for Local Notifications while there are a log of plugins documented in the context of older version 

v5 [https://ionicframework.com/docs/v5/native](https://ionicframework.com/docs/v5/native)
v6 [https://ionicframework.com/docs/v6/native](https://ionicframework.com/docs/v6/native)

Also, I noticed there is less and less documentation for plugins with every new ionic version. Is that intentional?

Thanks!

**Comment by liamdebeasi** [comment]
This has been fixed via https://github.com/ionic-team/ionic-docs/pull/2903. Thanks for the report!
