### ISSUE TITLE
content: src/index.tsx doesn't exist in base project

### ISSUE THREAD

**Issue by dginovker** [ionic-team/ionic-docs#2911]
### URL

https://ionicframework.com/docs/react/your-first-app

### Issue Description

If you do

```bash
ionic start photo-gallery tabs --type=react --capacitor
cd photo-gallery
ls src/
```

You get

```
App.test.tsx  App.tsx  components  main.tsx  pages  setupTests.ts  theme  vite-env.d.ts
```

But the docs want you to edit `index.tsx`

**Comment by DKAMX** [comment]
This is interesting. I am using `ionic/react 7.0.3`. In my case, I have the `index.tsx` rather than `main.tsx`.  
I am still learning Ionic and are they pointing to the same thing? Maybe they should clarify it a bit more.

**Comment by jcesarmobile** [comment]
This was fixed here https://github.com/ionic-team/ionic-docs/pull/2917

`@ionic/cli` 7.x uses vite and includes `main.tsx`, if you are getting a `index.tsx` you are probably using an older CLI version which doesn't use the vite template but the older template that had the `index.tsx` (despite it's an old template it's also updated to use `@ionic/react` 7.x.
Try updating the `@ionic/cli` to latest version
