### ISSUE TITLE
bug: tab with id: "undefined" does not exist in Stackblitz

### ISSUE THREAD

**Issue by dmonmad** [ionic-team/ionic-docs#2912]
### Describe the Bug

I have been struggling implementing ion-tabs recently with Ionic 6.

When I tried the Stackblitz demo I get the same error I am getting in my local:
tab with id: "undefined" does not exist

It wont change the Tab and print that error to console. 

### Expected Behavior

Tab changes seamlessly.

### Steps to Reproduce

Go to [Ionic 6 Tabs with Router](https://ionicframework.com/docs/v6/api/tabs#usage-with-router)

Open it in Stackblitz

Select a tab

### Screenshots

![image](https://user-images.githubusercontent.com/47661159/231689282-73d386f7-d835-488e-9299-bbb31ab016e0.png)
![image](https://user-images.githubusercontent.com/47661159/231689298-7236cde6-905e-4508-9fd2-ffec22064de1.png)

### Operating System

Windows

### Browser

Chrome

### Version

112.0.5615.49

**Comment by thetaPC** [comment]
Thank you for the issue! We were able to reproduce this issue and are looking into it.

**Comment by bridgecode** [comment]
Any update?

**Comment by thetaPC** [comment]
Thank you for checking in. Unfortunately, [support for version 6 is no longer available](https://ionicframework.com/docs/reference/support#framework-maintenance-and-support-status), so we won’t be able to address the issue in that version. However, the issue does not exist in versions 7 and 8. We recommend [upgrading to the latest version](https://ionicframework.com/docs/updating/8-0) to resolve this problem.

**Comment by mikebrucker** [comment]
This still occurs in version 8. Only happens when tab button does not navigate to a url. It doesn't appear to have any negative affects however the error is still annoying and unneeded.

**Comment by thetaPC** [comment]
@mikebrucker Thank you for letting us know. However, I'm not able to reproduce this, please open a new issue with reproduction steps.
