### ISSUE TITLE
bug: "Create your Ionic App" App Wizard is Unable to create app

### ISSUE THREAD

**Issue by TheophileDesmedt** [ionic-team/ionic-docs#2977]
### Describe the Bug

When attempting to create an ionic app on the app wizard (https://ionicframework.com/start#basics), an error message appear: "Unable to create app, please ping us on Twitter and try the manual install below."

console:

405
Method Not Allowed

### Expected Behavior

Should go to the next step, account creation

### Steps to Reproduce

Go to https://ionicframework.com/start#basics and try to create an app. I tested with several choices, they all failed.

### Screenshots

![image](https://github.com/ionic-team/ionic-docs/assets/34781168/8b37a9e3-f778-4519-9c58-339e9571d384)

![image](https://github.com/ionic-team/ionic-docs/assets/34781168/26893df7-3ed7-4d22-a1b2-11c2d499ac5b)

![image](https://github.com/ionic-team/ionic-docs/assets/34781168/d87ef209-a8ae-40c1-ae63-577382fdb001)

![image](https://github.com/ionic-team/ionic-docs/assets/34781168/92f26cd4-9676-430b-a1c3-b283dda2398b)

![image](https://github.com/ionic-team/ionic-docs/assets/34781168/703f4763-a5b7-42eb-ac99-ab80f744f635)

![image](https://github.com/ionic-team/ionic-docs/assets/34781168/a3055b44-b807-464d-abec-6c3f78e45522)

### Operating System

Windows 11

### Browser

Firefox

### Version

113.0.2 (64 bits)

**Comment by amandaejohnston** [comment]
Looks like this has been resolved, so I'll go ahead and close this out. Thanks again!
