### ISSUE TITLE
content: Vue Infinite Scroll Uses Wrong Event

### ISSUE THREAD

**Issue by joshuahaertel** [ionic-team/ionic-docs#2978]
### URL

https://ionicframework.com/docs/api/infinite-scroll

### Issue Description

The documention for Vue uses `IonInfiniteCustomEvent`, however it appears the event is actually supposed to be `InfiniteScrollCustomEvent`.

**Comment by thetaPC** [comment]
Thank you for the issue! It's been resolved through PR ionic-team/ionic-docs#2995. It will be deployed to the site soon!
