### ISSUE TITLE
feat: Sync and store platform mode selection (md/ios).

### ISSUE THREAD

**Issue by twoco** [ionic-team/ionic-docs#2991]
Just a minor thing, but a bit annoying. You could sync/bind the platform mode to all demo playgrounds.
I mean the user selection between `ios` and `md`. I don't want to click to all again and again. Just one time to md and all blocks changes. This can also be stored in e.g. local storage. What do you think?

![blah](https://github.com/ionic-team/ionic-docs/assets/53160891/033f95ff-5378-4d3b-a619-343ad574a2f4) 
[example page](https://ionicframework.com/docs/api/button)

**Comment by mapsandapps** [comment]
Hi, thanks for the feature request! I agree that this would be a good feature to add. We will consider adding this with #2798 (a similar feature request for storing the platform.)

**Comment by amandaejohnston** [comment]
This has since been implemented -- both the framework and mode selection will sync across all demos on the page, and the selection will persist as you navigate the docs. Thanks again!
