### ISSUE TITLE
ionic push and pop pages

### ISSUE THREAD

**Issue by akoundacmedia** [ionic-team/ionic-docs#3019]
maintenant la version d ionic n accepte plus les push on me dit propriete push does not exist dans hopepages et d apres les recherche je peut pas faire this.navctrl.push(detailspages)

**Comment by amandaejohnston** [comment]
Thank you for the issue. Can you give more details on what you are trying to do? A minimal Github repo showing the problem would also help.

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and ensure the template is fully filled out. Thank you!
