### ISSUE TITLE
content: card style models on android

### ISSUE THREAD

**Issue by ngmiduc** [ionic-team/ionic-docs#3022]
### URL

https://ionicframework.com/docs/api/modal#card-modal

### Issue Description

I noticed that the card style models are actually also working on Android devices.

Maybe this note needs to be updated?

`The card display style is only available on iOS.`

**Comment by amandaejohnston** [comment]
Thank you for the issue. While `ion-modal` functions on either mode whether you have card modal styling turned on or not, the card style itself only shows on `ios` mode.

For example, [here is an app](https://stackblitz.com/edit/angular-8wvqv9?file=src%2Fapp%2Fapp.module.ts,src%2Fapp%2Fexample.component.html) that's been forced to `md` mode. Note that the modal displays the same even if you remove the `presentingElement` prop from it. However, if you change the mode to `ios` on line 16 of `app.module.ts`, the modal will display in card style with `presentingElement` set, and normal style without it.

You can force the card style to be available on an Android device by setting `mode="ios"` on the `ion-modal`, or globally forcing `ios` mode as in the example app above.

Does this clear things up for you?

**Comment by ngmiduc** [comment]
Ah ok! I understand now!
