### ISSUE TITLE
feat: open ion-picker programically when mounted

### ISSUE THREAD

**Issue by acarlstein** [ionic-team/ionic-docs#3023]
### Describe Problem

Working with Ionic 7+ and Vue 3.

The examples available for ion-picker use an ion-button to display the ion-picker.

I wish to open the ion-picker when the page is mounted, so I can turn it into a plugin.

 `isOpen` doesn't help to open it programically.

Have a nice day.

### Describe Preferred Solution

When the ion-picker has a reference, then be able to call `open()` method to open it.

**Comment by amandaejohnston** [comment]
Thank you for the request. This would involve getting a reference to the `ion-picker` element in the manner recommended by the JS framework you are using, so we wouldn't be showing any additional Ionic behavior. Here's an example showing this in Angular using `ViewChild`: https://stackblitz.com/edit/angular-mtr9eu?file=src%2Fapp%2Fexample.component.html,src%2Fapp%2Fexample.component.ts

You can find the available methods for any component under the Methods section near the bottom of the page: https://ionicframework.com/docs/api/picker#methods

Does this help clear things up for you?
