### ISSUE TITLE
bug: The latest Japanese documentation is incorrectly linked to v6. 

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-docs#3050]
### Describe the Bug

We expect the latest (v7) Japanese documentation to be reflected at https://ionicframework.com/docs/ja. But in fact it is linked to https://ionicframework.com/docs/ja/v6/.

### Expected Behavior

Deployment results in correct linking to https://ionicframework.com/docs/ja.

### Steps to Reproduce

check link:

- https://ionicframework.com/docs/ja
- https://ionicframework.com/docs/ja/v6/

### Additional Information

related pull request:

https://github.com/ionic-team/ionic-docs/pull/2884
https://github.com/ionic-team/ionic-docs/pull/2889

If this seems difficult, I would suggest that https://ionicframework.jp/docs/ be the original as well as the Capacitor and Stencil documentation.

**Comment by rdlabo** [comment]
https://github.com/ionic-team/ionic-docs/pull/2889 's error may be occurred from https://github.com/ionic-team/ionic-docs/blob/main/scripts/i18n.sh#L8

**Comment by liamdebeasi** [comment]
Thanks! This is fixed in https://github.com/ionic-team/ionic-docs/pull/3057.

https://ionicframework.com/docs/ja
