### ISSUE TITLE
Demo for UI components is not showing

### ISSUE THREAD

**Issue by mohammedhamza1** [ionic-team/ionic-docs#3059]
### URL

https://ionicframework.com/docs/v6/api/range

### Issue Description

Demo for UI components is not showing

**Comment by mapsandapps** [comment]
Hi, thank you for submitting an issue! All the demos on this page are displaying correctly for me. Could you please provide some more information:

* Your browser & version
* Is it only certain demos that aren't displaying for you, or all the demos on the page? If it's only some, which ones?
* Are other pages in the docs working correctly?

Thank you.

**Comment by mohammedhamza1** [comment]
All the Demos
<img width="779" alt="image" src="https://github.com/ionic-team/ionic-docs/assets/24924500/9d19e0a1-9778-451f-a92c-a331ea5ed29e">

Browser: Chrome for MacOS, Version 115.0.5790.102

**Comment by amandaejohnston** [comment]
I'm also unable to reproduce this, using Mac Chrome version 115.0.5790.114. Could you check again and see if the demos are still down? It's possible this was a temporary outage.
