### ISSUE TITLE
ion-input color field not working

### ISSUE THREAD

**Issue by gerarrd** [ionic-team/ionic-docs#3062]
### Describe the Bug

In the documents found here(https://ionicframework.com/docs/api/input), the colors of the label, cursor, and highlight of an input field should reflect the specified color. But it is not working in the documentation to begin with. It is not also working in code.

### Expected Behavior

ion-input should change the colors of the cursor, label, and highlight depending on the  color specified

### Steps to Reproduce

Create an ion-input tag and set color to "danger"

### Screenshots

![image](https://github.com/ionic-team/ionic-docs/assets/3413329/7bbb985f-8ba9-4d8d-93cd-3ccc353c5598)

### Operating System

Windows

### Browser

Firefox

**Comment by amandaejohnston** [comment]
Thank you for the report. There may be some confusion over what the `color` property does. On iOS mode, only the caret/cursor color changes. On MD mode, both the cursor color and the color of the highlight at the bottom of the input will change.

In both modes, the colors of the input text and label do _not_ change. (This is different in v6; we changed it in v7 to better match native behavior.)

Things are working on Windows Firefox on my end (screencast below). Does this help clear things up?

https://github.com/ionic-team/ionic-docs/assets/90629384/b57ea34b-3c71-48b9-b709-980fd47577b4

**Comment by gerarrd** [comment]
Oh, I wasn't reading properly. I'm so sorry about that. Thank you for the response.
