### ISSUE TITLE
bug: 

### ISSUE THREAD

**Issue by akilisosa** [ionic-team/ionic-docs#3071]
### Describe the Bug

The select option in the typeahead component does not show, because the text is in-between the checkbox. 

### Expected Behavior

It should show the text to the right of the text box

### Steps to Reproduce

go here: 
https://ionicframework.com/docs/api/select

scroll down to the type-a-head part and copy and paste that part, enter in some dummy values, then run the program

### Operating System

windows

### Browser

brave browser

### Version

1.56.20, chromium" 115.0.5790.171

### Additional Information

will try to raise merge request you just need to move the text to the right side of the checkbox tags

**Comment by amandaejohnston** [comment]
Thank you for the issue. I'm unable to replicate the described behavior using the demo. Could you post a Stackblitz link or Github repo with the code you are using? It sounds like you have modified the demo code somewhat.

**Comment by amandaejohnston** [comment]
This issue is being closed due to insufficient reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and include a code reproduction. Thank you!
