### ISSUE TITLE
Toasts not working

### ISSUE THREAD

**Issue by bitflower** [ionic-team/ionic-docs#31]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/components#toast

**Current behavior:**
Clicking on any of the 5 toast variations brings up error:
<img width="842" alt="bildschirmfoto 2018-07-19 um 14 42 40" src="https://user-images.githubusercontent.com/6666636/42943107-35815710-8b62-11e8-88aa-23e685bd7a5d.png">

**Expected behavior:**
Toasts work in docs.

**Comment by brandyscarney** [comment]
Thank you for the issue! Fixed this in https://github.com/ionic-team/component-preview/commit/8deb5e298402d73cd15ee34273f539cbd6d5eeba
