### ISSUE TITLE
content: ion-backdrop basic usage demo should have tinted backdrop

### ISSUE THREAD

**Issue by ethanharlig** [ionic-team/ionic-docs#3110]
### Describe the Bug

The "basic usage" example of the [ion-backdrop](https://ionicframework.com/docs/api/backdrop) page isn't functional. Clicking on it does nothing. 

### Expected Behavior

The example should demonstrate the backdrop functionality.

### Steps to Reproduce

1. Navigate to [ion-backdrop docs page](https://ionicframework.com/docs/api/backdrop)
2. Go to "Basic Usage" section
3. Attempt to interact with the example

### Screenshots

https://github.com/ionic-team/ionic-docs/assets/11605206/4f5131c0-30d1-402e-aeca-a37c5e0453e1

### Browser

Firefox 117.0

**Comment by amandaejohnston** [comment]
Thank you for the issue. As described in the paragraph above the demo, the behavior you're describing actually _is_ the backdrop functionality -- it prevents clicking or tapping on any of the elements underneath it. Does that help answer your question?

**Comment by ethanharlig** [comment]
I did see that but I guess the example was then confusing to me since it doesn't feel like it's truly demonstrating the backdrop functionality. The following example showing a clickable overlay paired with the backdrop seems like a much more common use case and perhaps should be used as the primary example.

**Comment by amandaejohnston** [comment]
Would it help if the backdrop was tinted to better mimic the functionality it'd have in an overlay? The idea behind the demo is to show the backdrop's functionality by itself, without implying that it necessarily needs to be used with any other components.

**Comment by ethanharlig** [comment]
Personally that'd be more clear to me. I understand the desire to show the basic usage without any other components, I just think for this component in particular it may make sense to show with a tinted backdrop.

**Comment by amandaejohnston** [comment]
I've added a tint to the backdrop in https://github.com/ionic-team/ionic-docs/pull/3200. Thanks again!
