### ISSUE TITLE
bug: ion-textarea custom style not working for help or count

### ISSUE THREAD

**Issue by StefaniToto** [ionic-team/ionic-docs#3112]
### Describe the Bug

Based on ionic documentation we can access and change the attributes of count and error . 
https://ionicframework.com/docs/api/textarea

Below is a demo to change the size and color.

https://stackblitz.com/edit/angular-dhulrr-hexdmn?file=src%2Fapp%2Fexample.component.css,src%2Fapp%2Fexample.component.html

### Expected Behavior

`ion-textarea.custom {
  --background: #373737;
  --color: #fff;
  --padding-end: 10px;
  --padding-start: 10px;
  --placeholder-color: #ddd;
  --placeholder-opacity: 0.8;
}

ion-textarea.custom .helper-text,
ion-textarea.custom .counter {
  color: red !important;
  font-size: 24px !important;
}`

Is expected to change the the style of helper and counter

### Steps to Reproduce

Latest stackblitz from ionic documentation

### Screenshots

![image](https://github.com/ionic-team/ionic-docs/assets/32243109/7a8691c1-6b70-42a0-a0c9-4c87b3271913)

### Operating System

windows

### Browser

firefox, chrome

**Comment by mapsandapps** [comment]
Hi, thank you for the report! I can see that this example in the docs is not working in Angular. Angular encapsulation is preventing the `helper-text` class from getting the styles applied to it. You can fix this in the Stackblitz by moving 

```
ion-textarea.custom .helper-text,
ion-textarea.custom .counter {
  color: red !important;
  font-size: 24px !important;
}
```

into the global.css file.

We need to update the docs to address this and also change the specificity to remove the requirement of `!important`.

**Comment by liamdebeasi** [comment]
Thanks for reporting this! This is fixed in https://github.com/ionic-team/ionic-docs/pull/3199
