### ISSUE TITLE
Color Generator is not working

### ISSUE THREAD

**Issue by victorwpbastos** [ionic-team/ionic-docs#318]
The color generator tool is not working in Ionic 4 Production Docs. Beta Docs is still working btw.

Beta Docs
![image](https://user-images.githubusercontent.com/1017515/51632563-c5e00a00-1f36-11e9-88f9-c32643699997.png)

Production Docs
![image](https://user-images.githubusercontent.com/1017515/51632528-acd75900-1f36-11e9-831c-5dfb9bf3163a.png)

**Comment by brandyscarney** [comment]
It's live! https://ionicframework.com/docs/theming/color-generator

You may need to do a hard refresh to see it.

**Comment by lfbanos** [comment]
Still not working

**Comment by brandyscarney** [comment]
Where are you seeing it not working? It is working in Chrome fine:

![Screen Shot 2021-01-25 at 2 40 55 PM](https://user-images.githubusercontent.com/6577830/105756976-56cd8f80-5f1b-11eb-983a-57620f11fba8.png)

**Comment by codestorms37** [comment]
I just tested it:
![Screenshot 2021-01-25 162701](https://user-images.githubusercontent.com/46337583/105774002-5d173800-5f2a-11eb-9ce2-53753a703e65.png)

**Comment by codestorms37** [comment]
Also the CSS Variables didn't change:

![Screenshot 2021-01-25 162937](https://user-images.githubusercontent.com/46337583/105774206-a5cef100-5f2a-11eb-8132-f0322356c60a.png)

**Comment by codestorms37** [comment]
I just tested it:

- The demo app didn't change
- The Primary-shade and Primary-tint didn't change
- CSS variables didn´t change

I'm using Chrome

Regards
![Screenshot 2021-01-25 163233](https://user-images.githubusercontent.com/46337583/105774770-576e2200-5f2b-11eb-9128-57897bd1270f.png)

**Comment by brandyscarney** [comment]
@codestorms37 Unfortunately I cannot reproduce:

<img src="http://g.recordit.co/5JjLBlirf7.gif">

I have tested using the following:
- Chrome Version 87.0.4280.141 (Official Build) (x86_64)
- Chrome Version 88.0.4324.96 (Official Build) (x86_64)
- Safari Version 14.0.1 (15610.2.11.51.10, 15610)

Could you open the console and see if there are any errors?
