### ISSUE TITLE
content: Google Play Store deployment

### ISSUE THREAD

**Issue by Berkmann18** [ionic-team/ionic-docs#3208]
### URL

https://ionic.io/docs/appflow/destinations/google

### Issue Description

The API access section in the Google Play Console isn't there anymore, so from the moment the docs (about automating deployments to the Play Store) mention it to set up a service account, it can't be done because users will see
![API access page gone](https://github.com/ionic-team/ionic-docs/assets/8260834/29e1f29b-8f97-4f2d-a50c-1dde3259e430) and won't be able to move forward.
 
And I've not seen a way to get the automated deployments from Appflow to Google Play.

**Comment by amandaejohnston** [comment]
Thanks for the report! The Appflow docs repo is private so I can't link to the PR, but this has been resolved 👍

**Comment by Berkmann18** [comment]
Okay, thank you.
