### ISSUE TITLE
content: Swiperjs event names should be prefixed with "swiper" in Angular migration guide

### ISSUE THREAD

**Issue by karocksjoelee** [ionic-team/ionic-docs#3306]
### URL

https://ionicframework.com/docs/angular/slides#events

### Issue Description

The table : Below is a full list of method changes when going from ion-slides to Swiper Element: 
is not corrrect , according to [Swiperjs Events](https://swiperjs.com/element#events), it should have prefix of `swiper`

#All [Swiper events](https://swiperjs.com/swiper-api#events) are available as native DOM events but with lowercase names and swiper prefix (configurable via events-prefix parameter). E.g. slideChange becomes swiperslidechange.

**Comment by amandaejohnston** [comment]
Thank you for the issue. I confirmed that the prefixed events should indeed be used even in an Angular app (i.e. without using `addEventListener` directly), at least on the latest version of Swiper. We'll want to update both the Angular docs page, and the migration example app linked at the bottom of the page: https://github.com/ionic-team/slides-migration-samples/tree/swiper/angular
