### ISSUE TITLE
docs: item does not account for new text wrapping behavior

### ISSUE THREAD

**Issue by lincolnthree** [ionic-team/ionic-docs#3313]
### Prerequisites

- [X] I have read the [Contributing Guidelines](https://github.com/ionic-team/ionic-framework/blob/main/.github/CONTRIBUTING.md#creating-an-issue).
- [X] I agree to follow the [Code of Conduct](https://ionicframework.com/code-of-conduct).
- [X] I have searched for [existing issues](https://github.com/ionic-team/ionic-framework/issues) that already report this problem, without success.

### Ionic Framework Version

v7.x

### Current Behavior

![Screenshot 2023-12-11 at 2 35 23 PM](https://github.com/ionic-team/ionic-framework/assets/362329/34678656-4dae-4730-9618-bc72f30b3e43)

Ellipsis is no longer working as of Ionic 7.6.0

### Expected Behavior

Text should wrap/ellipsis when labels get too long in `ion-item` components unless `ion-text-wrap` styles are applied.

### Steps to Reproduce

Visit the documentation for `ion-item`.  See the error in the basic usage section:

https://ionicframework.com/docs/api/item#basic-usage

### Code Reproduction URL

https://ionicframework.com/docs/api/item#basic-usage

### Ionic Info

Ionic:

   Ionic CLI                     : 7.1.1 (/Users/lincoln/.nvm/versions/node/v16.14.0/lib/node_modules/@ionic/cli)
   Ionic Framework               : @ionic/angular 7.6.0
   @angular-devkit/build-angular : 17.0.6
   @angular-devkit/schematics    : 17.0.6
   @angular/cli                  : 17.0.6
   @ionic/angular-toolkit        : 10.0.0

**Comment by liamdebeasi** [comment]
You can use `.ion-text-nowrap` to prevent wrapping. However, I recommend allowing wrapping as truncating often times makes that content inaccessible to users.

**Comment by liamdebeasi** [comment]
> This also causes breaking block-level element wrapping to occur if you try to actually remove text-wrapping manually:

The browser is working correctly here. `pre` cause lines to only be broken at newline characters and `<br />` elements. Your code makes it so the text in `ion-label` does not wrap. However, the `ion-item` still allows wrapping. If the `ion-item` did not wrap, then the `ion-button` would be pushed out of view. As a result, the button wraps to the next line so it is still visible.

**Comment by lincolnthree** [comment]
Ideally it would be possible, but because virtual-scrolling makes variable-height items difficult (or impossible, without a good library available), we have to truncate in any place where VS is used.

Or when a side-panel is opened and we don't want to cause a ton of layout shift:

![image](https://github.com/ionic-team/ionic-docs/assets/362329/5d6939c2-801e-4c5e-8033-3e69ee8bcfe9)

(layout needs to stay where it is when side panel is opened...)

![image](https://github.com/ionic-team/ionic-docs/assets/362329/f583f177-4d7d-4bb8-8582-7ae9eb1cae9f)

**Comment by liamdebeasi** [comment]
> Ideally it would be possible, but because virtual-scrolling makes variable-height items difficult (or impossible, without a good library available), we have to truncate in any place where VS is used.

Ah I see, that's too bad. In that case I'd recommend setting `.ion-text-nowrap` on `ion-item`. Here is a demo: https://ionic-docs-git-item-wrapping-ionic1.vercel.app/docs/api/item#basic-usage

**Comment by lincolnthree** [comment]
Thanks, this is helpful.

One interesting thing... With `ion-text-nowrap` the ellipsis functionality returns, but the block-level elements in the item still break to the next line:

![image](https://github.com/ionic-team/ionic-docs/assets/362329/54365eaa-b1dc-446a-b334-e936dc0c9cfd)

If I set the width of the label to 0px, it works:

![image](https://github.com/ionic-team/ionic-docs/assets/362329/f1e78910-13c5-419f-89e1-46e45ab6b770)

**Comment by liamdebeasi** [comment]
Sorry, I'm not seeing the difference in behavior. Do you have a minimal repro?

**Comment by lincolnthree** [comment]
https://stackblitz.com/edit/angular-zx6jyk?file=src%2Fapp%2Fexample.component.html

```
<ion-item>
  <ion-label class="ion-text-nowrap">
    Multi-line text that should ellipsis when it is too long to fit on one line. Lorem ipsum dolor sit amet,
    consectetur adipiscing elit.
  </ion-label>
  <ion-label slot=end>Foo</ion-label>
</ion-item>
```

**Comment by lincolnthree** [comment]
![Screenshot 2023-12-11 at 3 13 56 PM](https://github.com/ionic-team/ionic-docs/assets/362329/38fe10b0-3146-4abd-834e-43e0ae924f16)

**Comment by lincolnthree** [comment]
Sorry, easier to see with a button:
![Screenshot 2023-12-11 at 3 15 06 PM](https://github.com/ionic-team/ionic-docs/assets/362329/3465883d-a4d2-47f8-9870-5da9bb1bb3ac)

**Comment by lincolnthree** [comment]
@liamdebeasi Did you see my reproduction of the layout braking issue? https://github.com/ionic-team/ionic-docs/issues/3313#issuecomment-1850811864

**Comment by liamdebeasi** [comment]
Yes I did. I am discussing with the team regarding this.

Sorry, the issue got closed automatically when https://github.com/ionic-team/ionic-docs/pull/3314 merged since it was linked in the PR description.

**Comment by lincolnthree** [comment]
> Yes I did. I am discussing with the team regarding this.
> 
> Sorry, the issue got closed automatically when #3314 merged since it was linked in the PR description.

Thanks, gotcha! No worries. I just wanted to make sure it didn't get lost. Looking forward to hearing what you figure out.

**Comment by liamdebeasi** [comment]
I spoke with the team, and the `width: 0` usage you set on `ion-label` is correct. The relevant change that caused this difference is in https://github.com/ionic-team/ionic-framework/blob/fc88613fefa019a3b695a2c6e10c85cd3ce79ae8/core/src/components/item/item.scss#L444.

We changed this from `flex: 1 0 0` to `flex: 1 0 auto`. The last value, the `flex-basis`, defines the initial main size of the flex item. Previously, the initial main size was `0`, and now it's `auto`. If we did not make this change then using multiple text elements in `ion-item` would cause some of the text to collapse to 0 (such as a label with a note).

The reason why your `width: 0` CSS works is it effectively makes the `flex-basis` 0 again, since the `auto` keyword causes `flex-basis` to use the value of `width`.

**Comment by lincolnthree** [comment]
Thanks @liamdebeasi -- What is the best way to undo this change in our CSS? Even with `width: 0` we are getting all kinds of layout inconsistencies on pretty much every page of the app. Even our login form. It will mean a full style review and changes to every component and screen.

Absent that, we may need to fork `ion-item` and maintain our own version of it. This is a very impactful and concerning change.

**Comment by liamdebeasi** [comment]
Just a heads up, the team is having discussions into revising part of the text wrapping behavior. In particular, we are considering not having the end/start slot content wrap to the next line. In other words, only the text in the default slot would wrap within its own container.

We are having this discussion based on some new information we've found related to how iOS handles wrapping. We're tracking this in https://github.com/ionic-team/ionic-framework/issues/28769. If we end up making this change this should address the issue you noted in https://github.com/ionic-team/ionic-docs/issues/3313#issuecomment-1850817066.

**Comment by lincolnthree** [comment]
Thanks Liam. Glad to hear further discussion is happening. To be honest, this issue has blocked us from updating to the latest Ionic versions. Even after auditing every screen, we can't come up with a global ruleset to fix the issues caused by this change. It's forcing us to add custom styles to every element. We're very close to forking `ion-item` entirely.
