### ISSUE TITLE
Ionic v7 migration guide breaking changes missing

### ISSUE THREAD

**Issue by jmonloop** [ionic-team/ionic-docs#3383]
### URL

https://ionicframework.com/docs/updating/7-0#getting-started

### Issue Description

Hello, 
I have upgraded from
 `"@ionic/angular": "^6.7.5"`
to 
`"@ionic/angular": "^7.6.3"`

I followed both the [main API changes guide](https://ionicframework.com/docs/updating/7-0) and the [specific breaking changes guide](https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#version-7x)

However my application is broken on places that they shouldn't according to the documentation.

For example`inner-item` component.
I've checked the official breaking changes and they shouldn't affect to anything in my app. (Only some paddings and font-size)
However in several places where I use this component the styles are messed up.

I inspected on deep and I found out that its shadow-root node has an element with `item-inner` class. When I set its `height:100%` it works as before. Maybe I'm missing something related with a parent element but the only change I made was upgrading Ionic and I'm okay with the documentation guide.

Isn't there a more detailed migration guide?
Thanks in advance

**Comment by amandaejohnston** [comment]
This issue is being closed due to lack of a reproduction. If this is still a problem in the latest version of Ionic, please open a new issue and include a link to a Stackblitz app or Github repo showcasing the problem. Thank you!
