### ISSUE TITLE
Ionic generate: include more information on types

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#343]
We had a user request to include more information on the different types that generate has here:

https://ionicframework.com/docs/cli/commands/generate

Original forum post: https://forum.ionicframework.com/t/announcing-ionic-4-neutronium/153961/3

**Comment by dwieeb** [comment]
This information is available in the command line:

<img width="464" alt="image" src="https://user-images.githubusercontent.com/236501/51709201-65f76b00-1feb-11e9-9fb5-3bd8fe42f392.png">

I am hesitant to include the plethora of options in the help documentation for `ionic generate`. Perhaps this is better suited as a tutorial that documents common options.

**Comment by brandyscarney** [comment]
Hmm we have the tutorial here: https://ionicframework.com/docs/building/scaffolding

Should we update this section?
