### ISSUE TITLE
bug: spawn adb ENOENT

### ISSUE THREAD

**Issue by Bader-Idris** [ionic-team/ionic-docs#3436]
### Describe the Bug

When attempting to run the project in Android/iOS mode from the Ionic extension icon, it throws this error:

```sh
spawn adb ENOENT
```

I went to Settings -> Advanced -> Ionic ADB Path and set the project's path, but it didn't resolve the issue. I tried this on the latest Ubuntu OS. Additionally, I created an empty folder for the project on an external hard drive and selected the mounted shortcut as /e/ionicProject. Therefore, one of these reasons could be the cause of the error.

**Comment by liamdebeasi** [comment]
Hey there! We use this repo to track bugs or feature requests for our documentation site. If you need help debugging a problem, I recommend posting on the [Ionic Forum](http://forum.ionicframework.com) or our [Discord](https://discord.com/invite/UPYYRhtyzp).
