### ISSUE TITLE
content: input theme colors

### ISSUE THREAD

**Issue by shawnnolanjr** [ionic-team/ionic-docs#3463]
### URL

https://ionicframework.com/docs/api/input#theming

### Issue Description

Is this supposed to have different color schematics? It's working locally, but the docs example doesn't seem to be updating.

<img width="771" alt="Screenshot 2024-02-20 at 12 22 13 PM" src="https://github.com/ionic-team/ionic-docs/assets/8684308/3737f592-b843-4859-a80a-2366e9de873c">

**Comment by amandaejohnston** [comment]
This isn't the first time I've seen someone get confused about this, so I'm going to put up a PR to clarify the docs 👀

**Comment by amandaejohnston** [comment]
I'm closing this as "not planned" because the demo is working as intended, but I've added some language in https://github.com/ionic-team/ionic-docs/pull/3471 that should hopefully clarify things for everyone going forward. Thank you for the report!

**Comment by shawnnolanjr** [comment]
> I'm closing this as "not planned" because the demo is working as intended, but I've added some language in #3471 that should hopefully clarify things for everyone going forward. Thank you for the report!

cool thanks.
