### ISSUE TITLE
menu-controller docs breaks docs website

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#349]
https://github.com/ionic-team/ionic/blob/master/core/src/components/menu-controller/menu-controller.ts#L195

This docs has a triple escaped snippet in it, which breaks the generated docs:

![image](https://user-images.githubusercontent.com/1038062/51709405-2f871380-201e-11e9-89ba-6aeb11add21b.png)

And even githubs markdown renderer:

https://github.com/ionic-team/ionic/tree/master/core/src/components/menu-controller

![image](https://user-images.githubusercontent.com/1038062/51709543-960c3180-201e-11e9-835f-a53d356aafa0.png)

**Comment by brandyscarney** [comment]
Thanks for the issue! This is a problem with Stencil's generator, please follow on this issue: https://github.com/ionic-team/stencil/issues/1314

**Comment by brandyscarney** [comment]
@rtpHarry No I appreciate it! I was just linking the two together since it's blocked. 🙂

**Comment by brandyscarney** [comment]
Just to let you know this issue will be closed with this PR: https://github.com/ionic-team/ionic/pull/18075

However, it is still an issue in our docs generation so it could pop up again if anyone adds code block usage to our documentation before https://github.com/ionic-team/stencil/issues/1314 is fixed. 🙂
