### ISSUE TITLE
bug: search is down

### ISSUE THREAD

**Issue by aparajita** [ionic-team/ionic-docs#3494]
### Describe the Bug

Search returns no results.

### Expected Behavior

Some results.

### Steps to Reproduce

1. Click in the search field.
2. Enter "ion". Nothing appears.

### Operating System

macOS 14.2.1

### Browser

Brave, Safari

### Version

Brave 1.63.165 Chromium: 122.0.6261.94, Safari 17.2.1

### Additional Information

Not seeing any Javascript or network errors in devtools.

**Comment by liamdebeasi** [comment]
Thanks! With the release of the Ionic 8 docs we versioned the v7 docs. As a result, we need Algolia to re-crawl that part of the site. Once that's done the search results should be fixed.

**Comment by aparajita** [comment]
I figured it had something to do with the move to v8.

**Comment by liamdebeasi** [comment]
This should be fixed now. Thanks again for letting us know!
