### ISSUE TITLE
(New Docs) ionic-native-google-maps not present in documentation

### ISSUE THREAD

**Issue by francovp** [ionic-team/ionic-docs#351]
**Current behavior:**
The ionic-native-google-maps documentation is not present in the sidebar

Is this plugin not considered for this released or you only forgot to include it?

![image](https://user-images.githubusercontent.com/2883350/51703625-9c39e800-1ff5-11e9-8230-3a5e3e27ad88.png)

**Comment by perrygovier** [comment]
Some history on the issue
https://github.com/ionic-team/ionic-native/issues/2658

**Comment by wf9a5m75** [comment]
@perrygovier @brandyscarney  ping

**Comment by camwiegert** [comment]
6cef8165c102697db8a37db60020df07542fe4ad

**Comment by wf9a5m75** [comment]
Thank you, @camwiegert !
