### ISSUE TITLE
Ionic 4 document web site not view

### ISSUE THREAD

**Issue by mesutseyhan** [ionic-team/ionic-docs#352]
Hello,

When I enter the https://ionicframework.com/docs/ 5 website, only the top title appears. Documents appear when loading the page, but it disappears when loading is finished. Side component and content are not visible. I’m using Chrome. (Other browsers have similar problems with Opera, Firefox, Edge). A similar problem exists on the website https://stenciljs.com/.
![ionic-docs](https://user-images.githubusercontent.com/6901279/51727267-4a887080-207c-11e9-9585-d7e919e4948c.png)

**Comment by camwiegert** [comment]
@mesutseyhan Thanks for the report! I believe this was determined to be a problem in stencil-router and was addressed in ionic-team/stencil-router@8b474181b5f73e5860ff5e698b32846cb68f173e

**Comment by mesutseyhan** [comment]
@camwiegert No problem now. working 
👍😁
