### ISSUE TITLE
bug: running the example on your first Ionic React app does not run

### ISSUE THREAD

**Issue by previnWong** [ionic-team/ionic-docs#3526]
### Describe the Bug

On this following page
https://ionicframework.com/docs/react/your-first-app

if you follow the steps and then try ```ionic serve```,  you get a page break.  Error is in the the IonRouter and IonRouterOutlet.
```
Type '{ children: Element[]; }' has no properties in common with type 'IntrinsicAttributes & IntrinsicClassAttributes<IonReactRouter> & Readonly<IonReactRouterProps>'.ts(2559)
```
and if you add ```children?: ReactNode | undefined``` to the interface, then it breaks at RouterOutlet
```
TS2739: Type '{ children: Element[]; }' is missing the following properties from type 'Pick<IonRouterOutlet & { basePath?: string | undefined; ref?: Ref<any> | undefined; ionPage?: boolean | undefined; } & IonicReactProps & Omit<...>, keyof IonicReactProps | ... 253 more ... | "ionPage">': onPointerEnterCapture, onPointerLeaveCapture
```
Not sure how to fix to get the app running.

### Expected Behavior

Should load the app with 3 tabs

### Steps to Reproduce

ionic start photo-gallery tabs --type=react --capacitor
cd photo-gallery
ionic serve

### Operating System

Mac

### Browser

Chrome

### Version

122.0.6261.113

### Additional Information

Ionic is at 7 and React is at 18

**Comment by liamdebeasi** [comment]
This should be fixed in Ionic 7.8.1. See https://github.com/ionic-team/ionic-framework/issues/29178 for more info.
