### ISSUE TITLE
ion-segment, ionChange should explain it is not fired when value changed programmatically

### ISSUE THREAD

**Issue by ChrisHSandN** [ionic-team/ionic-docs#3588]
### URL

https://ionicframework.com/docs/api/segment#events

### Issue Description

Suggest that the following is added to the end of the `ionChange` description:

> ionChange is not fired when the value is changed programmatically.

Would also be useful on:
* https://ionicframework.com/docs/api/radio-group#events

It is already stated on:
* https://ionicframework.com/docs/api/range#events
* https://ionicframework.com/docs/api/checkbox#events
* https://ionicframework.com/docs/api/accordion-group#events

**Comment by sean-perkins** [comment]
Hello 👋 thanks for this issue!

I've addressed this here: https://github.com/ionic-team/ionic-framework/pull/29407 and it will be available in the docs after the next patch release.
