### ISSUE TITLE
[beta docs] Trailing slash inconsistency

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-docs#36]
If you surf around the new beta docs, you get URLs like https://beta.ionicframework.com/docs/building/contributing (note no trailing slash). But if you open that URL directly (e.g. by clicking that previous link) you are redirected with a 301 to https://beta.ionicframework.com/docs/building/contributing/ (note the trailing slash).

The added redirect makes opening docs pages via referring links (forum, Google, ...) a bit slower.

Solutions: 
a) Remove this redirect
b) Change all links to include the trailing slash

**Comment by janpio** [comment]
Oh right, depending on which version is shown those are different. 

Difficult decision: If you think of `folder/` but `file` (as it was back in the days before URL rewrites or on the file system) you still don't get a real answer. It should definitely always be `docs/` I think, but what about subpages? What about cases like https://beta.ionicframework.com/docs/intro and https://beta.ionicframework.com/docs/intro/concepts where the first one is both an individual page and later the "folder" for other individual pages?

**Comment by camwiegert** [comment]
7f6b5a8ec986e3df9febedf940da6ce2f207fec7
