### ISSUE TITLE
New docs doesn't support links in blockquotes

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#360]
Looks like whatever has changed with the beta v4 docs > v4 docs markdown renderer, it no longer supports links withing blockquotes:

https://ionicframework.com/docs/theming/advanced/#modifying-colors

https://ionicframework.com/docs/theming/advanced/#the-alpha-problem

![image](https://user-images.githubusercontent.com/1038062/51804529-f76c1480-2259-11e9-9c9d-a4e59ed3f164.png)

**Comment by camwiegert** [comment]
The problem here is that there's inline Markdown inside of real HTML.

```html
<blockquote>
  See the [CSS Variables](/docs/theming/css-variables) section for more information on how to get and set CSS variables.
</blockquote>
```

We should just use Markdown blockquotes instead:

```markdown
> See the [CSS Variables](/docs/theming/css-variables) section for more information on how to get and set CSS variables.
```
