### ISSUE TITLE
content: Missing Ionic 8 release notes and migration guide

### ISSUE THREAD

**Issue by StefanNedelchev** [ionic-team/ionic-docs#3608]
### URL

https://github.com/ionic-team/ionic-framework/releases/tag/v8.0.0

### Issue Description

I see that release v8 has been around since the 17th of April but it contains no release notes, breaking changes and migration guide.

**Comment by sean-perkins** [comment]
Hello @StefanNedelchev that information is available here:
- Migration guide: https://ionicframework.com/docs/updating/8-0
- Breaking changes: https://github.com/ionic-team/ionic-framework/blob/main/BREAKING.md#version-8x
- Changelog: https://github.com/ionic-team/ionic-framework/compare/v7.8.6...v8.0.0

I've updated the release tag with this information: https://github.com/ionic-team/ionic-framework/releases/tag/v8.0.0

Thanks!
