### ISSUE TITLE
content: 

### ISSUE THREAD

**Issue by Jareedos** [ionic-team/ionic-docs#3635]
### URL

https://ionicframework.com/docs/api/radio#:~:text=labelPlacement%E2%80%8B&text=%22end%22%20%3A%20The%20label%20will,radio%20regardless%20of%20the%20direction.

### Issue Description

Your docs say to use 'labelPlacement="end"' to place the label at the end on an ion-radio .  But that is incorrect it should be 
'label-placement="end"'. Your stack blitz shows it as 'labelPlacement="end"' as well but that do not work, instead 'label-placement="end"' works.
<img width="837" alt="Screenshot 2024-05-01 at 1 33 35 PM" src="https://github.com/ionic-team/ionic-docs/assets/10731415/b153b094-e112-46f4-885e-6413c2ff3fe0">

**Comment by brandyscarney** [comment]
Thanks for the issue! The example you are showing is the Angular code. Are you using this in an Angular app?
