### ISSUE TITLE
bug: samples are not displayed in the ionic docs due to SSL cert issue

### ISSUE THREAD

**Issue by ryaa** [ionic-team/ionic-docs#3636]
### Describe the Bug

Due to the ssl cert issue the content can not be loaded from CDN which broke all the sample on the ionic docs pages

### Expected Behavior

samples should work as expected

### Steps to Reproduce

Open https://ionicframework.com/docs/api/picker

### Screenshots

<img width="1726" alt="Screenshot 2024-05-02 at 5 59 15 AM" src="https://github.com/ionic-team/ionic-docs/assets/3608222/19f54948-1f5d-4c0d-9ec0-24185d96546a">

<img width="1127" alt="Screenshot 2024-05-02 at 5 59 34 AM" src="https://github.com/ionic-team/ionic-docs/assets/3608222/132c3343-95fa-4a69-9212-21bf7293630e">

### Operating System

N/A

### Browser

N/A

### Version

N/A

**Comment by liamdebeasi** [comment]
@ryaa Does this still reproduce? It looks like this was [fixed on JSDelivr's end](https://github.com/jsdelivr/jsdelivr/issues/18565).

**Comment by ryaa** [comment]
> @ryaa Does this still reproduce? It looks like this was [fixed on JSDelivr's end](https://github.com/jsdelivr/jsdelivr/issues/18565).

yeah. it works fine now. thank you
