### ISSUE TITLE
Document otherwise undocumented types/interfaces

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-docs#367]
https://ionicframework.com/docs/api/action-sheet

The role parameter is not listed in the properties section. From the code sample, you can derive there are at least two roles: cancel and destructive.

**Comment by camwiegert** [comment]
@chrisgriffith Thanks! That list of properties is just the properties of the action sheet component itself, while the role key is part of the [`ActionSheetButton` interface](https://github.com/ionic-team/ionic/blob/master/core/src/components/action-sheet/action-sheet-interface.ts#L21) passed to the controller.

I'd like to get those interfaces documented more clearly, but I hope the linked definition can help in the meantime!

**Comment by camwiegert** [comment]
Renaming this as I think it's part of a larger issue we'd like to address.

**Comment by camwiegert** [comment]
Closing in favor of #229
