### ISSUE TITLE
Missing migration#project-structure visuals

### ISSUE THREAD

**Issue by zarko-tg** [ionic-team/ionic-docs#372]
https://ionicframework.com/docs/building/migration#project-structure

<img width="915" alt="screenshot 2019-01-29 at 21 51 01" src="https://user-images.githubusercontent.com/6142411/51939698-6a1ef080-2410-11e9-9897-e31c3aebe0e6.png">

**Comment by camwiegert** [comment]
@zarko-tg Thanks for the report. This is a component that hadn't been ported from the beta docs. A fix has been pushed (acb35d5d2cd0d2e42e6ddee3a557111f5ad47c4a) and should be deployed shortly.

cc @kensodemann

**Comment by kensodemann** [comment]
@camwiegert - welp, we are getting closer... :)

<img width="608" alt="screen shot 2019-01-31 at 12 44 16 pm" src="https://user-images.githubusercontent.com/1526846/52077277-406fe180-2556-11e9-8d37-977c3a465d09.png">

**Comment by kensodemann** [comment]
Opened dev-tools, reloaded with cache disabled, and now it works fine. Chrome caching issue, I guess…
