### ISSUE TITLE
content: add documentation for programmatically focusing in ion-app

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#3815]
### URL

https://ionicframework.com/docs/api/app

### Issue Description

The `ion-app` component has an internal `setFocus` method that can be used to programmatically focus elements. We should document this usage in the `ion-app` documentation and remove the `@internal` flag:

```tsx
/**
 * @internal
 * Used to set focus on an element that uses `ion-focusable`.
 * Do not use this if focusing the element as a result of a keyboard
 * event as the focus utility should handle this for us. This method
 * should be used when we want to programmatically focus an element as
 * a result of another user action. (Ex: We focus the first element
 * inside of a popover when the user presents it, but the popover is not always
 * presented as a result of keyboard action.)
 */
@Method()
async setFocus(elements: HTMLElement[]) {
  if (this.focusVisible) {
    this.focusVisible.setFocus(elements);
  }
}
```

We may want to link to this documentation from other components to show how to programmatically focus them. 

Related issue: https://github.com/ionic-team/ionic-framework/issues/29830

**Comment by AlienDarkCat** [comment]
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by brandyscarney** [comment]
This was completed by https://github.com/ionic-team/ionic-docs/pull/3842
