### ISSUE TITLE
Add comprehensive search UI

### ISSUE THREAD

**Issue by camwiegert** [ionic-team/ionic-docs#384]
We had a search feature on the beta docs, and have a start on the search UI for the new docs. Since we're building all of the pages ahead of time now, we can also build a complete search index.

<img width="299" alt="screen shot 2019-01-31 at 1 29 29 pm" src="https://user-images.githubusercontent.com/2547860/52079925-41a40d00-255c-11e9-98d5-e46424aa5eea.png">

**Comment by rtpHarry** [comment]
Question: does it have a keyboard shortcut to focus the search? 

I am using docs tons at the moment as I'm still a n00b and this would be handy to be able to hop around quickly.

**Comment by dotNetkow** [comment]
Going to close since we have indeed rolled out a brand new search UI.  @rtpHarry - see the upper right hand corner of the docs, or use keyboard shortcut: /    (as in, slash key).
