### ISSUE TITLE
Lack of css variables section on some components.

### ISSUE THREAD

**Issue by iget-master** [ionic-team/ionic-docs#393]
Hello,

I was reading the docs about theming:

> Ionic provides variables that exist at the component level, such as --background and --color. For a list of the custom properties a component accepts, view the Custom Properties section of its API reference. For example, see the Button Custom Properties.

Following the link to Button Custom Properties shows it page with that nice CSS custom properties.

But some components just don't have that section, making the developer life harder.

* https://ionicframework.com/docs/api/header
* https://ionicframework.com/docs/api/footer
* https://ionicframework.com/docs/api/text

Not sure why they don't have this section, I just started working on Ionic 4 and had no time to read it sources yet to understand if variables are supported or not on this components.

I suggest that, if for some reason a component don't have CSS Custom Properties, the docs could be more strict saying it like: "This component don't have any CSS Custom Properties."

**Comment by rtpHarry** [comment]
As far as I know, you are correct that these are blank just because they don't have any variables. 

If you find one without the variables listed then normally its some kind of container and you should look at what goes inside it to find what can be modified with variables.

**Comment by perrygovier** [comment]
@rtpHarry is correct. Closing this since there's no variables to display.
