### ISSUE TITLE
bug: Ion Toast Icon Not Displaying (Angular)

### ISSUE THREAD

**Issue by MedOussemaNjimi** [ionic-team/ionic-docs#3959]
### Describe the Bug

The ion-toast component's icon property works correctly in the Ionic documentation demo presentation. However, the provided [Stackblitz example](https://stackblitz.com/) linked in the same documentation does not display the icon as expected.

### Expected Behavior

The icon should display in the toast when using the icon property, consistent with the behavior in the documentation's live demo.

### Steps to Reproduce

Visit the Ionic [Toast documentation page](https://ionicframework.com/docs/api/toast).
Scroll to the demo section and observe that the toast displays with an icon as expected.
Open the linked Stackblitz example from the [demo] of Angular Version (https://stackblitz.com/run?file=src%2Fapp%2Fapp.component.ts).
Run the Stackblitz example and trigger the toast.

**Comment by brandyscarney** [comment]
Thank you for reporting this issue! It was resolved by [this commit](https://github.com/ionic-team/ionic-docs/commit/bfc8452bebcee4dc9bfd394142f0bfe9eeb0ab78) and should now be working as expected. If you’re still encountering any problems, please let us know. Thanks!
