### ISSUE TITLE
[Ionic 4] Documentation for component ion-select-popover link broken

### ISSUE THREAD

**Issue by joeondrus** [ionic-team/ionic-docs#397]
# Bug Report

**Ionic version:**
[x] **4.x**

**Current behavior:**
We get a response of "Not Found".

**Expected behavior:**
The documentation is shown.

**Steps to reproduce:**
On the website (ionicframework.com):
Navigate to components -> [https://ionicframework.com/docs/components](https://ionicframework.com/docs/components)
Sroll down to `Select`
Click on `ion-select-popover` -> [https://ionicframework.com/docs/api/select-popover](https://ionicframework.com/docs/api/select-popover)
Screen returned is "😟 Not Found"

I could not find the documentation in the source.  If the documentation is in the source and I missed it, let me know where I can find it and I can create a PR.

**Comment by brandyscarney** [comment]
Thanks for the issue! This is an internal component, it just needs to be removed from the menu here: https://github.com/ionic-team/ionic-docs/blob/master/src/components/menu/templates/components.tsx#L141

We'll have to get this fixed, but let me know if you plan on creating a PR so we don't double up on it. Thanks! 🙂
