### ISSUE TITLE
Code samples too long

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-docs#406]
On https://ionicframework.com/docs/api/fab there are some code comments that exceed the width of the container causing the reader to scroll horizontally. 

For example:

is clipped at overlapping.

**Comment by camwiegert** [comment]
@chrisgriffith I think we have to accept that some horizontal scrolling will happen in code samples. 

There are too many determining factors that are out of our control. Because it's still visible with scrolling, I don't think it warrants the effort needed to prevent this. Thanks!
