### ISSUE TITLE
ion-skeleton-text usage missing

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-docs#407]
It seems the usage pane is missing, along with a sample app.
https://ionicframework.com/docs/api/skeleton-text

**Comment by camwiegert** [comment]
Looks like this happened because we have a [usage example](https://github.com/ionic-team/ionic/blob/master/core/src/components/skeleton-text/usage/javascript.md), but it's empty.

**Comment by brandyscarney** [comment]
I've added this as part of this PR: https://github.com/ionic-team/ionic/pull/17612

Note that some of the usage examples will not work perfectly without my PR. 🙂

**Comment by fahimehahmadi94** [comment]
ion-skeleton-text {
    --background-rgb: 230,40,50;
}
