### ISSUE TITLE
Ion-loading's Javascript code sample showing

### ISSUE THREAD

**Issue by chrisgriffith** [ionic-team/ionic-docs#408]
On https://ionicframework.com/docs/api/loading the Angular/JavaScript code sample shows both the Angular and Javascript panes when the Angular option is selected. The JS option only shows the JS code sample.

**Comment by liamdebeasi** [comment]
Hi @chrisgriffith,

Thanks for filing this issue. Would you be able to post a screenshot, as well as the browser & version you reproduced this on?

Thanks!

**Comment by chrisgriffith** [comment]
It seems to fine now.
