### ISSUE TITLE
Missing documentation segment default value

### ISSUE THREAD

**Issue by ElianCordoba** [ionic-team/ionic-docs#423]
# Bug Report

**Ionic version:**
[x] **4.x**

The segment documentation is missing examples on how to select a default.

**Comment by dotNetkow** [comment]
"checked" property available in the [demo source](https://github.com/ionic-team/ionic-docs/blob/master/src/demos/api/segment/index.html) on the [Segment component docs page](https://ionicframework.com/docs/api/segment), and documented on the ion-segment-button docs page.
