### ISSUE TITLE
content: add documentation on slots to components

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#437]
**URL**
https://ionicframework.com/docs/components

**What is missing or inaccurate about the content on this page?**
We need to document the slots on Ionic components. Depends on the following issue in Stencil: https://github.com/ionic-team/stencil/issues/1362

Ionic components using named slots:

- [x] Button
  - [x] icon-only
  - [x] start
  - [x] end
- [x] Content
  - [x] fixed
- [x] Item Divider
  - [x] start
  - [x] end
- [x] Item Option
  - [x] start
  - [x] top
  - [x] icon-only
  - [x] bottom
  - [x] end
- [x] Item
  - [x] start
  - [x] end
- [x] Range
  - [x] start
  - [x] end
- [x] Tabs
  - [x] top
  - [x] bottom
- [x] Toolbar
  - [x] start
  - [x] secondary
  - [x] primary
  - [x] end

**Comment by brandyscarney** [comment]
The content part has been added and merged here: https://github.com/ionic-team/ionic/pull/17441

Do we want to add a separate issue for the UI design @camwiegert?

**Comment by camwiegert** [comment]
@brandyscarney I'm fine with using this issue for the UI.
