### ISSUE TITLE
v4 Docs: Grammar issue in Progressive-web-apps

### ISSUE THREAD

**Issue by MustaRohman** [ionic-team/ionic-docs#447]
**Describe the bug**
A simple grammar issue in the 'Deployment' subsection of 'Progressive Web App' page

> With the Firebase CLI installed run firebase init in the project. This will **set generate** a firebase.json config file and configure the app for deployment.

**To Reproduce**
1. Go to 'https://ionicframework.com/docs/publishing/progressive-web-app#deploying'

**Expected behavior**
> With the Firebase CLI installed run firebase init in the project. This will **generate** a firebase.json config file and configure the app for deployment.

**Screenshots**

**Browser and OS (please complete the following information):**
Any

**Additional context**

Errrmm, this is my first pull request, with hopefully many more to come. Please let me know if I've done anything wrong here. I am open to feedback! :)

**Comment by camwiegert** [comment]
@MustaRohman Thanks for contributing and congrats on the first issue! 🎉If you'd like to open a pull request with a fix, I'd suggest taking a look at our [contributing doc](https://github.com/ionic-team/ionic-docs/blob/master/.github/CONTRIBUTING.md).

**Comment by MustaRohman** [comment]
@camwiegert Awesome! Thanks a lot 👍

**Comment by brandyscarney** [comment]
I'm going to close this as the PR was merged, thank you!
