### ISSUE TITLE
[beta docs] Components, "Open Preview" doesn't work

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-docs#45]
If your viewport is too small to display the preview on the page, it displays a "Open Preview" link. That opens a new window/tab when clicked with URL https://beta.ionicframework.com/docs/content/component-preview-app/docs-www/. That URL only shows an Ionic logo but doesn't do anything.

**Comment by camwiegert** [comment]
Looking at it, that is working as expected. The issue with that page specifically is that it needs to receive a message to display a certain demo. You can do it manually by add a hash (e.g. `#button`) and reloading the page.

That said, it's confusing and unhelpful on the component preview. So I'd like to remove it there. Thanks!

**Comment by camwiegert** [comment]
https://beta.ionicframework.com/docs/content/component-preview-app/docs-www/#list

**Comment by janpio** [comment]
Yep, I was expecting some kind of navigation in the newly opened window or a changing "Open Preview" button for each component.
