### ISSUE TITLE
StackOverflow Tag Wiki Has Outdated Content

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#458]
**URL**
The URL at which the content is missing or inaccurate (updated link):
https://stackoverflow.com/tags/ionic-framework/info

**What is missing or inaccurate about the content on this page?**
It's out of date. Assume that this was originally written by a team member as it says "in the future *we* hope...", but either way, it should be updated.

**Comment by camwiegert** [comment]
@rtpHarry I'm unclear on where this content is located. Is that StackOverflow page linked to from somewhere? I'm just seeing a 404 on the linked page.

**Comment by rtpHarry** [comment]
Sorry, I thought it would redirect you to login rather than 404.

Its for the description of the Ionic Framework tag on StackOverflow:

https://stackoverflow.com/tags/ionic-framework/info

Just checked, this is accessible in an incognito tab:

![image](https://user-images.githubusercontent.com/1038062/52745639-72158d80-2fd7-11e9-831a-b0289eb3383c.png)

**Comment by camwiegert** [comment]
Going to close this as it isn't directly related to the docs. But I'll talk with the team about updating this. Thanks!
