### ISSUE TITLE
[beta docs] Embedded preview is shown with serif fonts

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-docs#46]
https://beta.ionicframework.com/docs/components/#alert
![image](https://user-images.githubusercontent.com/183673/43265476-208299aa-90e9-11e8-8139-93ca4fe07f4e.png)

(Windows 10, FF61)

**Comment by camwiegert** [comment]
@janpio Thanks for opening this. This was caused by our global styles not being included correctly in the preview window. It was fixed [here](https://github.com/ionic-team/component-preview/commit/b046af8acb414b467d589566cfaba16f55706fa9).
