### ISSUE TITLE
Suggestion - Please add Vue to Docs Usage for Ionic 4

### ISSUE THREAD

**Issue by BenHayat** [ionic-team/ionic-docs#461]
Hello Ionic Doc's Team;
As each component (Ionic 4) in the doc section has a Usage sample for Angular and JS, could you please add Vue syntax as well?

Thanks!
..Ben

**Comment by brandyscarney** [comment]
I moved this issue over to the `ionic-docs` repo since it is both a documentation content and UI issue, but just there are some open PRs to add vue usage docs for a few components: https://github.com/ionic-team/ionic/pulls?utf8=%E2%9C%93&q=is%3Aopen+is%3Apr+label%3A%22package%3A+vue%22+docs

**Comment by camwiegert** [comment]
This release includes React and Vue usage docs: 97da705bfac733facb02c9dcc7e9628fbfda0633
