### ISSUE TITLE
Document how to update value for ion-range dual knob

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic-docs#479]
**Is your feature request related to a problem? Please describe.**
`ion-range` should describe how to properly update values with a dual knob range. 

Due to how change detection works in stencil, mutating the value object does not cause change detection to happen: https://stenciljs.com/docs/reactive-data/#updating-an-object

**Describe the solution you'd like**
Ideally, there would be 1-2 sentences explaining how to update the lower and upper values such that change detection runs.

**Additional context**
This does not work:
```
dualKnobRangeElement.value.lower += 1;
```

This does work:
```
dualKnobRangeElement.value = {
  lower: lower + 1,
  upper: upper
}
```

**Comment by brandyscarney** [comment]
Can we close this since the playground shows an example of it? https://ionicframework.com/docs/api/range#dual-knobs
