### ISSUE TITLE
Theming: update the utility attributes to use classes

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#480]
**URL**
https://ionicframework.com/docs/layout/css-utilities

**What is missing or inaccurate about the content on this page?**
Currently all of our theming documentation for css utilities is using the attribute styles, e.g.:

```html
<ion-col text-center>
```

This should be updated to use the CSS classes:

```html
<ion-col class="ion-text-center">
```

<img width="659" alt="screen shot 2019-02-21 at 11 25 35 am" src="https://user-images.githubusercontent.com/6577830/53184658-6fb0c600-35cb-11e9-9b82-f8b20e0ccd37.png">

**Comment by tmk1991** [comment]
Why is this changed proposed? This will break all instances where I have text-center etc

**Comment by brandyscarney** [comment]
@tmk1991 It is not a breaking change. The attributes are still there, this just removes them from the documentation and documents the class versions of the same attributes: https://github.com/ionic-team/ionic/blob/master/core/src/css/text-alignment.scss#L14-L15

We are removing the attribute documentation in favor of using the classes. As we add more utilities (see [display](https://github.com/ionic-team/ionic/blob/master/core/src/css/display.scss#L19)) we will be adding them as classes only. The reason behind moving to classes is because in React, Stencil, or any framework using JSX and TypeScript there will be type errors thrown if you try to use a CSS attribute as it is looking for it to be a property of that element. Rather than have users use CSS attributes for certain frameworks and classes for others, we're recommending classes for consistency as they will work across frameworks without issue. Let me know if you have any questions, thanks!

**Comment by tmk1991** [comment]
So you're keeping the attributes it looks like: 

`.ion-text#{$infix}-center,
    [text#{$infix}-center] {
      text-align: center !important;
    }`

I panicked when I went into the docs and saw attributes removed from them.

**Comment by brandyscarney** [comment]
Yes, we won't remove the attributes without a breaking change which requires a major version release (Ionic 5.x) but we are recommending classes for consistency. 🙂

**Comment by tmk1991** [comment]
Thanks @brandyscarney ! - Sorry if my original message came off as inflammatory. I should have investigated it more closely.

**Comment by brandyscarney** [comment]
@tmk1991 No worries! I understand the concern. It's definitely a goal of ours not to introduce any breaking changes moving forward without a major version, so I want to make sure that in cases like this that doesn't happen. 🙂
