### ISSUE TITLE
ion-ripple-effect does not document ion-activatable usage

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic-docs#504]
**URL**
https://ionicframework.com/docs/api/ripple-effect

**What is missing or inaccurate about the content on this page?**
The docs give examples on how to use the `ion-ripple-effect` component, but none of them actually work unless the parent element has the `ion-activatable` class applied to it. We should update this document to make note of that.

**Comment by camwiegert** [comment]
@liamdebeasi Yeah good idea. Probably also worth mentioning that `ion-activatable` is automatically applied on some components. (e.g. button)

**Comment by peterpeterparker** [comment]
If the documentation of the ripple effect is improved, it would probably worse to mention in the same time that its container should also has a relative positioning (`position: relative;`)

**Comment by perrygovier** [comment]
This exists now
