### ISSUE TITLE
[beta docs] CSS Variables link broken

### ISSUE THREAD

**Issue by fvaldes33** [ionic-team/ionic-docs#51]
[X] bug report
[ ] feature request

**URL:**
The css-variables link found on the theming/basics page is broken.

https://beta.ionicframework.com/docs/theming/basics/css-variables <- 404
https://beta.ionicframework.com/docs/theming/basics/

**Current behavior:**
404

**Expected behavior:**
Should go to this page:
https://beta.ionicframework.com/docs/theming/css-variables/

**Comment by camwiegert** [comment]
@fvaldes33 Thanks for opening this! I believe this is related to #36 and relative URLs. The link is `./css-variables`. So, when there is a trailing slash it resolves to:
```
/docs/theming/basics/css-variables
```
Whereas when it doesn't have a trailing slash, it resolves to:
```
/docs/theming/css-variables
```

**Comment by camwiegert** [comment]
Going to close this as it's symptomatic of a larger issue. (#36)
