### ISSUE TITLE
Missing Ionic Native framework-specific config

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic-docs#510]
In the v3 docs, there used to be a space on each plugin page that would tell the user to add the plugin to their `app.module.ts` file.

Example:

v4: https://ionicframework.com/docs/native/apple-pay
v3: https://ionicframework.com/docs/v3/native/apple-pay/

I've gotten a handful of issues where users are getting errors similar to `StaticInjectorError(Platform: core)[n -> l]: NullInjectorError: No provider for l`, and it's due to the plugins not having been added to `app.module.ts`.

It would be great to add that extra bit of platform-specific instructions back into the documentation.

**Comment by dotNetkow** [comment]
oops that info got removed... linking [for later here](https://web.archive.org/web/20171110134247/https://ionicframework.com/docs/native/).

**Comment by brandyscarney** [comment]
I can't tell if this is still an issue because I'm not sure what is missing haha. Can we close this or does it still need to be added?

**Comment by liamdebeasi** [comment]
We can close it as we do not manage Ionic Native anymore.
