### ISSUE TITLE
State which Swiper options we support

### ISSUE THREAD

**Issue by liamdebeasi** [ionic-team/ionic-docs#511]
https://ionicframework.com/docs/api/slides

The `ion-slides` component does not support all of the options that are exposed in Swiper. We should update the documentation to explain which options are not supported (i.e. keyboard support). This has been a point of confusion for some users (see: https://github.com/ionic-team/ionic/issues/17662)

**Comment by lawchihon** [comment]
Is there any update for it? It is kind of annoying to test out which function work and which doesn't

**Comment by brandyscarney** [comment]
Do we still want to do this since we are now providing migration guides and deprecating slides?

**Comment by liamdebeasi** [comment]
We can probably close this since the recommendation is to use Swiper directly.
