### ISSUE TITLE
[beta docs] Last component Virtual Scroll does not get loaded into component preview

### ISSUE THREAD

**Issue by taylanken** [ionic-team/ionic-docs#52]
**I'm submitting a ...**
[x] bug report
[ ] feature request

**URL:**
[https://beta.ionicframework.com/docs/components/#toast](https://beta.ionicframework.com/docs/components/#toast)

**Current behavior:**
If I scroll all the way down on my monitor (1080p resolution) on the component docs page, the last component that gets displayed in the component preview on the right is Toast. Since I cannot scroll further down, the **Virtual Scroll**-component never gets loaded into the preview:

![image](https://user-images.githubusercontent.com/29762629/43267686-ef9a4d14-90ee-11e8-8c69-9d6c824b86b2.png)

**Expected behavior:**
I would expect that I am able to scroll further down to the point where the **Virtual Scroll**-component gets loaded into preview.

**Steps to reproduce:**
- Open the component docs in Chrome or Firefox on a 1080p-display.
- Scroll all the way down

**Comment by camwiegert** [comment]
@taylanken Thanks! It was padded with a fixed margin, but should be fixed by [this](https://github.com/ionic-team/ionic-docs/commit/b466aafdad499ae9ff3e69d1a892e89a34ab96b1).
