### ISSUE TITLE
“Quickstart” or “Start here” section

### ISSUE THREAD

**Issue by adamdbradley** [ionic-team/ionic-docs#524]
Left menu could use a simple “start here” link on the side menu. Right now it’s not immediately clear where you’re supposed to actually start, and “Packages & CDN” isn’t very descriptive.

![image](https://user-images.githubusercontent.com/452425/53968351-7c99e300-40bc-11e9-91f3-5b0d88c52e83.png)

**Comment by perrygovier** [comment]
I think https://ionicframework.com/docs/building/starting covers this ok
