### ISSUE TITLE
Color generator format is off

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#53]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/theming/color-generator/

**Current behavior:**
Color pickers are inline with the intro

**Expected behavior:**
The intro paragraph should not be on the same line as the color pickers

**Steps to reproduce:**
Go to the URL

**Other information:**

<img width="1102" alt="screen shot 2018-07-26 at 1 37 25 pm" src="https://user-images.githubusercontent.com/6577830/43278461-31beaa66-90d9-11e8-81db-ea773e65a69d.png">

**Comment by camwiegert** [comment]
Fixed! ✨ f7f3588b0337ed8c5e40c959b81108bfd472405e
