### ISSUE TITLE
It's onIonChange not ionChange @ionic/react

### ISSUE THREAD

**Issue by SulimanTwfiq** [ionic-team/ionic-docs#536]
**URL**
The URL at which the content is missing or inaccurate
https://ionicframework.com/docs/api/input
**What is missing or inaccurate about the content on this page?**
ionChange is not working in reactjs ,It must be  onIonChange to work.
I think it must be mentioned in the documentation .

**Comment by camwiegert** [comment]
@SulimanTwfiq The event name is still `ionChange`, the difference is in how React registers event handlers in JSX. For example, to listen for the `click` event you would write something like:

```jsx
<div onClick={handleClick}/>
```

The same is true for our custom event, `ionChange`:

```jsx
<div onIonChange={handleIonChange}/>
```

All that is to say that the `on` prefix is part of JSX. So, the docs aren't _really_ incorrect, but could definitely be made clearer. Thank you!

**Comment by jefer94** [comment]
In React, if i'll copy/paste the event, with React selected in the doc, it not work, too the menu example, the same thing, it's incorrect because I'll look the doc if not know an component. Because it, the doc are really incorrect.
