### ISSUE TITLE
Some code samples not being escaped

### ISSUE THREAD

**Issue by mahdiarn** [ionic-team/ionic-docs#545]
**URL**
https://ionicframework.com/docs/developer-resources/guides/first-app-v4/ios-android-camera

**Problem**
The XML tag does not appear, but when i check on .md file, it was displayed perfectly

![1552221190204](https://user-images.githubusercontent.com/18479742/54085023-66fe1500-436b-11e9-926b-d520f13692c7.jpg)

**Comment by camwiegert** [comment]
@mahdiarn Thanks for reporting this! I believe it's related to [this change](https://github.com/ionic-team/ionic-docs/commit/9ba8312b4996565319fc838719c3721ccf52bb35#diff-2e3be8e521c586c55e33907c8bdf477b). We are no longer running all code samples through a highlighter, which would do our escaping. I have a fix in mind.
