### ISSUE TITLE
A page to show the current state of development for Angular, React & Vue

### ISSUE THREAD

**Issue by BenHayat** [ionic-team/ionic-docs#548]
Hello Team;
Since there are gaps between the maturity stage of NG, React and Vue in the development stage, could you please add a page to Ionic 4 website that shows a progress bar (or a number) that shows how far the completion of each framework development is, compared to the other frameworks?

For example, it could be stated:
Angular: 50% Completed
React: 40% Completed
Vue: 30% complete

This can help those of us who use different frameworks as to "When" to get started using Ionic for real app.

Thanks!
..Ben

**Comment by camwiegert** [comment]
@BenHayat Thanks for the suggestion! As @pwespi mentions, semantic versioning will be the clearest indicator of when we deem each of these ready for production use. I'm not sure we could come up with an accurate percentage, really. In the meantime, I'd suggest watching the Ionic [blog](https://blog.ionicframework.com/) and [Twitter](https://twitter.com/ionicframework) account for updates.
