### ISSUE TITLE
[beta docs] Popover not working correctly

### ISSUE THREAD

**Issue by chrislow** [ionic-team/ionic-docs#55]
**I'm submitting a ...**
[x] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/components/#popover

**Current behavior:**
When opening the popover by clicking on the icon in the top-menu, you can select multiple fonts, but the font of the text only changes on the first click.

**Expected behavior:**
Font selection should be radio boxes and only one should be selectable.

**Steps to reproduce:**
* Go to https://beta.ionicframework.com/docs/components/#popover
* Click on the popover menu in the component preview
* Select a font -> Text gets updated
* Select another font -> Text doesnt get updated but font is still selected.

**Tested Environment:**
```
Operating System:   Linux Ubuntu 18.04.
Platform:           UNIX
Browser:            Google Chrome, Version 67.0.3396.99 (Official Build) (64-bit)
```

**Comment by chrislow** [comment]
![image](https://user-images.githubusercontent.com/5181596/43310002-a8cd7698-9186-11e8-8eaf-f1e86bca7d43.png)

**Comment by brandyscarney** [comment]
Thanks for the issue! This should be fixed by https://github.com/ionic-team/component-preview/commit/7d52cd0eedfd08901124801c320dd8d6df1bc1d1

We'll have a new deploy of the site soon. 🙂
