### ISSUE TITLE
Consider participating in Google's Season of Docs 2019

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#556]
Please, can you take a look at Google's Season of Docs and consider participating:

https://developers.google.com/season-of-docs/

It's like their Year of Code program but for technical writers.

It's something I would like to get involved in and would love to write for Ionic Framework if you are looking for help.

It's a three-month program and somebody from the organisation would need to be a mentor for the project. In exchange, any successful applicant would spend 1 month getting to know your requirements and then 2 months writing docs.

The website goes into more detail about the program.

**Comment by dotNetkow** [comment]
hi there - just letting you know we see this and are looking into it.  :)

**Comment by rtpHarry** [comment]
thanks for the update :)

**Comment by dotNetkow** [comment]
Hi @rtpHarry - met with the team. Unfortunately, at this time, it's not something we can prioritize at the moment - so we won't be participating. However, I have some ideas about ways you can still contribute as we do need the help. Can you email me? netkow@ionic.io. Thanks!
