### ISSUE TITLE
[CLI docs for ionic start]: docs for boolean options such as --git are wrong

### ISSUE THREAD

**Issue by pwespi** [ionic-team/ionic-docs#558]
In the documentation of the [`ionic start`](https://ionicframework.com/docs/cli/commands/start) command it says:

>`--git`
Do not initialize a git repo

However, it should be:
`--no-git`

The same goes for `--deps` and `--link`.

@dwieeb I'm not sure if this is an issue with the ionic-docs or ionic-cli repo.

**Comment by rtpHarry** [comment]
Looks like its here:

https://github.com/ionic-team/ionic-cli/blob/master/packages/ionic/src/commands/start.ts#L119

**Comment by dwieeb** [comment]
Thanks @pwespi! Must've missed that...
