### ISSUE TITLE
"Starting an App" steps on v4 docs website creates ionic v3 app...?

### ISSUE THREAD

**Issue by goleary** [ionic-team/ionic-docs#56]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/installation/cli/

**Current behavior:**
I followed the direction at the link abovefor creating an App. and when I inspect package.json I see:

`"ionic-angular": "3.9.2"`

**Expected behavior:**
I expect this to create an Ionic v4 app.

**Steps to reproduce:**
described at link above

**Comment by dwieeb** [comment]
@goleary Are you sure you're on CLI 4?

**Comment by goleary** [comment]
![image](https://user-images.githubusercontent.com/16123225/43344863-3d11983e-91a0-11e8-9463-724a33f7f4cb.png)

**Comment by chrisgriffith** [comment]
Did you include the --type=angular flag when you generated the app? The default type was changed during the last few alpha releases?

**Comment by goleary** [comment]
yeah looks like my mistake, sorry for the distraction.
