### ISSUE TITLE
docs: select API misses multiple value usage

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#564]
**URL**
https://ionicframework.com/docs/api/select

**What is missing or inaccurate about the content on this page?**
There are no examples for how to pass a value to a multi value select. See this issue: https://github.com/ionic-team/ionic/issues/17785

Also, weirdly the heading for multiple selection is under the single selection one: https://ionicframework.com/docs/api/select#multiple-selection

It should be the same heading level.

**Comment by gaurangkela** [comment]
any update on this? ion-select-option does not trigger ionSelect event

**Comment by brandyscarney** [comment]
Fixed by https://github.com/ionic-team/ionic/commit/a5229d90ca2a608e8bf4db0c8f71c86d481dd649
