### ISSUE TITLE
Update iOS/Android demo toggle design

### ISSUE THREAD

**Issue by bensperry** [ionic-team/ionic-docs#57]
Visual design and spacing update to the iOS/Android component demo platform toggle at the top. This also includes making the toggle visible at all times.

Some more info:
![image](https://user-images.githubusercontent.com/519526/43342939-0cd6a5f6-91aa-11e8-814a-70dd5928f13c.png)

`font-family: -apple-system,BlinkMacSystemFont...;
font-size: 10px;
color: #9da7b9 / #3880ff
font-weight: 600 / 700;
letter-spacing: 0.04em;`

Active border bottom:
`border-bottom: 2px solid #b7d4ff`

**Comment by brandyscarney** [comment]
+💯 Need this https://github.com/ionic-team/ionic-docs/issues/47

**Comment by CheetahDev** [comment]
Hey,

Any update on this? It's unfortunately very anoying when you want to present Ionic components to people! :disappointed: 

C.

**Comment by CheetahDev** [comment]
Wonderful, perfect timing! :smile:

**Comment by dotNetkow** [comment]
Closing due to new doc design rolled out as Brandy mentions above.
