### ISSUE TITLE
Navigation Ionic 4 Vanilla Javascript

### ISSUE THREAD

**Issue by RiyadKhalifeh** [ionic-team/ionic-docs#570]
Hello,
I’am using Vanilla Javascript in Ionic4
I want to route from one page to other but I don’t know how to add second page “such as Login Page for example”
 My www is in attachment

Thanks a lot

[www.zip](https://github.com/ionic-team/ionic-docs/files/2975429/www.zip)

**Comment by brandyscarney** [comment]
Thanks for the issue! Please visit our [forum](https://forum.ionicframework.com/) or [slack channel](http://ionicworldwide.herokuapp.com/) for questions about the framework. :smile:

We also have some documentation on our router here: https://ionicframework.com/docs/api/router

If you are looking for something specific, please create a new issue. Thanks!
