### ISSUE TITLE
/docs/introduction is missed

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-docs#575]
**Describe the bug**
ionicframework.com navigation link `https://ionicframework.com/docs/introduction`. But this is disable.

correct link is `https://ionicframework.com/docs/intro`

**To Reproduce**
1. hover `Developers`
2. Click on 'Introduction'

**Expected behavior**
missed link.

**Screenshots**
![スクリーンショット 2019-03-19 20 54 44](https://user-images.githubusercontent.com/9690024/54604256-a8887180-4a89-11e9-9250-b7413aeb3bbc.png)

**Browser and OS (please complete the following information):**

**Additional context**

**Comment by camwiegert** [comment]
Thanks! Fixed in ionic-team/ionic-site@7f483a9ec8a4e6e41c9216107cd154b3833c62fe.
