### ISSUE TITLE
Background image in ionic v4

### ISSUE THREAD

**Issue by zeel91297** [ionic-team/ionic-docs#579]
**URL**
https://ionicframework.com/docs/api/content

**What is missing or inaccurate about the content on this page?**
Here If someone wants to add background image to whole page then it is not displayed and it is also giving error?
Please show some demo of it.

**Comment by camwiegert** [comment]
@zeel91297 The background of `ion-content` can be set using the `--background` custom property:

```css
ion-content {
  --background: src("path/to/image.jpg");
}
```

Here is a list of all of [ion-content's custom properties](https://ionicframework.com/docs/api/content#css-custom-properties) and here is our [doc on using CSS variables to customize Ionic components](https://ionicframework.com/docs/theming/css-variables). Hope that helps!

**Comment by zeel91297** [comment]
@camwiegert I already tried writing the same code to my scss file but the code is not working and the background is still empty. Can you suggest any other way of doing so?
