### ISSUE TITLE
Virtual Scroll ionic v4

### ISSUE THREAD

**Issue by zeel91297** [ionic-team/ionic-docs#580]
**URL**
https://ionicframework.com/docs/api/virtual-scroll

**What is missing or inaccurate about the content on this page?**
Any beginner is new to ionic and if start learning from ionic 4 it is very difficult to understand how the coding flow goes from HTML to it's TypeScript. If you have given that information properly with demo it would be very helpful.

**Comment by perrygovier** [comment]
Sorry about that. I think this has been addressed w/ some improvements made to 
https://ionicframework.com/docs/api/virtual-scroll
