### ISSUE TITLE
Update to top navbar content

### ISSUE THREAD

**Issue by bensperry** [ionic-team/ionic-docs#592]
This change adds a few drop-downs and moves a couple of things around in the top navbar:

* Update our "open in new tab" icon to original (beta docs) style:
![image](https://user-images.githubusercontent.com/519526/54838956-d2af7e80-4c97-11e9-8dd0-d6b1b6a4edf2.png)

* Move the "v3" link to the docs switcher drop-down. Add Stencil and Capacitor, too.
![image](https://user-images.githubusercontent.com/519526/54838892-adbb0b80-4c97-11e9-97cb-cbf94b08ec67.png)

* Turn the "Community" link into a drop-down:
![image](https://user-images.githubusercontent.com/519526/54839080-199d7400-4c98-11e9-9e28-986d3052c7a0.png)

* Turn the "Support" link into a drop-down:
![image](https://user-images.githubusercontent.com/519526/54839230-6d0fc200-4c98-11e9-9830-cd0d5374203b.png)

**Comment by camwiegert** [comment]
Partially addressed in #598
