### ISSUE TITLE
Update Community Dropdown

### ISSUE THREAD

**Issue by bensperry** [ionic-team/ionic-docs#60]
Simplify the Community dropdown design. Remove icons. Update typeface/color.

![image](https://user-images.githubusercontent.com/519526/43348822-a9c439ca-91c1-11e8-8896-1347fef86034.png)

**Comment by bensperry** [comment]
Community Hub is currently being built, so can wait until that's published.

**Comment by dotNetkow** [comment]
Closing out as it appears like this design is now in place. Ben, reopen if need be.
