### ISSUE TITLE
[Not Found] - .json files is missing in "www" directory.

### ISSUE THREAD

**Issue by xamantra** [ionic-team/ionic-docs#603]
**http://localhost/docs/***/index.json**

**All or some json files is missing.**

**Comment by dotNetkow** [comment]
Hi, can you elaborate on what the specific issue is? Whether running the docs locally or the online published version, everything seems to be ok to me - no missing files. Please see our [contributing readme](https://github.com/ionic-team/ionic-docs/blob/master/CONTRIBUTING.md) for more details.
