### ISSUE TITLE
Open Preview buttons needs some love

### ISSUE THREAD

**Issue by manucorporat** [ionic-team/ionic-docs#65]
I love the "Open Preview" feature of the docs, but right now looks like second-citizen UI component.

- More spacing
- Bigger button?

![image from ios 1](https://user-images.githubusercontent.com/127379/43368856-d3e77e94-9363-11e8-85c5-b525110a53c8.png)

cc @bensperry thoughts?

**Comment by bensperry** [comment]
Your battery needs some love.

**Comment by manucorporat** [comment]
absolutely! 1% last for hours in my device hahaha

**Comment by bensperry** [comment]
How's this?

![preview](https://user-images.githubusercontent.com/519526/43405833-663b5686-93e0-11e8-984c-82faaae0887f.png)

**Comment by manucorporat** [comment]
what if it's that eye inside a little phone? haha

**Comment by bensperry** [comment]
Okay, but did you notice I also fixed your battery?

**Comment by bensperry** [comment]
Alright chatted with @manucorporat and we're going with this:

![image](https://user-images.githubusercontent.com/519526/43410674-5004681e-93ed-11e8-83b5-5960e33f0ccb.png)

**Comment by manucorporat** [comment]
> Okay, but did you notice I also fixed your battery?

HAAHHAAH i just did, thanks man! i hope i can run with that for a couple of days

**Comment by camwiegert** [comment]
@bensperry At the moment, the "Open Preview" link opens a new tab. Do we want to make that clear with the icon? I think you lose a little context by using the icon.

**Comment by bensperry** [comment]
@camwiegert Yeah, honestly I'd be fine with using our "open in new tab" icon scattered throughout the docs (assuming you are). If you want to roll with that to get this out the door sooner, go for it. 

This:
![image](https://user-images.githubusercontent.com/519526/43421794-627a09f2-940d-11e8-9f42-5173582dad27.png)
