### ISSUE TITLE
docs: change `npm install` to `ng add`.

### ISSUE THREAD

**Issue by rdlabo** [ionic-team/ionic-docs#657]
**Is your feature request related to a problem? Please describe.**
Docs introduce `how to add ionic` is npm install. But this method need some step.

https://ionicframework.com/docs/installation/cdn#angular-ionic-framework

**Describe the solution you'd like**
I think `ng add` is better. ng add is not only add package. It will handle these.

```
CREATE src/theme/variables.css (288 bytes)
UPDATE package.json (1375 bytes)
UPDATE src/app/app.module.ts (466 bytes)
UPDATE angular.json (5889 bytes)
```

**Describe alternatives you've considered**

**Additional context**

**Comment by amandaejohnston** [comment]
Thanks for the issue. It looks like `ng add` was added as an option in the time since this issue was posted: https://ionicframework.com/docs/intro/cdn#ionic--angular As such, I'm going to close this out.
