### ISSUE TITLE
Add generic phone status bars

### ISSUE THREAD

**Issue by bensperry** [ionic-team/ionic-docs#66]
Both our iOS and Android versions need to have some abstract reference to top/bottom utility bars. Here's what I propose for designs:

Android:
![image](https://user-images.githubusercontent.com/519526/43406235-6fb104f8-93e1-11e8-81db-c436dedcc1cf.png)

iOS:
![image](https://user-images.githubusercontent.com/519526/43406307-8e8bf482-93e1-11e8-8eef-812405838ccf.png)

We can probably do this pretty easily with some SVGs or even just CSS. LMK how you want to proceed when you're ready.

**Comment by dotNetkow** [comment]
We've got this in the v4 docs now ([the component demos](https://ionicframework.com/docs/api/action-sheet)), so closing.
