### ISSUE TITLE
Documenting dismissing overlays / toast

### ISSUE THREAD

**Issue by brandyscarney** [ionic-team/ionic-docs#660]
**URL**
https://ionicframework.com/docs/api/toast

**What is missing or inaccurate about the content on this page?**
I'm seeing some confusion with users on how to use onDidDismiss that we should document: 

https://github.com/ionic-team/ionic/issues/15389#issuecomment-417352644
https://forum.ionicframework.com/t/ionic-4-toast-syntax-has-changed/162557

Ionic Team Edit: We need to add usage examples for how to use `onDidDismiss` in our overlay components. Specifically, we are missing examples for `ion-toast`, `ion-popover`, `ion-alert`, and `ion-action-sheet`.

As an example, here is how we could update one of the `ion-toast` examples. Currently we have the following:

```typescript
async presentToast() {
  const toast = await this.toastController.create({
    message: 'Your settings have been saved.',
    duration: 2000
  });
  toast.present();
}
```

We could update the example to the following:

```typescript
async presentToast() {
  const toast = await this.toastController.create({
    message: 'Your settings have been saved.',
    duration: 2000
  });
  await toast.present();
  
  const { role } = await toast.onDidDismiss();
  console.log('onDidDismiss resolved with role', role);
}
```

We need to show how to use `onDidDismiss` in Angular, JavaScript, Stencil, and Vue, so be sure to edit those specific usage files instead of the `readme.md` file. Feel free to do this as one PR.

**Comment by willmartindev** [comment]
The current Vue usage example for Toast is as follows:

```html
<template>
  <ion-button @click="setOpen(true)">Show Toast</ion-button>
  <ion-toast
    :is-open="isOpenRef"
    message="Your settings have been saved."
    :duration="2000"
    @onDidDismiss="setOpen(false)"
  >
  </ion-toast>
</template>
```

Should the event binding be `@ionPopoverDidDismiss` ? And if the example makes use of the event should I still add example usage of the `onDidDismiss()` method?
