### ISSUE TITLE
docs: xcode 10 now supported in cordova 5.0.0

### ISSUE THREAD

**Issue by jadurani** [ionic-team/ionic-docs#663]
**URL**
https://ionicframework.com/docs/installation/ios

**What is missing or inaccurate about the content on this page?**
This is no longer accurate:
> We recommend using XCode 9. Xcode 10 support in Cordova is still a work-in-progress. See this issue for details.

As of Feb 9 2019, support for XCode 10 has already been finalized.

See: https://cordova.apache.org/announcements/2019/02/09/cordova-ios-release-5.0.0.html
Note:
> This release only supports Xcode 9 and up. It is important to know that starting March 2019, Apple requires all new apps submitted to the App store to be built with the iOS 12.1 SDK or later (Xcode 10). [source](https://developer.apple.com/ios/submit/)

**Comment by dotNetkow** [comment]
Thank you for the issue. Going to close since we recently updated the page to remove any mentions of specific Xcode versions.
