### ISSUE TITLE
Component Demo/Preview - Button

### ISSUE THREAD

**Issue by bensperry** [ionic-team/ionic-docs#67]
Design for the Button component demo:

![image](https://user-images.githubusercontent.com/519526/43411312-661c6ffa-93ef-11e8-9cec-5a7c6f7d4f0c.png)

All of the button demo examples can up modified into a Solid (default), Outline, and Clear mode from an inline "tabs" design:

![image](https://user-images.githubusercontent.com/519526/43411502-f1998518-93ef-11e8-9b82-5bbeca05ed6f.png)

**Comment by bensperry** [comment]
FYI - this is a screenshot of the demo in iOS mode. Android would be the same, just using Android platform styles.

**Comment by brandyscarney** [comment]
This has been done: https://ionicframework.com/docs/api/button
