### ISSUE TITLE
ion-select controller dead links

### ISSUE THREAD

**Issue by peterpeterparker** [ionic-team/ionic-docs#676]
**Describe the bug**
On the `ion-select` doc page ([https://ionicframework.com/docs/api/select](https://ionicframework.com/docs/api/select)] the links to the controllers point to nothing

**Screenshots**
<img width="1232" alt="Capture d’écran 2019-05-01 à 18 12 29" src="https://user-images.githubusercontent.com/16886711/57029134-228f4700-6c41-11e9-8008-2a5ccfae266d.png">

<img width="1232" alt="Capture d’écran 2019-05-01 à 18 44 05" src="https://user-images.githubusercontent.com/16886711/57029143-2b801880-6c41-11e9-83f9-9a5f125b25d2.png">

**Comment by dotNetkow** [comment]
Working now. Likely a bug that was fixed.

**Comment by peterpeterparker** [comment]
Cool, thx for the feedback 😃
