### ISSUE TITLE
Component Demo/Preview - Nav

### ISSUE THREAD

**Issue by bensperry** [ionic-team/ionic-docs#68]
Updated design for the Nav component demo (mockup is in Android mode):
![image](https://user-images.githubusercontent.com/519526/43411854-0f15473e-93f1-11e8-944f-7b8548aab06b.png)

**Comment by bensperry** [comment]
Here's the iOS version:
![image](https://user-images.githubusercontent.com/519526/43418084-8976c5fa-9402-11e8-83a3-73de83f84a18.png)

**Comment by bensperry** [comment]
Here's the iOS mode:
![image](https://user-images.githubusercontent.com/519526/43418334-2fe5ce2c-9403-11e8-9822-2326f7d28b6d.png)

**Comment by dotNetkow** [comment]
[Looks done](https://ionicframework.com/docs/api/nav) to me.
