### ISSUE TITLE
menu-controller incorrect method name 

### ISSUE THREAD

**Issue by ab-kily** [ionic-team/ionic-docs#683]
**URL**
https://ionicframework.com/docs/api/menu-controller

**What is missing or inaccurate about the content on this page?**
according to the https://github.com/ionic-team/ionic/blob/master/angular/src/providers/menu-controller.ts , the correct name of swipe method is: 
`swipeEnable(shouldEnable: boolean, menuId?: string): Promise<HTMLIonMenuElement>`

but the docs says the method is:
`swipeGesture(shouldEnable: boolean, menuId?: string | null | undefined) => Promise<HTMLIonMenuElement | undefined>`

**Comment by dotNetkow** [comment]
Likely outdated docs at the time of opening this issue. Docs and Framework code now correctly use "swipeGesture." Thanks!
