### ISSUE TITLE
Native - Firebase messaging

### ISSUE THREAD

**Issue by hugoblanc** [ionic-team/ionic-docs#685]
**URL**
https://ionicframework.com/docs/native/firebase-messaging

**What is missing or inaccurate about the content on this page?**

Wrong "Usage" part. 
logEvent doesn't exist for this plugin but for cordova-plugin-firebase.

**Comment by amandaejohnston** [comment]
Thanks for the issue. It looks like this plugin has been removed from the docs since this was posted, so I'm going to go ahead and close this out.
