### ISSUE TITLE
Need to add Toggle and Radio demos

### ISSUE THREAD

**Issue by bensperry** [ionic-team/ionic-docs#69]
The Toggle and Radio component demos are missing from the [components page](https://beta.ionicframework.com/docs/components/)

**Comment by camwiegert** [comment]
I can't recall when, but at some point the decision was made to consolidate these two into [checkbox](https://beta.ionicframework.com/docs/components/#checkbox) as they're so similar. They're mentioned in the checkbox description. Want to resurrect them?

**Comment by bensperry** [comment]
🤔Good question.

I'm leaning towards yes, because the component page is really a "showcase" page, and it would be good to show all the components upfront. 

That said, Material docs consolidate Checkbox, Radio, and Toggle under one category called Selection Controls. Thoughts on that?

**Comment by camwiegert** [comment]
@bensperry Maybe this could be handled by our new UX for versions of a component?

**Comment by bensperry** [comment]
Yep 👍

**Comment by bensperry** [comment]
Will end up being something close to this:
![image](https://user-images.githubusercontent.com/519526/43660365-6c658882-9724-11e8-8c04-38ab9e4ee690.png)

**Comment by brandyscarney** [comment]
These exist now
