### ISSUE TITLE
Remove "Preview" tab for inline Nav content

### ISSUE THREAD

**Issue by bensperry** [ionic-team/ionic-docs#70]
I think we can keep the "Markup" content, but since the real "preview" is the actual demo on the right, we can just remove the inline "Preview" tab. Could look like this when we want to just show code/markup:

![image](https://user-images.githubusercontent.com/519526/43421708-20eef808-940d-11e8-9042-81bac0e7fb5c.png)

**Comment by camwiegert** [comment]
*Note* that we currently don't have a way to opt out of the HTML previews on a single code sample. We can only opt out for the entire page, so we'll need to make changes to the markdown renderer.
