### ISSUE TITLE
Usage for ion-picker component

### ISSUE THREAD

**Issue by capozzic1** [ionic-team/ionic-docs#711]
I think it would be helpful to have a 'usage' section for the ion-picker component. I see the ion-datetime component uses it, and I would like to use it directly. 

I've tried using it as:
`<ion-picker></ion-picker>`, but am not able to render the component.

**Comment by dotNetkow** [comment]
Thanks - good idea. In the meantime, from the Ion Picker docs page, please see the [demo source](https://github.com/ionic-team/ionic-docs/blob/master/src/demos/api/picker/index.html) that has examples.

**Comment by nicobytes** [comment]
Hello!

It would be great use ion-picker like a component.

https://forum.ionicframework.com/t/wheel-selector-inside-content/185828/3

**Comment by sebinbenjamin** [comment]
I'd like to contribute to the docs. I've read the [contributing guide](https://github.com/ionic-team/ionic-docs/blob/master/CONTRIBUTING.md). The API docs seem to be generated auto-generated from the main ionic repo. I have the changes in my fork. How do I run it locally before I put a PR?

**Comment by sean-perkins** [comment]
Hello everyone 👋  the picker component now has component playground examples available: https://ionicframework.com/docs/api/picker.

This allows you to see live examples of the picker usage for each supported framework. You can also open the examples in Stackblitz.
