### ISSUE TITLE
Header disappears after page load on mobile

### ISSUE THREAD

**Issue by jusfeel** [ionic-team/ionic-docs#72]
**I'm submitting a ...**  (check one with "x")
[x] bug report
[ ] feature request

**URL:**

https://beta.ionicframework.com/docs/api/action-sheet/
**Current behavior:**

No menu on mobile (it flashes and disappears)
**Expected behavior:**

Menu
**Steps to reproduce:**

Open https://beta.ionicframework.com/docs/api/action-sheet/ on chrome or safari in mobile
**Other information:**

**Comment by camwiegert** [comment]
I'm unable to reproduce this on iOS or Android, but this was a known issue with the docs during early alpha. Please ensure you're not getting any cached assets. If the problem persists, please provide platform info.

**Comment by jusfeel** [comment]
![chrome](https://user-images.githubusercontent.com/2442286/43523232-562863d4-95ce-11e8-8ced-2f2d9064f896.jpg)
Please check chrome system info on my phone(iOS).  It seems that the blue menu disappears after the page has been fully loaded.

**Comment by camwiegert** [comment]
Thanks for the info. I'm still unable to reproduce. I'm still suspicious that you're getting some long-cached styles. Does [this link](https://ionic-docs.herokuapp.com/docs/) have the same issue for you?

I'm going to rename this and leave it open for a bit in case others run into the issue.

**Comment by jusfeel** [comment]
It's the same. I don't think it's cache. It's the first time I visit it since it's beta 4 doc. My iOS is a bit old though.


--
Hao
  

At 2018-08-02 00:01:32, "Cam Wiegert" <notifications@github.com> wrote:


Thanks for the info. I'm still unable to reproduce. I'm still suspicious that you're getting some long-cached styles. Does this link have the same issue for you?

I'm going to rename this and leave it open for a bit in case others run into the issue.
