### ISSUE TITLE
ion toast wrong property css-class

### ISSUE THREAD

**Issue by carlosnewmusic** [ionic-team/ionic-docs#722]
**Describe the bug**
https://ionicframework.com/docs/api/toast#properties cssClass 
the attribute is wrong "css-class" instead of "cssClass"

**Comment by brandyscarney** [comment]
Thanks for the issue! The attribute is correct, if you are styling an element directly you would set the html in the following way:

```
<ion-toast css-class="class">
```

However, if you were to set it via JavaScript the property would be `cssClass`.  We have some more information on properties here: https://stenciljs.com/docs/properties
