### ISSUE TITLE
Broken link for Jins Meme

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#724]
This page:
https://ionicframework.com/docs/native/jins-meme

Has a 404 broken GitHub link. 

It looks like it should go to:
https://github.com/BlyncSync/JinsMemeSDK-Plugin-Cordova

**Comment by dotNetkow** [comment]
Thanks! Going to audit all the community plugins soon, including this one. I'll track this issue.

**Comment by dotNetkow** [comment]
Will be fixed in [upcoming ionic native PR](https://github.com/ionic-team/ionic-native/pull/3454).
