### ISSUE TITLE
Camera Docs encourages bad behavior

### ISSUE THREAD

**Issue by jasekiw** [ionic-team/ionic-docs#725]
The URL at which the content is missing or inaccurate: https://ionicframework.com/docs/native/camera

**What is missing or inaccurate about the content on this page?**
In the usage section, it shows how to use the camera with base64 data.
```
this.camera.getPicture(options).then((imageData) => {
 // imageData is either a base64 encoded string or a file URI
 // If it's base64 (DATA_URL):
 let base64Image = 'data:image/jpeg;base64,' + imageData;
}, (err) => {
 // Handle error
});
```

Using the base64 option causes crashes and will lead people down the wrong path if they are not familiar with the cordova plugin. This will hurt the user experience of the app since for older devices it will crash. I have actual customers reporting crashes on their devices when using this option.

Pulled from cordova's documentation:

```
Note: The image quality of pictures taken using the camera on newer devices is quite good. Encoding such images using Base64 has caused memory issues on some of these devices (iPhone 4, BlackBerry Torch 9800). Therefore, using FILE_URI as the 'Camera.destinationType' is highly recommended.
```

I have experienced this on iPhone 6s as well so in general this approach should not be used.

**Suggestion**
Only present the file_url option as it is a more stable solution and will provide a better experience for the developers using this plugin. Adding a note that tells the developer that the base64 option causes crashes and should be avoided is preferred as well.

**Comment by jasekiw** [comment]
In addition to this, most developers might then have the question of: How do I upload the saved image? Giving an example of using the [HTTP api ](https://ionicframework.com/docs/native/http) would be preferred to help ease them into the correct flow.

**Comment by jcesarmobile** [comment]
it might have changed, but on the getPicture it uses `this.camera.DestinationType.FILE_URI`

anyway, the docs come directly from the plugin docs, you can request a change here https://github.com/danielsogl/awesome-cordova-plugins/issues
