### ISSUE TITLE
feat: include Types in the docs

### ISSUE THREAD

**Issue by ctfrancia** [ionic-team/ionic-docs#726]
# Feature Request

**Ionic version:**

[x] **4.x**

**Describe the Feature Request**

One of the main time wasters that I find myself in is figuring out what types/interfaces is Ionic, Angular, Typescript.

**Describe Preferred Solution**

Include types in docs, the example below better demonstrates

**Describe Alternatives**

have a `cheatsheet` of the most commonly used that is Ionic specific

**Related Code**

```
  public onKeydown(ev: KeyboardEvent | EventTarget): void {
    if ((ev as KeyboardEvent).keyCode === 13) {
      this.sendMessage();
      (ev as EventTarget).target.blur(); //Error: Property 'target' does not exist on type 'EventTarget'
    } else {
      //stuff...
    }
    return;
  }
```
**Additional Context**

**Comment by liamdebeasi** [comment]
Thanks for the report, and apologies for the delay. We have added interfaces to our component docs. For example, `ion-input` has the `InputCustomEvent` interface that you can use: https://ionicframework.com/docs/api/input#interfaces
