### ISSUE TITLE
Ionic Native - Tealium

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#742]
**URL**
https://ionicframework.com/docs/native/tealium

Linked from the sidebar of the native section of the site, shows a 404 page.

FYI, There are two related sub plugins that depend on this which do exist:

https://ionicframework.com/docs/native/tealium-adidentifier

https://ionicframework.com/docs/native/tealium-installreferrer

**Comment by dotNetkow** [comment]
Fixed with recent Ionic Native PR.
