### ISSUE TITLE
Docs - Changelog not loading

### ISSUE THREAD

**Issue by mswilson4040** [ionic-team/ionic-docs#75]
**I'm submitting a ...**  (check one with "x")
[x ] bug report
[ ] feature request

**URL:**
https://beta.ionicframework.com/docs/faq/changelog

**Current behavior:**
Error: Unable to fetch faq/changelog:

**Expected behavior:**
The page should load and display the change log

**Steps to reproduce:**
Go to https://beta.ionicframework.com/docs/faq/changelog

**Other information:**
No other information needed.

**Comment by camwiegert** [comment]
@mswilson4040 Thanks for opening this. That page wasn't loading because... it doesn't exist. 😄 I noticed it was linked from the books page, though, so I removed it.
