### ISSUE TITLE
Windows: JSON generation puts files in wrong folders

### ISSUE THREAD

**Issue by drdreo** [ionic-team/ionic-docs#761]
**Describe the bug**
Running the docs on windows 10 generates some pages in wrong folders.
It removes parts of the absolute path and generates the files there. 

**To Reproduce**
1. copy repo
2. npm install
3. npm run
4. Everything works, except the static pages served aren't found by the  server

**Expected behavior**
Server can serve the right files. The .json generation puts the files in the right folder.

**Additional context**
In the file `scripts/build-pages/index.ts` the method `toFilePath` at the end of the file converts the file path wrong on windows 10.
Example path before and after:
Before: `C:/Users/me/downloads/ionic-docs-master/src/pages/enterprise/identity-vault/3.0.X/identity-vault` 
After:  `C:\Users\me\downloads\ionic-docs-master\src\pages\rs\me\downloads\ionic-docs-master\src\pages\enterprise\identity-vault\3.0.X\identity-vault.json`

This happens due to  ``` `${resolve(PAGES_DIR, urlPath.slice(6) || 'index')}.json\`; ```  the slice(6) removes the C:/Use and this generates the "...rs\..." path. 

My quick fix is:

```js
const toFilePath = (urlPath: string) =>
  `${resolve(PAGES_DIR, urlPath.slice(6) || 'index')}.json`;

const toFilePathWindows = (urlPath: string) => {
  if (urlPath.startsWith("C:")) {
    urlPath = urlPath.replace(/\//g, "\\");
    return `${urlPath}.json`;
  }
  else {
    return `${resolve(PAGES_DIR, urlPath.slice(6))}.json`;
  }
}
```

**Comment by frederikprijck** [comment]
Had the same issue, the fix allowed me to run the docs locally.

As mentioned on slack, we probably want to ensure it's a little bit smarter on Windows (like not hardcoding the `C` drive etc).

But for anyone encountering the issue in the meantime, the above fix should work fine!

**Comment by dotNetkow** [comment]
At long last, we believe the issue is fixed. Please pull latest from master and reopen this if you still encounter issues. Thanks!
