### ISSUE TITLE
[beta docs] Code blocks display any content on single line

### ISSUE THREAD

**Issue by andy-rash** [ionic-team/ionic-docs#768]
**Describe the bug**
Code blocks display contents on a single line, even when they contain non-one-liners.

**To Reproduce**
1. Go to: https://beta.ionicframework.com/docs/layout/grid#how-it-works
2. See error

**Expected behavior**
Code blocks should display multi-line code samples on multiple lines.

**Screenshots**
Error: https://i.imgur.com/x6Goiga.png

**Browser and OS (please complete the following information):**
 - OS: macOS 10.14.5 Mojave
 - Browser: Chrome Version 74.0.3729.169 (Official Build) (64-bit)
 - Version: n/a

**Additional context**
I cloned the ionic docs repo and ran it locally and I saw no display errors.

Additionally, I've seen this and other issues on multiple other occasions, though I don't have screenshots for these instances. For example, one time after visiting the [layout/grid page](https://beta.ionicframework.com/docs/layout/grid), the entire "Customizing the grid" portion of the page would follow to other pages. Unfortunately, I cannot reproduce this error.

**Comment by dotNetkow** [comment]
Hi there - thanks for the issue. Apologies if this isn't clear, but this issue is related to the Beta site of the Ionic docs (beta.ionicframework.com), rather than the production version (ionicframework.com/docs). It's used occasionally by the Ionic team for testing purposes only, which is why you didn't see any errors when you cloned the code. If you do see issues with grid layout or others on the prod site, please don't hesitate to log them in the future. Thanks!

**Comment by andy-rash** [comment]
Thanks for the response @dotNetkow . I think part of why I opened this issue was because I was (and still do on occasion) getting redirected to beta.ionicframework.com from the production website. It hasn't happened deterministically enough for me to notice any sort of pattern, however. This is kind of annoying, especially when, for instance, I see usage information on the production website, and then later when I need to see it again the link takes me to the beta website and am met with something like:

**Usage**
`[object Object]`

...which is useless and has definitely happened to me on more than one occasion.

**Comment by dotNetkow** [comment]
Thanks for further clarifying! That is strange, and shouldn't happen of course. I'll check with the team. If you see it in action again, let us know. Thanks!
