### ISSUE TITLE
FileTransfer is deprecated

### ISSUE THREAD

**Issue by mrambow** [ionic-team/ionic-docs#770]
**URL**
https://ionicframework.com/docs/native/file-transfer

**What is missing or inaccurate about the content on this page?**
The Fileplugin from cordova is deprecated in favour of XHR2
see: https://cordova.apache.org/blog/2017/10/18/from-filetransfer-to-xhr2.html

**Comment by dotNetkow** [comment]
Good catch - this was listed in the plugin, but due to bad formatting wasn't being displayed. Will be fixed in [this PR](https://github.com/ionic-team/ionic-native/pull/3454).
