### ISSUE TITLE
Js Crashing, Unable to use Drop Downs or Search Docs

### ISSUE THREAD

**Issue by jjohnson1994** [ionic-team/ionic-docs#774]
**Describe the bug**
Originally I thought this was only related to switching frameworks, but it's actually the whole docs. I cannot use any dropdowns or the search feature.

I'm unable to switch between Ionic framework when returning to the Ionic docs. The framework select box the top left only shows Angular and does nothing when clicked. The framework options, usually shown above code samples, also aren't visible. I also have a lot of possibly related errors in the console (screenshot below).

Clearing site data and refreshing the page sometimes fixes this.

**To Reproduce**
1. https://ionicframework.com/docs/components
2. Click around and view docs
3. Switch between framework, either in the top left of the page or above code samples
4. Leave the page and return after some time (this was overnight).
5. Framework select box and framework options are no longer available.

**Expected behavior**
To be able to the switch between frameworks and see code example for each framework version.

**Screenshots**
![image](https://user-images.githubusercontent.com/23138767/59979036-4edc9980-95da-11e9-84cc-82ac22feaa79.png)
![image](https://user-images.githubusercontent.com/23138767/59979040-54d27a80-95da-11e9-9775-fbbeab28b95f.png)

**Browser and OS (please complete the following information):**
 - OS: Mac OS Mojave 10.14.5
 - Browser Chrome
 - Version 74.0.3729.169 (Official Build) (64-bit)

**Comment by jjohnson1994** [comment]
Update on the above. It looks like everything on the page is crashing, none of the drop downs work and I cannot search the docs.

**Comment by dotNetkow** [comment]
Can you try a hard refresh (hold down Shift key then reload) as a quick fix? We're investigating this.

**Comment by jjohnson1994** [comment]
Did try a hard refresh at the time but that didn't help.

**Comment by dotNetkow** [comment]
We've had multiple updates since then, is this still an issue? if so, please let me know browser you're using, etc. Thanks!
