### ISSUE TITLE
Bring back the scrollable kitchen sink

### ISSUE THREAD

**Issue by shamilovtim** [ionic-team/ionic-docs#782]
Ever since the kitchen sink was removed it is harder to understand visually what components Ionic provides and it's more difficult to sell Ionic to stakeholders without them easily being able to scroll the beautiful components that Ionic provides. I'm not saying that you have to remove the granular developer docs for components but I strongly urge you to bring back the scrollable kitchen sink and make it front and center on the website again.

**Comment by dotNetkow** [comment]
Thanks for the issue. We've since implemented this version - the [root/main UI components page](https://ionicframework.com/docs/components), that shows off all components.
