### ISSUE TITLE
Broken Ionic Framework CDN URLs

### ISSUE THREAD

**Issue by sebinbenjamin** [ionic-team/ionic-docs#794]
**https://ionicframework.com/docs/installation/cdn#ionic-framework-cdn**

Ionic CDN URLs given incorrectly on the docs page.

![image](https://user-images.githubusercontent.com/4099066/60390829-ef601b80-9afc-11e9-97ef-697fc571cd6e.png)

```
<script src="https://unpkg.com/@ionic/core@latest/dist/ionic.jscore@latest/dist/ionic.js"></script>
<link href="https://unpkg.com/@ionic/core@latest/css/ionic.bundle.csscore@latest/css/ionic.bundle.css" rel="stylesheet">

```

**Comment by sebinbenjamin** [comment]
Strangely, the URLs are correct in the source code at [https://github.com/ionic-team/ionic-docs/blob/master/src/pages/installation/cdn.md#ionic-framework-cdn](https://github.com/ionic-team/ionic-docs/blob/master/src/pages/installation/cdn.md#ionic-framework-cdn) and it is show correctly when runing the documentation locally.

**Comment by dotNetkow** [comment]
Looks like this was a Cloudfare issue that we've now resolved. Can you reload the page and confirm? thanks.

**Comment by sebinbenjamin** [comment]
Yay, it's working correctly now. 👍
