### ISSUE TITLE
Improve ion-loading with async / rxjs example

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#799]
**URL**
https://ionicframework.com/docs/api/loading

I just used this page for the first time and it wasn't very helpful to me.

It describes scenarios where they auto-dismiss after a while, but I imagine that in almost all real-world scenarios this is going to be used to wrap around some async operation.

For my first experience, it wasn't clear how to structure this or how to hook it into the end of the observable.

I've currently got this going on but I know it's not yet right (for example the tap doesn't handle error scenario):

```
  async ngOnInit() {
    let loader = await this.loadingController.create({ 
      spinner: 'crescent',
      message: 'Loading feed'
    });

    await loader.present();
    this.posts$ = this.route.paramMap.pipe(
      switchMap(
        (params: ParamMap) =>
          params.get("category")
           ? this.postsService.fetchPostsByCategory(params.get("category"))
           : this.postsService.fetchPosts()
      ),
      tap((data) => console.log(data)),
      tap(() => loader.dismiss())
    );
  }
```

I know you cannot cover all scenarios but rxjs is a part of Angular so it seems reasonable to support this with the docs?

**Comment by dotNetkow** [comment]
Thanks for logging this. I'm not sure RxJS is something we'll tackle honestly. The challenge is that there are so many ways to use Ionic components, whether on their own or with endless other libraries, so we'll never be able to cover them all. Hence why we intentionally keep the UI component docs simple.

That said, an RxJS guide in the main Framework docs would be nice to have.

**Comment by wflemingnz** [comment]
@rtpHarry not sure how much further you got with your example code, but:

> for example the tap doesn't handle error scenario

can be resolved by using `finalize` which is called when the observable completes ie:

` finalize(() => loader.dismiss())`
