### ISSUE TITLE
cli: npm update ionic@latest code rendered twice 

### ISSUE THREAD

**Issue by Siedlerchr** [ionic-team/ionic-docs#800]
**Describe the bug**
Under the section troubleshooting the command `npm install -g ionic@latestionic@latest`  is shown which is wrong.

**To Reproduce**
1. Go to https://ionicframework.com/docs/cli
2- Scroll down to Troubleshooting
3. See error

**Expected behavior**
Cmmand listed as  `npm install -g ionic@latest`

**Screenshots**
![grafik](https://user-images.githubusercontent.com/320228/60493153-9afb9e00-9cac-11e9-8bd6-76ec99253eef.png)

**Browser and OS (please complete the following information):**
 - OS:  Windows 10
 - Browser  Firefox
 - Version 67
**Additional context**

**Comment by dotNetkow** [comment]
Looks like this was a Cloudfare issue that we've now resolved. Can you reload the page and confirm? thanks.

**Comment by Siedlerchr** [comment]
Looks good now.
