### ISSUE TITLE
Ionic Infinite Scroll example not firing event

### ISSUE THREAD

**Issue by Kerrex** [ionic-team/ionic-docs#803]
**Describe the bug**
Infinite scroll not working

**To Reproduce**
1. Go to 'https://ionicframework.com/docs/api/infinite-scroll'
2. Try to scroll example on the right
3. New content is not loading and there's blank space instead of the loader

**Expected behavior**
New content should load

**Browser and OS (please complete the following information):**
 - Ubuntu Linux
 - Chrome
 - Version 75.0.3770.100

**Additional context**
It looks like `ionInfinite` event is not working. Firing it manually via console triggers loading additional content.
Actually I'm having the same problem on my newly created project using Ionic CLI 5.2.1, Angular 7.2.2

**Comment by jneumann83** [comment]
I fix this problem, after updating the packages.
npm outdated and then I updated the following packages:

npm i -g ionic
npm rm @ionic-native/admob-pro & npm add @ionic-native/admob-pro
npm rm @ionic-native/app-rate & npm add @ionic-native/app-rate
npm rm @ionic-native/app-version & npm add @ionic-native/app-version
npm rm @ionic-native/core & npm add @ionic-native/core
npm rm @ionic-native/deeplinks & npm add @ionic-native/deeplinks
npm rm @ionic-native/device & npm add @ionic-native/device
npm rm @ionic-native/firebase & npm add @ionic-native/firebase
npm rm @ionic-native/google-analytics & npm add @ionic-native/google-analytics
npm rm @ionic-native/keyboard & npm add @ionic-native/keyboard
npm rm @ionic-native/network & npm add @ionic-native/network
npm rm @ionic-native/open-native-settings & npm add @ionic-native/open-native-settings
npm rm @ionic-native/push & npm add @ionic-native/push
npm rm @ionic-native/screen-orientation & npm add @ionic-native/screen-orientation
npm rm @ionic-native/social-sharing & npm add @ionic-native/social-sharing
npm rm @ionic-native/splash-screen & npm add @ionic-native/splash-screen
npm rm @ionic-native/status-bar & npm add @ionic-native/status-bar
npm rm @ionic/angular & npm add @ionic/angular
npm rm @ionic/cli-framework & npm add @ionic/cli-framework
npm rm @ionic/core & npm add @ionic/core
npm rm @ionic/discover & npm add @ionic/discover

**Comment by dotNetkow** [comment]
The docs page example works for me - is this still an issue?

If you're seeing an issue within an Ionic app you're building, then please log an issue [here](https://github.com/ionic-team/ionic).
