### ISSUE TITLE
<ion-input> type File

### ISSUE THREAD

**Issue by JEricaM** [ionic-team/ionic-docs#813]
**URL**
https://ionicframework.com/docs/api/input?fbclid=IwAR3q7L8eSkFqKBomK2NM94SG51wSvIZMib7md5iON-cDVbEHL-CovS3Prx0

**What is missing or inaccurate about the content on this page?**
In the ion-input page it's written that ion-input accept "text", "password", "email", "number", "search", "tel", and "url".

By the way, in the Properties section, in the accept paragraph it's written:
"If the value of the type attribute is "file", then this attribute will indicate the types of files that the server accepts, otherwise it will be ignored."
Reading this suggests that it is possible to use the "file" type as an ion-input type but is not. 

I think that this part of the doc should be more clear :)

**Comment by brandyscarney** [comment]
I know this issue is older but I'm going to combine this with https://github.com/ionic-team/ionic-docs/issues/814 since that one has more comments on it. Thank you!
