### ISSUE TITLE
CLI start doc does not explain difference between values for --type flag

### ISSUE THREAD

**Issue by AndrWeisR** [ionic-team/ionic-docs#821]
**URL**
https://ionicframework.com/docs/cli/commands/start

The docs do not explain the purpose of the different --type arguments, in particular the difference between 'angular' and 'ionic-angular'. This is important missing information.

**Comment by jcesarmobile** [comment]
closing since it includes `For example, you can start an Ionic 3 project with --type=ionic-angular`, so I think it's explained.

But `--type=ionic-angular` is not supported in Ionic CLI 7, so in fact should be removed.
