### ISSUE TITLE
Document multi-app config

### ISSUE THREAD

**Issue by dwieeb** [ionic-team/ionic-docs#83]
See https://github.com/ionic-team/ionic-cli/issues/3281

**Comment by ehorodyski** [comment]
Has this been documented?

**Comment by dwieeb** [comment]
@ehorodyski Not yet, but subscribe to this issue for updates.

**Comment by vadost** [comment]
@dwieeb Hi, when will any updates?

**Comment by dwieeb** [comment]
👋 

I added some docs for multi-app here: https://beta.ionicframework.com/docs/cli/configuration#multi-app

Please feel free to provide any feedback! I tried to keep it framework-agnostic. Additional configuration is necessary for Angular. I think these are the best docs they have for that: https://github.com/angular/angular-cli/wiki/stories-multiple-projects

It's a new feature for both Ionic and Angular, so there isn't much documentation/tutorials out there yet.

**Comment by travismarx** [comment]
@dwieeb thanks for this. I've been looking forward to it. Suggestions I would have would be:

- Clarify the initial app starting process. Do you still create the initial app with the ionic-cli? Do you pass any special parameters when doing so? Manually create your ionic.config.json? 

- Are the lib and apps folders created automatically with ionic-cli, angular-cli, or manually? In the example folder structure photo under https://beta.ionicframework.com/docs/cli/configuration#multi-app-config-file, apps is under src, but in the code example under https://beta.ionicframework.com/docs/cli/configuration#adding-an-app-to-a-multi-app-project it would appear that the apps folder is a direct child of the root project folder.

It's a great start, I think just a little more documentation and clarification would get things going down  a smooth path.

**Comment by dwieeb** [comment]
@travismarx Thanks for the feedback! 👍 Yeah it's certainly not a smooth process yet. In fact, I found a bug while writing the setup steps, which should clear up some things.

**Comment by davl3232** [comment]
Thank you @benorama!

**Comment by idanzapp** [comment]
using `ionic g service services/data-feed --project=benight-admin`
got this =>
```
> ng generate service services/data-feed --project=benight-admin
Two or more projects are using identical roots. Unable to determine project using current working directory. Using default workspace project instead.
```
so it would be nice to give --project support to `@ionic/schematics-angular` aswell

**Comment by dwieeb** [comment]
@idanzapp That specific error looks like an issue with your `angular.json` configuration, but there are quite a few improvements we need to make to properly handle `generate` for multi-app projects.

Just created a few issues that people can subscribe to if they like:
* https://github.com/ionic-team/ionic-cli/issues/3744
* https://github.com/ionic-team/angular-toolkit/issues/34

**Comment by idanzapp** [comment]
thanks @dwieeb ill stay tunned, i know the warning is due to my angular.json, but im sharing tsconfig.json, theme, and enviroments through 3 apps, and i had to do some weird stuff in order to get paths on tsconfig working

**Comment by Binero** [comment]
I don't think the [docs](https://beta.ionicframework.com/docs/cli/configuration#project-structure) are correct.

> If a multi-app project is detected during ionic start, the CLI will add the app configuration to the root ionic.config.json file instead of creating a project-specific one.

However, if I create an empty `ionic.config.json` with the following contents, and run `ionic start`, no projects are added to the existing config in the root, but instead a new one is created in a sub-folder. 

```json
{
    "projects": {}
}
```

**Comment by Binero** [comment]
Seems like it's a chicken-egg problem. To create a multi-app project, one needs to have already filled in the config with dummy data, otherwise `ionic-cli` won't detect the multi-app setup. Simply having `"projects": {}` is not sufficient. 

This should be clarified in the docs somehow. Likely, the way the tools works should be updated too. The `ionic start` script should be able to run without any project currently loaded (as there might be none).

**Comment by dwieeb** [comment]
Thanks @Binero! I just pushed a fix for that. It will be included in CLI 4.4.0 (probably will be released tomorrow).

**Comment by dwieeb** [comment]
CLI 4.4.0 is out!

**Comment by dwieeb** [comment]
I'm gonna consider this issue resolved.

Please follow these issues for updates about multi-app re: `ionic generate`:
* https://github.com/ionic-team/ionic-cli/issues/3744
* https://github.com/ionic-team/angular-toolkit/issues/34
