### ISSUE TITLE
appflow/package/credentials "Find your UDID." links to nonexisting page

### ISSUE THREAD

**Issue by janpio** [ionic-team/ionic-docs#833]
https://github.com/ionic-team/ionic-docs/blob/master/src/pages/appflow/package/credentials.md

```
[Find your UDID](/services/profiles/ios-udid.html).
```

That page is a 404: https://ionicframework.com/services/profiles/ios-udid.html

**Comment by dotNetkow** [comment]
[Updated the docs](https://github.com/ionic-team/ionic-docs/commit/6793471049418c9f9aea7af542d9c6759e14a5bf); should be live shortly.
