### ISSUE TITLE
I can't find documentation for a new plugin

### ISSUE THREAD

**Issue by srinidhirao** [ionic-team/ionic-docs#840]
**URL**
https://ionicframework.com/docs/native/overview

**What is missing or inaccurate about the content on this page?**
I don't find the documentation for the [unvired-cordova-sdk](https://github.com/ionic-team/ionic-native/pull/3090) plugin which is published to ionic-native. I thought it would be automatically created, but I don't see that happening. What is the process to publish the docs?

I'm not clear on what I'm supposed to get the plugin doc appear on the site. Can you please help?

**Comment by srinidhirao** [comment]
Can you please have a look at this? What do I have to get the plugin published?

**Comment by dotNetkow** [comment]
Apologies for the delay. Since native plugins exist in two spots, both the Ionic Native code and the Ionic docs, there's a manual step to get the docs updated. [It's available now.](https://ionicframework.com/docs/native/unvired-cordova-sdk)
