### ISSUE TITLE
IE11 doesn't display website correctly

### ISSUE THREAD

**Issue by BorntraegerMarc** [ionic-team/ionic-docs#841]
**Describe the bug**
I think this Screenshot says it all:

![Screenshot (2)](https://user-images.githubusercontent.com/7549295/61628558-eb9a6180-ac82-11e9-97dd-32da61d77022.png)

**To Reproduce**
Go to https://ionicframework.com/docs on IE11

**Expected behavior**
It should work on IE11 as ionic supports IE11.

**Screenshots**
![Screenshot (3)](https://user-images.githubusercontent.com/7549295/61628615-15538880-ac83-11e9-9911-312894c44475.png)

**Browser and OS (please complete the following information):**
 - OS: Windows 10
 - Browser IE11

**Additional context**

**Comment by dotNetkow** [comment]
Thanks for submitting this - unfortunately, modern browsers are required to view the docs.

**Comment by BorntraegerMarc** [comment]
Well, it's just that I thought the docs can be displayed from any browser that Ionic actually supports.
