### ISSUE TITLE
Beta docs missing CSS from CDN

### ISSUE THREAD

**Issue by lightbeard** [ionic-team/ionic-docs#85]
CDN install docs [here](https://beta.ionicframework.com/docs/installation/cdn) are missing how to add Ionic 4 CSS.

For example, shouldn't something like this be added?

**Ionic CSS from a CDN**

Similarly, Ionic stylesheets are available from CDN with [unpkg](https://unpkg.com/#/). To add the latest available minified CSS stylesheets add the following tag inside `<head></head>`.

`<link rel="stylesheet" href="https://unpkg.com/@ionic/core@latest/css/ionic.min.css">`

**Comment by camwiegert** [comment]
@lightbeard Thanks for opening this. I'm going to close it in favor of #54 where it is being addressed.
