### ISSUE TITLE
v3 docs: On-page search results navigate to v4 doc pages

### ISSUE THREAD

**Issue by arLevi** [ionic-team/ionic-docs#874]
**Description**
Unable to review v3 docs, even though the docs site support it.

**To Reproduce**
1. Browse: https://ionicframework.com/docs/v3/
2. Search "button"
3. Click on "button" from the results

**Expected behavior**
You suppose to see version3 docs of component "button"
Instead, you're going back to the button-v4-version .

**Comment by rtpHarry** [comment]
A better title for this would be "v3 docs on-page search results go to docs v4 urls".

You can see still access it via the side menu.
