### ISSUE TITLE
display issue with ios example mobile - top content border pops to square after load

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#910]
**Describe the bug**
The page loads with normal curved borders at the start, then it pops out the design into a square border. Only happens on IOS mobile example. Screenshot below.

**To Reproduce**
1. Go to https://ionicframework.com/docs/api/loading / https://ionicframework.com/docs/api/radio / any page with an example.
2. Wait for the page to load
3. See error

**Expected behavior**
Display correctly.

**Screenshots**
![image](https://user-images.githubusercontent.com/1038062/63783591-753eee00-c917-11e9-9f09-d8529ba8eda0.png)

**Browser and OS (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome Version 76.0.3809.100 (Official Build) (64-bit)

**Additional context**

**Comment by dotNetkow** [comment]
Just tried this on Windows 10 with latest Chrome - appears to be fixed. Please comment if it needs to be reopened. Thanks!
