### ISSUE TITLE
Modal Dialog not working as in the Documentation

### ISSUE THREAD

**Issue by lognad** [ionic-team/ionic-docs#925]
const modal = await this.modalController.create({
      component: ModalPage
    });

Creating Modal Dialog using this method throws error: 
ERROR
Error: Uncaught (in promise): Error: No component factory found for [object Object]. Did you add it to @NgModule.entryComponents?
Error: No component factory found for [object Object]. Did you add it to @NgModule.entryComponents

Works only when using 

     const modal = await this.modalController.create(ModalPage);

https://stackblitz.com/edit/ionic-cdcv8i

**Comment by brandyscarney** [comment]
Thanks for the issue! Your stackblitz is using `ionic-angular` version `3.9.2`. Our latest version of Ionic with Angular is `4.9.0`. If you're looking for steps to migrate please check our migration guide: https://ionicframework.com/docs/building/migration

For the v3 docs please visit this link: https://ionicframework.com/docs/v3/
