### ISSUE TITLE
toast button with role 'cancel' skips handler call

### ISSUE THREAD

**Issue by rtpHarry** [ionic-team/ionic-docs#966]
**URL**
https://ionicframework.com/docs/api/toast

**What is missing or inaccurate about the content on this page?**
Based on a [conversation that's come up](https://stackoverflow.com/questions/57993500/button-handler-in-toast-message-ionic-4-is-not-fired-why) on StackOverflow it seems that having `role: 'cancel'` in the click handler prevents the `console.log` from logging:

![image](https://user-images.githubusercontent.com/1038062/65166531-16c6e480-da6b-11e9-8712-83086d14f4a2.png)

I've tested this myself and have confirmed it is creating this issue.

Can anyone give me the OK that the correct resolution is to simply remove the `role: 'cancel'` line? Does anything else depend on this? If it's ok to remove, is this true for all libraries (angular / js / react / vue)?

I will create a PR, and also add in `await` before each `toast.present()`.

**Comment by dotNetkow** [comment]
Given that the ToastButton interface has the `role` property defined:

`role?: 'cancel' | string;`

So, while removing it was a successful workaround, it's not what actually should be done - This seems like a Framework bug to me. @brandyscarney ?

**Comment by brandyscarney** [comment]
So it seems like the cancel role is handled differently in that it does not call the handler method at all:

```
private async buttonClick(button: ToastButton) {
  const role = button.role;
  if (isCancel(role)) {
    return this.dismiss(undefined, role);
  }
  const shouldDismiss = await this.callButtonHandler(button);
  if (shouldDismiss) {
    return this.dismiss(undefined, button.role);
  }
  return Promise.resolve();
}
```

I think this is a bug. This is also how alert & action sheet work though, so will need to evaluate that.

**Comment by rtpHarry** [comment]
I think this might be a dup now, but i'll leave it for you to close as you have identified issues with alert and actionsheet as well:

https://github.com/ionic-team/ionic/issues/19791

**Comment by dotNetkow** [comment]
Yes thanks Matthew! It'll be fixed in the next release.
