### ISSUE TITLE
missed closing tag '</ion-item-sliding>'

### ISSUE THREAD

**Issue by skipokylas** [ionic-team/ionic-docs#977]
**URL**
The URL at which the content is missing or inaccurate
missed closing tag '</ion-item-sliding>'
**What is missing or inaccurate about the content on this page?**

**Comment by brandyscarney** [comment]
Could you please provide the URL where this is? Thanks!

**Comment by skipokylas** [comment]
looks like it's fixed in this commit https://github.com/ionic-team/ionic-docs/commit/b50bfc1591672e88f765f92d8a29d53cca4bcc0e
